# Prep

## Import stuff

In [1]:
import pandas as pd
pd.set_option('max_colwidth', 100)
import numpy as np
import matplotlib.pyplot as plt
from sklearn import svm, datasets
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import label_binarize
from sklearn.multiclass import OneVsRestClassifier
from sklearn.metrics import confusion_matrix
import itertools
import scipy.stats as st
from scipy import stats
from sklearn.feature_selection import mutual_info_classif
#import seaborn as sns
#from matplotlib import pyplot as plt
#%matplotlib inline
pd.set_option('display.max_rows', 100)
pd.set_option('display.max_columns', 500)
import rpy2
#import pingouin as pg
from itertools import combinations
import openpyxl
from contextlib import redirect_stdout
import random
import math

## Some magical magic to make the R stuff work

In [2]:
# fix from here https://github.com/rpy2/rpy2/issues/882
import os
#os.environ['R_HOME'] = '/Users/zeleninam2/miniconda3/envs/env_hitop_3way_2026/lib/R' # change this to whatever is relevant to you, or you might not need this line at all.

os.environ["OMP_NUM_THREADS"] = "1"
os.environ["OPENBLAS_NUM_THREADS"] = "1"
os.environ["MKL_NUM_THREADS"] = "1"

import rpy2.robjects as ro
from rpy2.robjects.packages import importr
from rpy2.robjects import pandas2ri
import rpy2.ipython.html
rpy2.ipython.html.init_printing()
from rpy2.rinterface_lib.embedded import RRuntimeError

rbase = importr('base')
utils = importr('utils')
lavaan = importr('lavaan')
semtools = importr('semTools')

In [3]:
# importing stuff the right way
try:
    semTools_version = '.'.join([str(ii) for ii in list(ro.r('packageVersion("semTools")')[0])])
except RRuntimeError:
    semTools_version = ''
# There's a bug in the main semtools libarary, this install from my fork of semtools where I've fixed it.
if semTools_version != '0.5.6.933':
    ro.r("""
        library(devtools)
        install_github("shotgunosine/semTools/semTools@aa68e38f88d9dd881617d5ade429bde2b2a74e08")
        """
    )

## Paths

In [4]:
path_to_item_lookup = '../../data/ValSample/Internalizing-Somatoform Items_DW.xlsx'
path_to_cogmood_questions = '../../data/CFA/cogmood_questions.csv'
path_to_valsample = '../../data/ValSample/inters23.xlsx'
path_to_codesheet = '../../dylan_github/yougov_codesheet_alignment.tsv'
path_to_genpop = '../../data/NIMH0007_genpop_num_OUTPUT.csv'
path_to_enriched = '../../data/NIMH0007_mental_health_num_OUTPUT.csv'
path_to_helpfile = '/Users/zeleninam2/Documents/1_projects/hitop/data/CFA/temp/cfa_temp.csv'

## Count how many cpus I have, then decide how many I want to use; define how many iterations for CFA (decrease for debugging)

In [5]:
total_cpus = os.cpu_count()
cpus_to_use = total_cpus-2
global cpus_to_use
print(f"\nGoing to use {cpus_to_use} CPUs for CFA heavy-lifting\n")

num_iter = 1000
global num_iter

Going to use 10 CPUs for CFA heavy-lifting

## SET SEEDS !!!!!!!!!!

In [6]:
#rngkind = "L'Ecuyer-CMRG"
random.seed(12345)

In [7]:
ro.r('RNGkind(kind = "L\'Ecuyer-CMRG")')
ro.r('set.seed(12345)')

<rpy2.rinterface_lib.sexp.NULLType object at 0x157eccad0> [0]

### TEST THE SEEDS!!!!!!!!

In [8]:
for i in range(5):
    print(random.random())
# after kernel restart, this should be 
# 0.41661987254534116
# 0.010169169457068361
# 0.8252065092537432
# 0.2986398551995928
# 0.3684116894884757

0.41661987254534116
0.010169169457068361
0.8252065092537432
0.2986398551995928
0.3684116894884757

In [9]:
ro.r('rnorm(5)')
# after kernel restart, this should be 
# -1.457850350316457	-0.45246126454182867	0.3650586371545244	-1.57091128601566	1.1419085835874878

<rpy2.robjects.vectors.FloatVector object at 0x310cf5850> [14]
R classes: ('numeric',)
[-1.457850, -0.452461, 0.365059, -1.570911, 1.141909]

### I'M ALSO SETTING THE SAME SEEDS EVERY TIME I RUN THE HELPED CFA FUNCTION, JUST IN CASE!!!!!

# Functions

## Functions for loading and processing data

In [10]:
def make_hitop_list(data):
    # only hitop cols
    hitop_cols = []
    for c in data.columns:
        if 'hitop' in c and 'today' not in c:
            hitop_cols.append(c)   
    return(hitop_cols)

def make_recontact_list(data):
    list_recontact = []
    for c in data.columns:
        if 'recontact' in c:
            list_recontact.append(c)
    return(list_recontact)

def do_checks(dat, remove_checks):
    assert remove_checks in ['no', 'yes', 'grid', 'gridinitialvisitonly']
    dat['passed_checks'] = True
    dat['passed_grid'] = True
    dat['passed_grid_initialonly'] = True
    dat['passed_list'] = True
    dat.loc[dat.check_moderately != 3, 'passed_checks'] = False
    dat.loc[dat.check_notatall != 1, 'passed_checks'] = False
    dat.loc[dat.check_moderately != 3, 'passed_grid'] = False
    dat.loc[dat.check_notatall != 1, 'passed_grid'] = False
    dat.loc[dat.todaycheck_1 != 1, 'passed_checks'] = False
    dat.loc[dat.todaycheck_2 != 1, 'passed_checks'] = False
    dat.loc[dat.todaycheck_1 != 1, 'passed_list'] = False
    dat.loc[dat.todaycheck_2 != 1, 'passed_list'] = False
    # deal with attention checks - recontact
    dat['passed_checks_recontact'] = True
    dat['passed_grid_recontact'] = True
    dat['passed_list_recontact'] = True
    dat.loc[dat.check_moderately_recontact != 3, 'passed_checks_recontact'] = False
    dat.loc[dat.check_notatall_recontact != 1, 'passed_checks_recontact'] = False
    dat.loc[dat.check_moderately_recontact != 3, 'passed_grid_recontact'] = False
    dat.loc[dat.check_notatall_recontact != 1, 'passed_grid_recontact'] = False
    dat.loc[dat.todaycheck_1_recontact != 1, 'passed_checks_recontact'] = False
    dat.loc[dat.todaycheck_2_recontact != 1, 'passed_checks_recontact'] = False
    dat.loc[dat.todaycheck_1_recontact != 1, 'passed_list_recontact'] = False
    dat.loc[dat.todaycheck_2_recontact != 1, 'passed_list_recontact'] = False
    print('checks_initial:')
    print(1 - dat.loc[:, ['passed_checks', 'passed_grid', 'passed_list']].mean())
    how_many_passed_checks = dat['passed_checks'].value_counts()[True]
    how_many_overall = dat.shape[0]
    print('Passed checks: %d out of %d' % (how_many_passed_checks, how_many_overall))
    print('checks_recontact:')
    print(1 - dat.loc[:, ['passed_checks_recontact', 'passed_grid_recontact', 'passed_list_recontact']].mean()) 
    how_many_passed_checks_recontact = dat['passed_checks_recontact'].value_counts()[True]
    print('Passed checks: %d out of %d' % (how_many_passed_checks_recontact, how_many_overall))
    if remove_checks == 'yes':
        print('removing checks')
        dat = dat.loc[dat['passed_checks'] == True]
        dat = dat.loc[dat['passed_checks_recontact'] == True]
        print(dat.shape)
        print('done removing checks')
    elif remove_checks == 'grid':
        print('removing checks')
        dat = dat.loc[dat['passed_grid'] == True]
        dat = dat.loc[dat['passed_grid_recontact'] == True]
        print(dat.shape)
        print('done removing checks') 
    elif remove_checks == 'gridinitialvisitonly':
        print('removing checks')
        dat = dat.loc[dat['passed_grid'] == True]
        print(dat.shape)
        print('done removing checks')        
    return(dat)

def load_item_lookup():
    # this is a table that aligns scale items with their corresponding questions
    htqs = pd.read_excel(path_to_item_lookup, skiprows=2,
                                names=['id', 'scale', 'item', '_0', '_1', '_2', '_3']).drop(['_0', '_1', '_2', '_3'], axis=1)
    # cmqs is a dataframe with items and responses
    # htcm is the same dataframe, but only displaying HiTOP items
    cmqs = pd.read_csv(path_to_cogmood_questions)
    cmqs = cmqs.rename({'Unnamed: 0': 'id'}, axis=1)
    htcm = cmqs.query("measure == 'HiTOP'")
    # this is a lookup table for subscales, items (sentence questions), and hitop ids
    item_lookup = htcm.loc[:, ['id','subscale', 'item']].merge(htqs.loc[:, ['id','item']], how='inner', on='item', suffixes=['_cm', '_ht'])
    item_lookup['htid'] = 'hitop'+ item_lookup.id_ht.astype(str)
    return(item_lookup)
    
def load_valsample():
    # VALIDATION SAMPLE - main dataframe with responses
    dat_validation = pd.read_excel(path_to_valsample)
    '''resp_cols = responses.columns[responses.columns.isin(item_lookup.htid)]
    # scale scores
    scale_scores = []
    for ss, df in item_lookup.groupby('subscale'):
        tmp = responses.loc[:, df.htid].sum(1)
        tmp.name = ss.replace(" ", "_").replace("/", "_").replace("-", "_")
        scale_scores.append(tmp)
    scale_scores = pd.concat(scale_scores, axis=1)
    scale_names = list(scale_scores.columns.values)'''
    #do_checks(dat_validation)    
    # this is the validation data to be used
    hitop_cols_list = make_hitop_list(dat_validation)
    data_validation = dat_validation[hitop_cols_list]
    data_validation = data_validation.assign(whichdata=['validation']*data_validation.shape[0])
    return(data_validation)

def do_codesheet():
    #loads the codesheet file
    # wherever the emane column exists, creates a dict variablename:ename
    code_book = pd.read_csv(path_to_codesheet, sep='\t')
    ename_lut = {vn:en for vn, en in code_book.loc[code_book.ename.notnull(), ['var_name', 'ename']].values}
    for vn, en in code_book.loc[code_book.ename.notnull(), ['var_name', 'ename']].values:
        ename_lut[vn+'_recontact'] = en+'_recontact'
    tmp = code_book.query('ename.notnull()')
    scale_lut = {}
    for ss, df in tmp.loc[tmp.ename.str.contains('hitop') & ~tmp.ename.str.contains('today')].groupby('subscale'):
        scale_name = ss.replace(" ", "_").replace("/", "_").replace("-", "_")
        items = df.ename.values
        scale_lut[scale_name] = items    
     #   scale_name_initial = scale_name+'_initial'
     #   scale_lut[scale_name_initial] = items 
        scale_name_recontact = scale_name+'_recontact'
        items_recontact = []
        for item in items:
            items_recontact.append(item+'_recontact')
        scale_lut[scale_name_recontact] = np.array(items_recontact, dtype=object)
    # rename checks
    ename_lut['FNM_Q8_5'] ='check_moderately'
    ename_lut['FNM_Q22_3'] ='check_notatall'
    ename_lut['FNM_Q42_m_10'] ='todaycheck_1'
    ename_lut['FNM_44_m_28'] ='todaycheck_2'
    ename_lut['FNM_Q8_5_recontact'] ='check_moderately_recontact'
    ename_lut['FNM_Q22_3_recontact'] ='check_notatall_recontact'
    ename_lut['FNM_Q42_m_10_recontact'] ='todaycheck_1_recontact'
    ename_lut['FNM_44_m_28_recontact'] ='todaycheck_2_recontact'
    return ename_lut, scale_lut

def clean_mood_diagnosis(dat):
    # clean mood diagnosis
    dat['mood_dx'] = ''
    dat['n_mood_dx'] = (dat.loc[:, ['FNM_Q25_1', 'FNM_Q25_2', 'FNM_Q25_3', 'FNM_Q25_4', 'FNM_Q25_5', 'FNM_Q25_6']]==1).sum(1)
    dat.loc[dat.FNM_Q25_955 == 1, 'mood_dx'] = 'other'
    dat.loc[dat.FNM_Q25_1 == 1, 'mood_dx'] = 'mdd'
    dat.loc[dat.FNM_Q25_2 == 1, 'mood_dx'] = 'persistent'
    dat.loc[dat.FNM_Q25_3 == 1, 'mood_dx'] = 'premenstrual'
    dat.loc[dat.FNM_Q25_4 == 1, 'mood_dx'] = 'bipolarI'
    dat.loc[dat.FNM_Q25_5 == 1, 'mood_dx'] = 'bipolarII'
    dat.loc[dat.FNM_Q25_6 == 1, 'mood_dx'] = 'cyclothymic'
    dat.loc[dat.n_mood_dx > 1, 'mood_dx'] = 'multiple'
    # clean other mood columns
    dat.loc[dat.mood_years == 999, 'mood_years'] = np.nan
    dat['mood_bothered']=False
    dat.loc[dat.mood_bothered_orig == 1, 'mood_bothered'] = True
    return(dat)

def clean_mood_diagnosis_recontact(dat):
    # clean mood diagnosis - recontact
    dat['mood_dx_recontact'] = ''
    dat['n_mood_dx_recontact'] = (dat.loc[:, ['FNM_Q25_1_recontact', 'FNM_Q25_2_recontact', 'FNM_Q25_3_recontact', 'FNM_Q25_4_recontact', 'FNM_Q25_5_recontact', 'FNM_Q25_6_recontact']]==1).sum(1)
    dat.loc[dat.FNM_Q25_955_recontact == 1, 'mood_dx_recontact'] = 'other'
    dat.loc[dat.FNM_Q25_1_recontact == 1, 'mood_dx_recontact'] = 'mdd'
    dat.loc[dat.FNM_Q25_2_recontact == 1, 'mood_dx_recontact'] = 'persistent'
    dat.loc[dat.FNM_Q25_3_recontact == 1, 'mood_dx_recontact'] = 'premenstrual'
    dat.loc[dat.FNM_Q25_4_recontact == 1, 'mood_dx_recontact'] = 'bipolarI'
    dat.loc[dat.FNM_Q25_5_recontact == 1, 'mood_dx_recontact'] = 'bipolarII'
    dat.loc[dat.FNM_Q25_6_recontact == 1, 'mood_dx_recontact'] = 'cyclothymic'
    dat.loc[dat.n_mood_dx_recontact > 1, 'mood_dx_recontact'] = 'multiple'
    # clean other mood columns - recontact
    # clean other mood columns
    dat.loc[dat.mood_years_recontact == 999, 'mood_years_recontact'] = np.nan
    dat['mood_bothered_recontact']=False
    dat.loc[dat.mood_bothered_recontact_orig == 1, 'mood_bothered_recontact'] = True
    return(dat)

def clean_anxiety_diagnosis(dat):
    # clean anxiety diagnosis
    dat['anxiety_dx'] = ''
    dat['n_anxiety_dx'] = (dat.loc[:, ['FNM_Q30_m_1',
                                       'FNM_Q30_m_2',
                                       'FNM_Q30_m_3', 
                                       'FNM_Q30_m_4', 
                                       'FNM_Q30_m_5',
                                       'FNM_Q30_m_6',
                                       'FNM_Q30_m_7',
                                       'FNM_Q30_m_8',]]==1).sum(1)
    dat.loc[dat.FNM_Q30_m_955 == 1, 'anxiety_dx'] = 'other'
    dat.loc[dat.FNM_Q30_m_1 == 1, 'anxiety_dx'] = 'gad'
    dat.loc[dat.FNM_Q30_m_2 == 1, 'anxiety_dx'] = 'separation'
    dat.loc[dat.FNM_Q30_m_3 == 1, 'anxiety_dx'] = 'agoraphobia'
    dat.loc[dat.FNM_Q30_m_4 == 1, 'anxiety_dx'] = 'phobia'
    dat.loc[dat.FNM_Q30_m_5 == 1, 'anxiety_dx'] = 'social'
    dat.loc[dat.FNM_Q30_m_6 == 1, 'anxiety_dx'] = 'panic_disorder'
    dat.loc[dat.FNM_Q30_m_7 == 1, 'anxiety_dx'] = 'panic_attack'
    dat.loc[dat.FNM_Q30_m_8 == 1, 'anxiety_dx'] = 'mutism'
    dat.loc[dat.n_anxiety_dx > 1, 'anxiety_dx'] = 'multiple'
    # clean other anxiety columns
    dat.loc[dat.anxiety_years == 999, 'anxiety_years'] = np.nan
    dat['anxiety_bothered']=False
    dat.loc[dat.anxiety_bothered_orig == 1, 'anxiety_bothered'] = True
    return(dat)

def clean_anxiety_diagnosis_recontact(dat):
    # clean anxiety diagnosis - recontact
    dat['anxiety_dx_recontact'] = ''
    dat['n_anxiety_dx_recontact'] = (dat.loc[:, ['FNM_Q30_m_1_recontact',
                                       'FNM_Q30_m_2_recontact',
                                       'FNM_Q30_m_3_recontact', 
                                       'FNM_Q30_m_4_recontact', 
                                       'FNM_Q30_m_5_recontact',
                                       'FNM_Q30_m_6_recontact',
                                       'FNM_Q30_m_7_recontact',
                                       'FNM_Q30_m_8_recontact',]]==1).sum(1)
    dat.loc[dat.FNM_Q30_m_955_recontact == 1, 'anxiety_dx_recontact'] = 'other'
    dat.loc[dat.FNM_Q30_m_1_recontact == 1, 'anxiety_dx_recontact'] = 'gad'
    dat.loc[dat.FNM_Q30_m_2_recontact == 1, 'anxiety_dx_recontact'] = 'separation'
    dat.loc[dat.FNM_Q30_m_3_recontact == 1, 'anxiety_dx_recontact'] = 'agoraphobia'
    dat.loc[dat.FNM_Q30_m_4_recontact == 1, 'anxiety_dx_recontact'] = 'phobia'
    dat.loc[dat.FNM_Q30_m_5_recontact == 1, 'anxiety_dx_recontact'] = 'social'
    dat.loc[dat.FNM_Q30_m_6_recontact == 1, 'anxiety_dx_recontact'] = 'panic_disorder'
    dat.loc[dat.FNM_Q30_m_7_recontact == 1, 'anxiety_dx_recontact'] = 'panic_attack'
    dat.loc[dat.FNM_Q30_m_8_recontact == 1, 'anxiety_dx_recontact'] = 'mutism'
    
    dat.loc[dat.n_anxiety_dx_recontact > 1, 'anxiety_dx_recontact'] = 'multiple'
    # clean other anxiety columns - recontact
    dat.loc[dat.anxiety_years_recontact == 999, 'anxiety_years_recontact'] = np.nan
    dat['anxiety_bothered_recontact']=False
    dat.loc[dat.anxiety_bothered_recontact_orig == 1, 'anxiety_bothered_recontact'] = True
    return(dat)

def clean_attnt_dx(dat):
    # clean attention diagnosis
    dat['attention_dx'] = ''
    dat['n_attention_dx'] = (dat.loc[:, ['FNM_Q35_m_1',
                                       'FNM_Q35_m_2',
                                      ]]==1).sum(1)
    dat.loc[dat.FNM_Q35_m_3 == 1, 'attention_dx'] = 'other'
    dat.loc[dat.FNM_Q35_m_1 == 1, 'attention_dx'] = 'adhd'
    dat.loc[dat.FNM_Q35_m_2 == 1, 'attention_dx'] = 'adhd'
    
    # clean other attention columns
    dat.loc[dat.attention_years == 999, 'attention_years'] = np.nan
    dat['attention_bothered']=False
    dat.loc[dat.attention_bothered_orig == 1, 'attention_bothered'] = True
    return(dat)

def clean_attnt_dx_recontact(dat):
    # clean attention diagnosis - recontact
    dat['attention_dx_recontact'] = ''
    dat['n_attention_dx_recontact'] = (dat.loc[:, ['FNM_Q35_m_1_recontact',
                                       'FNM_Q35_m_2_recontact',
                                      ]]==1).sum(1)
    dat.loc[dat.FNM_Q35_m_3_recontact == 1, 'attention_dx_recontact'] = 'other'
    dat.loc[dat.FNM_Q35_m_1_recontact == 1, 'attention_dx_recontact'] = 'adhd'
    dat.loc[dat.FNM_Q35_m_2_recontact == 1, 'attention_dx_recontact'] = 'adhd'
    
    # clean other attention columns - recontact
    dat.loc[dat.attention_years_recontact == 999, 'attention_years_recontact'] = np.nan
    dat['attention_bothered_recontact']=False
    dat.loc[dat.attention_bothered_recontact_orig == 1, 'attention_bothered_recontact'] = True
    return(dat)

def define_attnt_checks(dat):
    # deal with attention checks 
    dat['passed_checks'] = True
    dat['passed_grid'] = True
    dat['passed_list'] = True
    dat.loc[dat.check_moderately != 3, 'passed_checks'] = False
    dat.loc[dat.check_notatall != 1, 'passed_checks'] = False
    dat.loc[dat.check_moderately != 3, 'passed_grid'] = False
    dat.loc[dat.check_notatall != 1, 'passed_grid'] = False
    dat.loc[dat.todaycheck_1 != 1, 'passed_checks'] = False
    dat.loc[dat.todaycheck_2 != 1, 'passed_checks'] = False
    dat.loc[dat.todaycheck_1 != 1, 'passed_list'] = False
    dat.loc[dat.todaycheck_2 != 1, 'passed_list'] = False 
    # deal with attention checks - recontact
    dat['passed_checks_recontact'] = True
    dat['passed_grid_recontact'] = True
    dat['passed_list_recontact'] = True
    dat.loc[dat.check_moderately_recontact != 3, 'passed_checks_recontact'] = False
    dat.loc[dat.check_notatall_recontact != 1, 'passed_checks_recontact'] = False
    dat.loc[dat.check_moderately_recontact != 3, 'passed_grid_recontact'] = False
    dat.loc[dat.check_notatall_recontact != 1, 'passed_grid_recontact'] = False
    dat.loc[dat.todaycheck_1_recontact != 1, 'passed_checks_recontact'] = False
    dat.loc[dat.todaycheck_2_recontact != 1, 'passed_checks_recontact'] = False
    dat.loc[dat.todaycheck_1_recontact != 1, 'passed_list_recontact'] = False
    dat.loc[dat.todaycheck_2_recontact != 1, 'passed_list_recontact'] = False
    # how many passed checks?
    print('\nThis is how many ppl passed attention checks:')
    print('Calculated as 1 - dat.loc[:, [\'passed_checks\', \'passed_grid\', \'passed_list\']].mean()')
    print(1 - dat.loc[:, ['passed_checks', 'passed_grid', 'passed_list']].mean())
    print('Same for recontact:')
    print(1 - dat.loc[:, ['passed_checks_recontact', 'passed_grid_recontact', 'passed_list_recontact']].mean())
    return(dat)
    
def load_data(dataname, doing_checks, doing_remove_checks):
    print(doing_remove_checks)
    assert(dataname in ['genpop','enriched'])
    
    #codesheet file
    ename_lut, scale_lut = do_codesheet()
    
    # done working with the codesheet file, now opening the actual data
    if dataname == 'genpop':
        datapath = path_to_genpop
    elif dataname == 'enriched':
        datapath = path_to_enriched
    dat = pd.read_csv(datapath, dtype={'caseid':str}, engine='python')
    if dataname == 'genpop':
        # ONLY GENPOP drop the .0 that pandas appends for some reason - only for genpop
        dat['caseid'] = dat.caseid.str[:-2]
    
    #renaming columns
    dat = dat.rename(ename_lut, axis=1)
    dat = dat.rename(columns={
        'mood_bothered': 'mood_bothered_orig',
        'mood_bothered_recontact': 'mood_bothered_recontact_orig',
        'anxiety_bothered': 'anxiety_bothered_orig',
        'anxiety_bothered_recontact': 'anxiety_bothered_recontact_orig',
        'attention_bothered': 'attention_bothered_orig',
        'attention_bothered_recontact': 'attention_bothered_recontact_orig'}) 
    
    # clean diagnoses
    dat = clean_mood_diagnosis(dat)
    dat = clean_mood_diagnosis_recontact(dat)
    dat = clean_anxiety_diagnosis(dat)
    dat = clean_anxiety_diagnosis_recontact(dat)
    dat = clean_attnt_dx(dat)
    dat = clean_attnt_dx_recontact(dat)
    
    if doing_checks:
        dat = do_checks(dat = dat, remove_checks = doing_remove_checks) 

    minus_1_cols = []
    m1_stems = ['inattention', 'hyperactivity', 'impulsivity', 'sct', 'gad', 'phq', 'hitop',
           'inattention_recontact', 'hyperactivity_recontact', 'impulsivity_recontact', 'sct_recontact', 'gad_recontact', 'phq_recontact', 'hitop_recontact']
    for ms in m1_stems:
        #print(ms)
        if "recontact" not in ms:
            cols = list(dat.columns[dat.columns.str.contains(ms) & ~dat.columns.str.contains('today') & ~dat.columns.str.contains('sum') & ~dat.columns.str.contains('recontact')].values)
        else:
            cols = list(dat.columns[dat.columns.str.contains(ms[:-10]) & ~dat.columns.str.contains('today') & ~dat.columns.str.contains('sum') & dat.columns.str.contains('recontact')].values)
        #print(cols)
        minus_1_cols.extend(cols)

    # why are we doing this
    # subtract 1 from responses
    dat.loc[:, minus_1_cols] -= 1

    # summing up the values
    sum_cols = []
    for ms in m1_stems:
        if 'hitop' not in ms:
            if "recontact" not in ms:
                cols = list(dat.columns[dat.columns.str.contains(ms) & ~dat.columns.str.contains('today') & ~dat.columns.str.contains('sum') & ~dat.columns.str.contains('recontact')].values)
                dat[f'{ms}_sum'] = dat.loc[:, cols].sum(1)
                sum_cols.append(ms + '_sum')
            else:
                cols = list(dat.columns[dat.columns.str.contains(ms[:-10]) & ~dat.columns.str.contains('today') & ~dat.columns.str.contains('sum') & dat.columns.str.contains('recontact')].values)
                dat[f'{ms[:-10]}_sum_recontact'] = dat.loc[:, cols].sum(1)
                sum_cols.append(ms[:-10] + '_sum_recontact')    
    hitop_sums = []
    for scale_name, items in scale_lut.items():
        dat[scale_name] = dat.loc[:, items].sum(1) # adding a dat[scale_name] with a sum of all values ("items)"
        hitop_sums.append(scale_name)   

    sum = 0
    for scale_name, items in scale_lut.items():
        if "well_being" not in scale_name:
            sum += len(items)

    # !!!!!!!!!! double-check this
    dat['hitop_sum'] = dat.loc[:, hitop_sums[::2][:-1]].sum(1)  # [:-1] because we don't include the well-being scale
    dat['hitop_sum_recontact'] = dat.loc[:, hitop_sums[1::2][:-1]].sum(1)
    dat['baars_sum'] = dat.inattention_sum + dat.hyperactivity_sum + dat.impulsivity_sum
    dat['baars_sum_recontact'] = dat.inattention_sum_recontact + dat.hyperactivity_sum_recontact + dat.impulsivity_sum_recontact
    dat['moodanxiety_bothered'] = dat.mood_bothered | dat.anxiety_bothered
    dat['moodanxiety_bothered_recontact'] = dat.mood_bothered_recontact | dat.anxiety_bothered_recontact

    my_columns = []
    for item in ['hitop_sum', 'baars_sum', 'phq_sum', 'gad_sum', # all sums
                 'mood_bothered','anxiety_bothered', 'attention_bothered', 'moodanxiety_bothered', # bothered
                 'inattention_sum', 'hyperactivity_sum', 'impulsivity_sum', 'sct_sum']: # each subscale of baars
        my_columns.append(item)
        my_columns.append(item+'_recontact')
    my_columns.extend(hitop_sums) #each subscale of hitop

        # rename columns with phq and gad sums for cnsistency in naming
    dat = dat.rename(columns={"gad_recontact_sum": "gad_sum_recontact", "phq_recontact_sum": "phq_sum_recontact"})

    # rename baars subscales
    dat = dat.rename(columns={"inattention_sum": "baars_inattention_sum", 
                          "inattention_sum_recontact": "baars_inattention_sum_recontact",
                          "hyperactivity_sum": "baars_hyperactivity_sum", 
                          "hyperactivity_sum_recontact": "baars_hyperactivity_sum_recontact",
                          "impulsivity_sum": "baars_impulsivity_sum", 
                          "impulsivity_sum_recontact": "baars_impulsivity_sum_recontact",
                          "sct_sum": "baars_sct_sum",
                          "sct_sum_recontact": "baars_sct_sum_recontact"})

    # rename hitops subscales
    rename_dict = {}
    for hitop_item in hitop_sums:
        rename_dict[hitop_item] = 'hitop_' + hitop_item
    dat = dat.rename(columns=rename_dict)
    
    hitop_cols_list = make_hitop_list(dat)
    dat = dat.assign(whichdata=[dataname]*dat.shape[0])
    data = dat[hitop_cols_list]
    data = data.assign(whichdata=[dataname]*data.shape[0])
    recontact_cols_list = make_recontact_list(data)
    data_norecontact = data.drop(columns=recontact_cols_list)
    return dat, data, data_norecontact   

def prep_data_recontactanalysis(dataframe_withrecontact):
    df = dataframe_withrecontact
    df_helper = df.copy(deep=True)
    df_rows = df.shape[0]
    df = df.assign(whichvisit=['initialvisit']*df_rows)
    df_helper = df_helper.assign(whichvisit=['recontactvisit']*df_rows)
    # in df, drop all "recontact" columns
    # in df_helper, drop all initial visit columns, then rename the recontact columns
    cols_recontact = []
    cols_original = []
    for c in df.columns:
        if "recontact" in c:
            cols_recontact.append(c)
            cols_original.append(c[:-10])  
    df = df.drop(columns=cols_recontact)
    df_helper = df_helper.drop(columns=cols_original)
    cols_dict = {}
    for cname in cols_recontact:
        cols_dict[cname] = cname[:-10]
    # rename cols in df_helper
    df_helper.rename(columns=cols_dict, inplace=True)    
    mydata_withrecontact = pd.concat([df, df_helper])
    return(mydata_withrecontact)

## CFA helper functions

In [11]:
def print_summary(obj):
    return rprint(summary(obj))

def print_short_summary(invariance_output):
    ro.r("myoutput <- capture.output(summary(invariance_output))") 
    ro.r("stringid <- grep(\"chisq\", myoutput)")
    ro.r("print(myoutput[stringid-1])")
    ro.r("print(myoutput[stringid])")
    return (0)

def print_problematic_items(invariance_output):
    ro.r("myoutput <- capture.output(summary(invariance_output))") 
    print('Problematic items:')
    ro.r("stringidsig <- grep(\"may differ between Groups\", myoutput)")
    ro.r("print(myoutput[stringidsig])")   
    return (0)
    
def extract_p(invariance_output):
    ro.globalenv['invariance_output'] = invariance_output
    ro.r("myoutput <- capture.output(summary(invariance_output))") 
    ro.r("stringid <- grep(\"chisq\", myoutput)")
    ro.r('myrline <- myoutput[stringid]')
    mypline = ro.r('myrline')[0]
    my_p = mypline.split()[-1]
    return(my_p)

def check_secondary_criteria(fit_config):
    Criteria_passed = False
    ro.r("myoutputconfig <- capture.output(summary(fit_config, fit.measures=TRUE))")
    ro.r("stringid_cfi <- grep(\"Robust.*CFI\", myoutputconfig)")
    ro.r("cfi_line <- myoutputconfig[stringid_cfi]")
    cfiline = ro.r('cfi_line')[0]    
    my_cfi = cfiline.split()[-1] 
    my_cfi = float(my_cfi)
    ro.r("stringid_tli <- grep(\"Robust.*TLI\", myoutputconfig)")
    ro.r("tli_line <- myoutputconfig[stringid_tli]")
    tliline = ro.r('tli_line')[0]    
    my_tli = tliline.split()[-1] 
    my_tli = float(my_tli)
    ro.r("stringid_rmsea <- grep(\"Robust.*RMSEA\", myoutputconfig)")
    ro.r("rmsea_line <- myoutputconfig[stringid_rmsea]")
    myrmsealine = ro.r('rmsea_line')[0]
    my_rmsea = myrmsealine.split('\n')[0].split()[-1]
    my_rmsea = float(my_rmsea)   
    if (my_cfi > 0.95) and (my_tli > 0.95) and (my_rmsea < 0.06):
        Criteria_passed = True
    return (Criteria_passed, my_cfi, my_tli, my_rmsea)   

def check_hitop_ids(items_to_check, my_item_lookup):
    # checks what item ids mean what
    for i in items_to_check:
        a = repr(my_item_lookup.loc[my_item_lookup['htid'] == 'hitop'+i]['htid']).split(' ', 1)[1]
        aa = str(a).split('\n')[0]
        b = repr(my_item_lookup.loc[my_item_lookup['htid'] == 'hitop'+i]['item']).split(' ', 1)[1]
        bb = str(b).split('\n')[0]
        print(aa+bb)
    print('\n')

def cfa_helper_func(scalename, list_of_items, do_metric, do_scalar, do_strict, mydata_python, mydata_temp_path):
    # Helper CFA funct
    # Inputs:
    # --> scalename - string of scale name: 'appetite_loss'
    # --> list_of_items - list of items to test, not necessarily the full list of items for the scale: ['hitop280', 'hitop283', 'hitop109']
    # --> do_metric, do_scalar, do_strict: True/False
    # --> mydata_python - python df with data (this function will feed it to R)
    # --> mydata_temp_path - path to do an intermediate step of saving from python, then reading into R

    # SETTING THE SEED HERE, JUST TO BE SURE IT IS SET TO THE SAME THING EVERY TIME I RUN THIS HELPER FUNCTION
    random.seed(12345)
    ro.r('RNGkind(kind = "L\'Ecuyer-CMRG")')
    ro.r('set.seed(12345)')

    rprint = ro.r('print')
    summary = ro.r('summary')

    # make a R-readable string out of scalename and desired list of items
    # (this will sometimes match the full set - and it's okay - but sometimes won't, when we iterate through all options looking for inv subsets)
    myrstring = scalename + "=~"
    for x in list_of_items: # iterate through desired items and add them to my formula
        myrstring += x + ' + '
    myrstring = myrstring[:-3] # drop the last " + "
    #print(f'Testing formula: {myrstring}')      
    ro.globalenv['testformula_r'] = myrstring # send it to the R world

    # transfer data from python into R
    # I save the python df as csv and then load it to R (there must be a more elegant way to do this, but this one works...)
    mydata_python.to_csv(mydata_temp_path)
    r_data_command = f'rdata <- read.csv(\'{mydata_temp_path}\', header=TRUE)'
    ro.r(r_data_command)

    # telling R which column to test
    group = 'whichdata'
    ro.globalenv['group'] = group

    flag_passed_metric = False # setting flag for metric because this level is the most important one --> we return this
    
    # Always do CONFIGURAL:
    flag_passed_config = False # flag for configural
    fit_config = ro.r('cfa(testformula_r, data = rdata, group = group, estimator = "WLSMV")')
    ro.globalenv['fit_config'] = fit_config        
    out_config = semtools.permuteMeasEq(nPermute=num_iter,
                                        con=fit_config, # In the case of testing configural invariance when modelType = "mgcfa", con is the configural model (implicitly, the unconstrained model is the saturated model, so use the defaults uncon = NULL and param = NULL).
                                        parallelType="multicore", ncpus=cpus_to_use)
    config_p = extract_p(out_config)
    if float(config_p) >= 0.05:
        print('CONFIG INVARIANT chisq p = ' + str(config_p))
        flag_passed_config = True
    else:
        (flag_passed_config, my_cfi, my_tli, my_rmsea) = check_secondary_criteria(fit_config)
        if flag_passed_config:
            print('CONFIG chisq p = ' + str(config_p))
            print('PASSED SECONDARY CRITERIA WITH CFI = ' + str(my_cfi) + ' TLI = ' + str(my_tli) + ' RMSEA = ' + str(my_rmsea))

    if flag_passed_config: # only do metric if configural is passed
        if do_metric:
            # ====== METRIC =====
            fit_metric = ro.r('cfa(testformula_r, data = rdata, group = group, estimator = "WLSMV", group.equal="loadings")')
            ro.globalenv['fit_metric'] = fit_metric
            out_metric = semtools.permuteMeasEq(nPermute=num_iter, 
                                                        uncon=fit_config, 
                                                        con=fit_metric, 
                                                        param="loadings",
                                                        parallelType="multicore", ncpus=cpus_to_use)
            metric_p = extract_p(out_metric)
            if float(metric_p) >= 0.05:
                print('METRIC INVARIANT chisq p = ' + str(metric_p))
                flag_passed_metric = True

                if do_scalar: # only do scalar if metric is passed
                    # ====== SCALAR =====
                    fit_scalar = ro.r('cfa(testformula_r, data = rdata, group = group, estimator = "WLSMV", group.equal=c("loadings", "intercepts"))')
                    ro.globalenv['fit_scalar'] = fit_scalar
                    out_scalar = semtools.permuteMeasEq(nPermute=num_iter, 
                                                            uncon=fit_metric, 
                                                            con=fit_scalar, 
                                                            param=ro.StrVector(["loadings","intercepts"]),
                                                            parallelType="multicore", 
                                                            ncpus=cpus_to_use)
                    scalar_p = extract_p(out_scalar)
                    if float(scalar_p) >= 0.05:
                        print('SCALAR INVARIANT chisq p = ' + str(scalar_p)) 
                        
                        if do_strict: # only do strict if scalar is passed
                            # ====== STRICT =====
                            ro.globalenv['out_scalar'] = out_scalar
                            fit_strict = ro.r('cfa(testformula_r, data = rdata, group = group, estimator = "WLSMV", group.equal=c("loadings", "intercepts", "residuals"))')
                            ro.globalenv['fit_strict'] = fit_strict
                            out_strict = semtools.permuteMeasEq(nPermute=num_iter, 
                                                                        uncon=fit_scalar, 
                                                                        con=fit_strict, 
                                                                        param=ro.StrVector(["loadings","intercepts", "residuals"]),
                                                                        parallelType="multicore", 
                                                                        ncpus=cpus_to_use)
                            strict_p = extract_p(out_strict)
                            if float(strict_p) >= 0.05:
                                print('STRICT INVARIANT chisq p = ' + str(strict_p))
                            else:
                                # significant:
                                print('STRICT INVARIANT NOT PASSED, chisq p = ' + str(strict_p))
                        else: # not do_strict
                            print('STRICT N/A')
                            strict_p = 'NA'
                    else: # scalar not passed
                        print('SCALAR INVARIANT NOT PASSED, chisq p = ' + str(scalar_p))
                        print('STRICT N/A')
                        strict_p = 'NA' 
                else: # not do_scalar
                    print('SCALAR N/A')
                    scalar_p = 'NA' 
                    print('STRICT N/A')
                    strict_p = 'NA'                     
            else: # metric not passed
                print('METRIC INVARIANT NOT PASSED, chisq p = ' + str(metric_p)) 
                print('SCALAR N/A')
                print('STRICT N/A')                    
                scalar_p = 'NA'
                strict_p = 'NA'       
        else: # not do_metric
            print('METRIC N/A')
            print('SCALAR N/A')
            print('STRICT N/A')
            metric_p = 'NA'
            scalar_p = 'NA'
            strict_p = 'NA'            
    else: # config not passed
        print('CONFIG INVARIANT NOT PASSED, chisq p = ' + str(config_p))
        print('METRIC N/A')
        print('SCALAR N/A')
        print('STRICT N/A')
        metric_p = 'NA'
        scalar_p = 'NA'
        strict_p = 'NA'
    
    return(flag_passed_metric, config_p, metric_p, scalar_p, strict_p)

## CFA wrapper functions

In [12]:
def do_three_way_cfa_ablations(whichscale, whichcfa, howmanyitems):
    
    # checks all combinations of X items for Y scale,
    # reports if a 3-way invariant combination was found
    
    print(f'FOR SCALE {whichscale.upper()}:')    
    print(f'RUN ALL COMBINATIONS OF {howmanyitems} ITEMS and checks if a combination is 3-way invariant.')
    
    flag_found_inv_in_all_three = False
    successful_combinations = {}

    # these are the original scales
    mdl_strs_new = {'anhedonic_depression': 'anhedonic_depression =~hitop39 + hitop77 + hitop84 + hitop92 + hitop93 + hitop123 + hitop157 + hitop182 + hitop230 + hitop246',
         'anxious_worry': 'anxious_worry =~hitop20 + hitop34 + hitop89 + hitop203 + hitop248 + hitop265',
         'appetite_gain': 'appetite_gain =~hitop120 + hitop141 + hitop243 + hitop275',
         'appetite_loss': 'appetite_loss =~hitop280 + hitop283 + hitop109',
         'cognitive_problems': 'cognitive_problems =~hitop67 + hitop189 + hitop142',
         'hyposomnia': 'hyposomnia =~hitop99 + hitop181 + hitop5 + hitop66 + hitop231',
         'insomnia': 'insomnia =~hitop160 + hitop254 + hitop261 + hitop268',
         'panic': 'panic =~hitop15 + hitop104 + hitop126 + hitop211 + hitop215 + hitop257',
         'separation_insecurity': 'separation_insecurity =~hitop40 + hitop50 + hitop69 + hitop81 + hitop113 + hitop136 + hitop151 + hitop197',
         'shame_guilt': 'shame_guilt =~hitop72 + hitop140 + hitop143 + hitop220',
         'situational_phobia': 'situational_phobia =~hitop16 + hitop165 + hitop225 + hitop247 + hitop278',
         'social_anxiety': 'social_anxiety =~hitop1 + hitop17 + hitop114 + hitop117 + hitop124 + hitop129 + hitop204 + hitop222 + hitop236 + hitop258',
         'well_being': 'well_being =~hitop9 + hitop23 + hitop54 + hitop106 + hitop149 + hitop200 + hitop244 + hitop245 + hitop250 + hitop281'}
    
    for cln_ss, mdl in mdl_strs_new.items(): 
        if cln_ss == whichscale:  # take the scale we are interested in 
            if whichcfa == 'metric':
                doing_metric = True
                doing_scalar = False
                doing_strict = False
            elif whichcfa == 'scalar':
                doing_metric = True
                doing_scalar = True
                doing_strict = False   
            elif whichcfa == 'strict':
                doing_metric = True
                doing_scalar = True
                doing_strict = True                  
            print("\n")
            print(f"Running {cln_ss.upper()}")
            print(f"Items: {mdl}")
            
            # loop to do ablations
            temp_items = mdl_strs_new[cln_ss]
            temp_items_items = temp_items.split("=~",1)[1]
            temp_items_items_items = temp_items_items.split(" + ")
            list_of_items = temp_items_items_items

            count_success = 0
            count_comb = 1

            for com in combinations(list_of_items, howmanyitems):

                # number of possible combinations of x items of of n possible items
                num_combinations = math.comb(len(list_of_items), howmanyitems)
                print(f'\n+++ TESTING {count_comb}th COMBINATION out of {num_combinations} possible combinations of {howmanyitems} items +++')
                print(f'Items to test: {com}')

                # set flags for metric invariance genpop and enriched to FALSE, for this combination of items
                flag_metric_val_gp = False
                flag_metric_val_en = False
                flag_metric_gp_en = False 

                # +++ VALIDATION VS GENPOP +++
                print('\n -----> VALID VS GENPOP <----- ')
                flag_metric_val_gp, pconfig_val_gp, pmetric_val_gp, pscalar_val_gp, pstrict_val_gp = cfa_helper_func(\
                    scalename = cln_ss,\
                    list_of_items = com,\
                    do_metric = doing_metric, \
                    do_scalar = doing_scalar, \
                    do_strict = doing_strict, \
                    mydata_python = mydata_val_genpop_norecontact, \
                    mydata_temp_path = path_to_helpfile)
            
                # +++ VALIDATION VS ENRICHED +++ 
                print('\n -----> VALID VS ENRICHED <----- ')
                flag_metric_val_en, pconfig_val_en, pmetric_val_en, pscalar_val_en, pstrict_val_en = cfa_helper_func(\
                    scalename = cln_ss,\
                    list_of_items = com,\
                    do_metric = doing_metric, \
                    do_scalar = doing_scalar, \
                    do_strict = doing_strict, \
                    mydata_python = mydata_val_enriched_norecontact, \
                    mydata_temp_path = path_to_helpfile)

                # +++ GENPOP VS ENRICHED +++ 
                print('\n -----> GENPOP VS ENRICHED <----- ')
                flag_metric_gp_en, pconfig_gp_en, pmetric_gp_en, pscalar_gp_en, pstrict_gp_en = cfa_helper_func(\
                    scalename = cln_ss,\
                    list_of_items = com,\
                    do_metric = doing_metric, \
                    do_scalar = doing_scalar, \
                    do_strict = doing_strict, \
                    mydata_python = data_genpop_enriched_norecontact, \
                    mydata_temp_path = path_to_helpfile)

                if all([flag_metric_val_gp, flag_metric_val_en, flag_metric_gp_en]):
                    print(f"Combination {count_comb} passes 3-way invariance!")
                    flag_found_inv_in_all_three = True
                    count_success += 1
                    successful_combinations[com]={'val_gp':[pconfig_val_gp, pmetric_val_gp, pscalar_val_gp, pstrict_val_gp],\
                                                  'val_en':[pconfig_val_en, pmetric_val_en, pscalar_val_en, pstrict_val_en],\
                                                  'gp_en':[pconfig_gp_en, pmetric_gp_en, pscalar_gp_en, pstrict_gp_en]}
                count_comb+=1
                        
            print("\nCFA DONE")
            if flag_found_inv_in_all_three:
                print(f'\n\nFound {count_success} combination(s) of {howmanyitems} that is 3-way invariant.')
                print(successful_combinations)
            
            else:
                print(f'\nCould not find a combination of {howmanyitems} for scale {whichscale} that is 3-way invariant =(')
                print(f'Val–GP: {flag_metric_val_gp}')
                print(f'Val–EN: {flag_metric_val_en}')
                print(f'GP–EN:  {flag_metric_gp_en}\n')
                
    return(successful_combinations)

In [13]:
def run_specific_cfa(whichscale, item_list, whichcfa):
    # checks 3-way CFA for a specific formula
    print(f'\n\nFOR SCALE {whichscale.upper()}:')    
    print(f'\nRUN ALL 3-way CFA for items: {item_list}.')
    
    # down to which scale to test
    if whichcfa == 'metric':
        doing_metric = True
        doing_scalar = False
        doing_strict = False
    elif whichcfa == 'scalar':
        doing_metric = True
        doing_scalar = True
        doing_strict = False   
    elif whichcfa == 'strict':
        doing_metric = True
        doing_scalar = True
        doing_strict = True  

    # set flags for metric invariance to FALSE, for this combination of items
    flag_metric_val_gp = False
    flag_metric_val_en = False
    flag_metric_gp_en = False 

    # +++ VALIDATION VS GENPOP +++
    print('\n -----> VALID VS GENPOP <----- ')
    flag_metric_val_gp, pconfig_val_gp, pmetric_val_gp, pscalar_val_gp, pstrict_val_gp = cfa_helper_func(\
                    scalename = whichscale,\
                    list_of_items = item_list,\
                    do_metric = doing_metric, \
                    do_scalar = doing_scalar, \
                    do_strict = doing_strict, \
                    mydata_python = mydata_val_genpop_norecontact, \
                    mydata_temp_path = path_to_helpfile)
            
    # +++ VALIDATION VS ENRICHED +++ 
    print('\n -----> VALID VS ENRICHED <----- ')
    flag_metric_val_en, pconfig_val_en, pmetric_val_en, pscalar_val_en, pstrict_val_en = cfa_helper_func(\
                    scalename = whichscale,\
                    list_of_items = item_list,\
                    do_metric = doing_metric, \
                    do_scalar = doing_scalar, \
                    do_strict = doing_strict, \
                    mydata_python = mydata_val_enriched_norecontact, \
                    mydata_temp_path = path_to_helpfile)

    # +++ GENPOP VS ENRICHED +++ 
    print('\n -----> GENPOP VS ENRICHED <----- ')
    flag_metric_gp_en, pconfig_gp_en, pmetric_gp_en, pscalar_gp_en, pstrict_gp_en = cfa_helper_func(\
                    scalename = whichscale,\
                    list_of_items = item_list,\
                    do_metric = doing_metric, \
                    do_scalar = doing_scalar, \
                    do_strict = doing_strict, \
                    mydata_python = data_genpop_enriched_norecontact, \
                    mydata_temp_path = path_to_helpfile)

    if all([flag_metric_val_gp, flag_metric_val_en, flag_metric_gp_en]):
        flag_found_inv_in_all_three = True
        print("\n!!! PASSES 3-WAY INVARIANCE")
                   
    print("DONE")

    return(0)

# Run Main Code

## Load all data

In [14]:
# Load item_lookup
item_lookup = load_item_lookup()

# Load validation data 
data_val = load_valsample()

# Load genpop data
data_genpop_full, data_genpop, data_genpop_norecontact = load_data('genpop', doing_checks = True, doing_remove_checks='gridinitialvisitonly')

# Load enriched data
data_enriched_full, data_enriched, data_enriched_norecontact = load_data('enriched', doing_checks = True, doing_remove_checks='gridinitialvisitonly')

# Concatinate data
mydata_val_genpop = pd.concat([data_val, data_genpop])
mydata_val_genpop_norecontact = pd.concat([data_val, data_genpop_norecontact])

mydata_val_enriched = pd.concat([data_val, data_enriched])
mydata_val_enriched_norecontact = pd.concat([data_val, data_enriched_norecontact])

data_genpop_enriched_norecontact = pd.concat([data_genpop_norecontact, data_enriched_norecontact])
data_genpop_enriched_full = pd.concat([data_genpop_full, data_enriched_full])

# recontact
data_genpop_recontactanalysis = prep_data_recontactanalysis(data_genpop)
data_enriched_recontactanalysis = prep_data_recontactanalysis(data_enriched)

/Users/zeleninam2/miniconda3/envs/env_semtools_fix/lib/python3.11/site-packages/openpyxl/worksheet/_read_only.py:85: UserWarning: Unknown extension is not supported and will be removed
  for idx, row in parser.parse():

gridinitialvisitonly
checks_initial:
passed_checks    0.462
passed_grid      0.006
passed_list      0.458
dtype: float64
Passed checks: 269 out of 500
checks_recontact:
passed_checks_recontact    0.548
passed_grid_recontact      0.200
passed_list_recontact      0.548
dtype: float64
Passed checks: 226 out of 500
removing checks
(497, 753)
done removing checks
gridinitialvisitonly
checks_initial:
passed_checks    0.293548
passed_grid      0.016129
passed_list      0.290323
dtype: float64
Passed checks: 219 out of 310
checks_recontact:
passed_checks_recontact    0.412903
passed_grid_recontact      0.174194
passed_list_recontact      0.412903
dtype: float64
Passed checks: 182 out of 310
removing checks
(305, 753)
done removing checks

In [58]:
# check nans
for d in [data_val, data_genpop, data_genpop_norecontact,
         data_enriched, data_enriched_norecontact,
         mydata_val_genpop_norecontact,
         mydata_val_enriched_norecontact,
         data_genpop_enriched_norecontact, 
         data_genpop_recontactanalysis, data_enriched_recontactanalysis]:
    print('checking for nans')
    print(d.isnull().values.any())

print('\n')

checking for nans
False
checking for nans
False
checking for nans
False
checking for nans
False
checking for nans
False
checking for nans
True
checking for nans
True
checking for nans
False
checking for nans
False
checking for nans
False

In [43]:
data_genpop_full.shape

(497, 800)

In [44]:
data_genpop.shape

(497, 197)

In [45]:
data_genpop_norecontact.shape

(497, 99)

In [52]:
data_genpop_enriched_full.shape

(802, 800)

In [46]:
data_genpop_enriched_norecontact.head()

,hitop157,hitop81,hitop34,hitop54,hitop243,hitop182,hitop69,hitop89,hitop50,hitop129,hitop265,hitop124,hitop231,hitop93,hitop67,hitop245,hitop281,hitop141,hitop40,hitop204,hitop21,hitop236,hitop280,hitop84,hitop120,hitop77,hitop92,hitop258,hitop39,hitop254,hitop215,hitop95,hitop106,hitop283,hitop16,hitop20,hitop189,hitop1,hitop136,hitop246,hitop248,hitop257,hitop114,hitop117,hitop250,hitop200,hitop160,hitop23,hitop165,hitop244,hitop9,hitop142,hitop230,hitop149,hitop247,hitop99,hitop66,hitop240,hitop222,hitop90,hitop113,hitop278,hitop203,hitop159,hitop123,hitop275,hitop268,hitop225,hitop143,hitop151,hitop181,hitop211,hitop17,hitop126,hitop5,hitop261,hitop220,hitop15,hitop72,hitop140,hitop109,hitop197,hitop104,hitop_anhedonic_depression,hitop_anxious_worry,hitop_appetite_gain,hitop_appetite_loss,hitop_cognitive_problems,hitop_hyposomnia,hitop_indecisiveness,hitop_insomnia,hitop_panic,hitop_separation_insecurity,hitop_shame_guilt,hitop_situational_phobia,hitop_social_anxiety,hitop_well_being,hitop_sum,whichdata
0,1,1,2,3,2,1,1,1,0,1,2,0,0,0,1,3,3,2,0,1,1,1,0,0,0,0,0,0,0,0,0,1,2,0,0,1,3,1,1,0,1,0,0,1,3,2,0,3,0,3,3,1,0,3,0,0,0,1,0,1,0,0,3,1,0,1,0,0,1,1,0,0,0,0,0,1,0,0,0,1,0,0,0,2,11,5,0,6,0,3,1,0,4,2,0,5,28,39,genpop
1,1,0,3,3,0,2,0,2,0,1,3,2,0,1,2,3,3,3,1,3,1,2,1,0,1,3,1,1,0,1,0,1,3,0,2,3,1,2,0,1,1,3,1,1,0,3,2,3,3,3,3,1,1,3,3,1,2,1,3,1,1,1,0,2,0,1,0,1,1,1,1,3,1,2,1,1,1,2,0,1,1,0,2,10,13,5,2,6,5,3,4,12,3,3,10,17,27,93,genpop
2,1,1,2,2,2,1,1,2,1,1,1,3,1,2,1,1,2,1,2,1,1,2,2,2,1,2,1,2,1,1,2,1,3,3,2,1,1,2,0,1,2,1,1,3,2,1,2,1,3,2,1,2,2,1,1,1,1,2,1,2,2,1,2,1,2,2,1,2,1,1,1,2,2,1,1,1,3,2,1,2,1,0,0,15,12,6,6,5,5,4,5,8,8,7,9,18,16,108,genpop
3,1,0,0,2,1,0,0,0,0,0,0,0,0,0,0,2,0,1,0,0,0,0,0,0,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,2,3,3,2,1,0,2,1,0,0,0,0,0,0,0,0,0,0,0,3,0,0,0,0,0,1,0,0,1,0,1,0,0,0,0,0,1,0,3,0,1,0,0,6,1,0,0,4,1,13,17,genpop
4,3,0,1,3,3,3,3,0,1,2,0,1,0,2,2,1,0,3,2,1,1,2,0,1,3,2,1,1,3,3,1,1,0,0,0,1,2,1,0,1,2,3,1,1,0,2,3,1,0,0,1,3,0,0,1,2,0,0,0,1,0,0,2,2,0,3,1,1,1,2,0,1,1,1,0,3,1,1,1,1,0,0,2,16,6,12,0,9,2,3,10,9,8,4,2,11,8,92,genpop

In [47]:
data_genpop_enriched_full.head()

,caseid,weight,sample_type,screener_1ongoing,screener_2impact,screener_3depression,screener_4anxiety,screener_5attention,consent,mood_yn,FNM_Q25_1,FNM_Q25_2,FNM_Q25_3,FNM_Q25_4,FNM_Q25_5,FNM_Q25_6,FNM_Q25_955,FNM_Q25_933,FNM_Q25_open1,mood_years,FNM_Q27_1,FNM_Q27_2,FNM_Q27_3,FNM_Q27_4,FNM_Q27_5,FNM_Q27_6,FNM_Q27_7,FNM_Q27_8,FNM_Q27_9,FNM_Q27_10,FNM_Q27_11,FNM_Q27_12,FNM_Q27_13,FNM_Q27_14,FNM_Q27_15,FNM_Q27_16,FNM_Q27_17,FNM_Q27_18,FNM_Q27_19,FNM_Q27_955,FNM_Q27_933,FNM_Q27_open1,mood_bothered_orig,anxiety_yn,FNM_Q30_m_1,FNM_Q30_m_2,FNM_Q30_m_3,FNM_Q30_m_4,FNM_Q30_m_5,FNM_Q30_m_6,FNM_Q30_m_7,FNM_Q30_m_8,FNM_Q30_m_955,FNM_Q30_m_933,FNM_Q30_open1,anxiety_years,FNM_Q32_1,FNM_Q32_2,FNM_Q32_3,FNM_Q32_4,FNM_Q32_5,FNM_Q32_6,FNM_Q32_7,FNM_Q32_8,FNM_Q32_9,FNM_Q32_10,FNM_Q32_955,FNM_Q32_933,FNM_Q32_open1,anxiety_bothered_orig,attention_yn,FNM_Q35_m_1,FNM_Q35_m_2,FNM_Q35_m_3,FNM_Q35_m_933,FNM_Q35_open1,attention_years,FNM_Q37_m_1,FNM_Q37_m_2,FNM_Q37_m_3,FNM_Q37_m_4,FNM_Q37_m_5,FNM_Q37_m_6,FNM_Q37_m_7,FNM_Q37_m_8,FNM_Q37_m_9,FNM_Q37_m_955,FNM_Q37_m_933,FNM_Q37_open1,attention_bothered_orig,inattention_1,inattention_2,inattention_3,inattention_4,inattention_5,inattention_6,FNM_Q1_attn,inattention_7,inattention_8,inattention_9,hyperactivity_1,hyperactivity_2,hyperactivity_3,hyperactivity_4,hyperactivity_5,impulsivity_1,impulsivity_2,impulsivity_3,impulsivity_4,sct_1,sct_2,sct_3,sct_4,sct_5,sct_6,sct_7,sct_8,sct_9,gad_1,gad_2,gad_3,gad_4,gad_5,gad_6,gad_7,phq_1,phq_2,phq_3,phq_4,phq_5,phq_6,phq_7,phq_8,hitop157,hitop81,hitop34,hitop54,hitop243,hitop182,hitop69,hitop89,hitop50,check_moderately,hitop129,hitop265,hitop124,hitop231,hitop93,hitop67,hitop245,hitop281,hitop141,hitop40,hitop204,hitop21,hitop236,hitop280,hitop84,hitop120,hitop77,hitop92,hitop258,hitop39,hitop254,hitop215,hitop95,hitop106,hitop283,hitop16,hitop20,hitop189,hitop1,hitop136,hitop246,hitop248,hitop257,hitop114,hitop117,hitop250,hitop200,hitop160,hitop23,hitop165,hitop244,hitop9,hitop142,hitop230,hitop149,hitop247,hitop99,hitop66,hitop240,hitop222,hitop90,hitop113,hitop278,hitop203,hitop159,hitop123,hitop275,hitop268,hitop225,hitop143,hitop151,hitop181,hitop211,hitop17,hitop126,hitop5,hitop261,hitop220,check_notatall,hitop15,hitop72,hitop140,hitop109,hitop197,hitop104,todayinattention_1,todayinattention_2,todayinattention_3,todayinattention_4,todayinattention_5,todayinattention_6,todayinattention_7,todayinattention_8,todayinattention_9,todayhyperactivity_1,todayhyperactivity_2,todayhyperactivity_3,todayhyperactivity_4,todayhyperactivity_5,todayimpulsivity_1,todayimpulsivity_2,todayimpulsivity_3,todayimpulsivity_4,todaysct_1,todaysct_2,todaysct_3,todaysct_4,todaysct_5,todaysct_6,todaysct_7,todaysct_8,todaysct_9,today_na1,todaygad_1,todaygad_2,todaygad_3,todaygad_4,...,hitop117_recontact,hitop250_recontact,hitop200_recontact,hitop160_recontact,hitop23_recontact,hitop165_recontact,hitop244_recontact,hitop9_recontact,hitop142_recontact,hitop230_recontact,hitop149_recontact,hitop247_recontact,hitop99_recontact,hitop66_recontact,hitop240_recontact,hitop222_recontact,hitop90_recontact,hitop113_recontact,hitop278_recontact,hitop203_recontact,hitop159_recontact,hitop123_recontact,hitop275_recontact,hitop268_recontact,hitop225_recontact,hitop143_recontact,hitop151_recontact,hitop181_recontact,hitop211_recontact,hitop17_recontact,hitop126_recontact,hitop5_recontact,hitop261_recontact,hitop220_recontact,check_notatall_recontact,hitop15_recontact,hitop72_recontact,hitop140_recontact,hitop109_recontact,hitop197_recontact,hitop104_recontact,todayinattention_1_recontact,todayinattention_2_recontact,todayinattention_3_recontact,todayinattention_4_recontact,todayinattention_5_recontact,todayinattention_6_recontact,todayinattention_7_recontact,todayinattention_8_recontact,todayinattention_9_recontact,todayhyperactivity_1_recontact,todayhyperactivity_2_recontact,todayhyperactivity_3_recontact,todayhyperactivity_4_recontact,todayhyperactivity_5_recontact,todayimpulsivity_1_recontact,todayimpulsivity_2_recontact,todayimpulsivity_3_recontact,todayimpulsivity_4_recontact,todaysct_1_recontact,todaysct_2_recontact,todaysct_3_recontact,todaysct_4_recontact,todaysct_5_recontact,todaysct_6_recontact,todaysct_7_recontact,todaysct_8_recontact,todaysct_9_recontact,today_na1_recontact,todaygad_1_recontact,todaygad_2_recontact,todaygad_3_recontact,todaygad_4_recontact,todaygad_5_recontact,todaygad_6_recontact,todaygad_7_recontact,todayphq_1_recontact,todayphq_2_recontact,todayphq_3_recontact,todayphq_4_recontact,todayphq_5_recontact,todayphq_6_recontact,todayphq_7_recontact,todayphq_8_recontact,today_na2_recontact,todayhitop157_recontact,todayhitop81_recontact,todayhitop34_recontact,todayhitop54_recontact,todayhitop243_recontact,todayhitop182_recontact,todayhitop69_recontact,todayhitop89_recontact,todayhitop50_recontact,todaycheck_1_recontact,todayhitop129_recontact,todayhitop265_recontact,todayhitop124_recontact,todayhitop231_recontact,todayhitop93_recontact,todayhitop67_recontact,todayhitop245_recontact,todayhitop281_recontact,today_na3_recontact,todayhitop141_recontact,todayhitop40_recontact,todayhitop204_recontact,todayhitop21_recontact,todayhitop236_recontact,todayhitop280_recontact,todayhitop84_recontact,todayhitop120_recontact,todayhitop77_recontact,todayhitop92_recontact,todayhitop258_recontact,todayhitop39_recontact,todayhitop254_recontact,todayhitop215_recontact,todayhitop95_recontact,todayhitop106_recontact,todayhitop283_recontact,todayhitop16_recontact,todayhitop20_recontact,todayhitop189_recontact,todayhitop1_recontact,todayhitop136_recontact,todayhitop246_recontact,todayhitop248_recontact,todayhitop257_recontact,todayhitop114_recontact,todayhitop117_recontact,todayhitop250_recontact,todayhitop200_recontact,todayhitop160_recontact,todayhitop23_recontact,todayhitop165_recontact,todayhitop244_recontact,today_na4_recontact,todayhitop9_recontact,todayhitop142_recontact,todayhitop230_recontact,todayhitop149_recontact,todayhitop247_recontact,todayhitop99_recontact,todayhitop66_recontact,todayhitop240_recontact,todayhitop222_recontact,todayhitop90_recontact,todayhitop113_recontact,todayhitop278_recontact,todayhitop203_recontact,todayhitop159_recontact,todayhitop123_recontact,todayhitop275_recontact,todayhitop268_recontact,todayhitop225_recontact,todayhitop143_recontact,todayhitop151_recontact,todayhitop181_recontact,todayhitop211_recontact,todayhitop17_recontact,todayhitop126_recontact,todayhitop5_recontact,todayhitop261_recontact,todayhitop220_recontact,todaycheck_2_recontact,todayhitop15_recontact,todayhitop72_recontact,todayhitop140_recontact,todayhitop109_recontact,todayhitop197_recontact,todayhitop104_recontact,today_na5_recontact,family_wealth_recontact,WHODAS_H2_recontact,WHODAS_H3_recontact,starttime_recontact,endtime_recontact,mood_dx,n_mood_dx,mood_bothered,mood_dx_recontact,n_mood_dx_recontact,mood_bothered_recontact,anxiety_dx,n_anxiety_dx,anxiety_bothered,anxiety_dx_recontact,n_anxiety_dx_recontact,anxiety_bothered_recontact,attention_dx,n_attention_dx,attention_bothered,attention_dx_recontact,n_attention_dx_recontact,attention_bothered_recontact,passed_checks,passed_grid,passed_grid_initialonly,passed_list,passed_checks_recontact,passed_grid_recontact,passed_list_recontact,baars_inattention_sum,baars_hyperactivity_sum,baars_impulsivity_sum,baars_sct_sum,gad_sum,phq_sum,baars_inattention_sum_recontact,baars_hyperactivity_sum_recontact,baars_impulsivity_sum_recontact,baars_sct_sum_recontact,gad_sum_recontact,phq_sum_recontact,hitop_anhedonic_depression,hitop_anhedonic_depression_recontact,hitop_anxious_worry,hitop_anxious_worry_recontact,hitop_appetite_gain,hitop_appetite_gain_recontact,hitop_appetite_loss,hitop_appetite_loss_recontact,hitop_cognitive_problems,hitop_cognitive_problems_recontact,hitop_hyposomnia,hitop_hyposomnia_recontact,hitop_indecisiveness,hitop_indecisiveness_recontact,hitop_insomnia,hitop_insomnia_recontact,hitop_panic,hitop_panic_recontact,hitop_separation_insecurity,hitop_separation_insecurity_recontact,hitop_shame_guilt,hitop_shame_guilt_recontact,hitop_situational_phobia,hitop_situational_phobia_recontact,hitop_social_anxiety,hitop_social_anxiety_recontact,hitop_well_being,hitop_well_being_recontact,hitop_sum,hitop_sum_recontact,baars_sum,baars_sum_recontact,moodanxiety_bothered,moodanxiety_bothered_recontact,whichdata
0,1250163174,1.106354,1,2,2,2,1,2,1,2,9,9,9,9,9,9,9,9,__NA__,NaN,9,9,9,9,9,9,9,9,9,9,9,9,9,9,9,9,9,9,9,9,9,__NA__,999,2,9,9,9,9,9,9,9,9,9,9,__NA__,NaN,9,9,9,9,9,9,9,9,9,9,9,9,__NA__,999,2,9,9,9,9,__NA__,NaN,9,9,9,9,9,9,9,9,9,9,9,__NA__,999,0,1,0,0,0,1,4,0,3,2,1,0,1,2,3,0,2,0,0,0,1,2,1,3,2,3,3,0,2,2,2,2,1,1,0,0,1,0,3,0,2,1,0,1,1,2,3,2,1,1,1,0,3,1,2,0,0,0,1,3,3,2,0,1,1,1,0,0,0,0,0,0,0,0,0,1,2,0,0,1,3,1,1,0,1,0,0,1,3,2,0,3,0,3,3,1,0,3,0,0,0,1,0,1,0,0,3,1,0,1,0,0,1,1,0,0,0,0,0,1,0,1,0,0,1,0,0,0,2,2,2,2,2,2,2,2,2,2,2,2,2,1,2,2,2,2,2,2,2,2,2,2,1,1,2,2,2,2,2,1,...,0,0,2,0,3,0,3,3,1,0,3,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,2,0,1,0,0,0,0,0,0,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,1,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,1,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,1,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,1,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,1,79.0,0.0,0.0,2023-09-01T22:40:03.442,2023-09-02T20:17:31.157,,0,False,,0,False,,0,False,,0,False,,0,False,,0,False,True,True,True,True,False,True,False,7,7,2,15,10,7,4,7,0,9,6,3,2,3,11,6,5,4,0,0,6,2,0,0,3,1,1,2,0,0,4,2,2,0,0,0,5,2,28,26,39,22,16,11,False,False,genpop
1,1250164036,1.265345,1,2,2,2,1,2,1,2,9,9,9,9,9,9,9,9,__NA__,NaN,9,9,9,9,9,9,9,9,9,9,9,9,9,9,9,9,9,9,9,9,9,__NA__,999,2,9,9,9,9,9,9,9,9,9,9,__NA__,NaN,9,9,9,9,9,9,9,9,9,9,9,9,__NA__,999,2,9,9,9,9,__NA__,NaN,9,9,9,9,9,9,9,9,9,9,9,__NA__,999,1,1,1,0,0,1,4,0,1,1,0,0,1,1,1,1,1,0,1,2,2,1,2,1,1,1,1,0,1,1,1,1,1,0,1,0,0,1,0,1,0,1,1,1,0,3,3,0,2,0,2,0,3,1,3,2,0,1,2,3,3,3,1,3,1,2,1,0,1,3,1,1,0,1,0,1,3,0,2,3,1,2,0,1,1,3,1,1,0,3,2,3,3,3,3,1,1,3,3,1,2,1,3,1,1,1,0,2,0,1,0,1,1,1,1,3,1,2,1,1,1,1,2,0,1,1,0,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,1,2,2,2,2,2,2,1,1,2,1,...,1,1,1,2,3,3,3,3,1,1,3,3,2,1,1,3,1,0,0,0,1,0,1,1,1,0,0,1,1,1,1,1,2,0,1,1,0,0,1,0,1,1,1,2,2,1,2,2,1,1,1,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,1,1,1,1,2,2,2,2,2,1,2,2,2,2,2,2,1,2,1,1,2,2,2,2,2,1,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,1,2,1,2,2,2,2,2,2,2,2,1,2,1,1,1,1,1,2,2,2,2,2,1,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,1,2,2,2,2,2,2,2,0.0,0.0,1.0,2023-09-01T22:52:12.464,2023-09-01T23:30:59.739,,0,False,,0,False,,0,False,,0,False,,0,False,,0,False,True,True,True,True,True,True,True,6,3,3,11,6,4,5,4,2,9,4,6,10,10,13,9,5,4,2,4,6,4,5,6,3,4,4,8,12,5,3,0,3,0,10,10,17,13,27,26,93,77,12,11,False,False,genpop
2,1250166926,1.002733,1,2,2,1,2,2,1,2,9,9,9,9,9,9,9,9,__NA__,NaN,9,9,9,9,9,9,9,9,9,9,9,9,9,9,9,9,9,9,9,9,9,__NA__,999,2,9,9,9,9,9,9,9,9,9,9,__NA__,NaN,9,9,9,9,9,9,9,9,9,9,9,9,__NA__,999,2,9,9,9,9,__NA__,NaN,9,9,9,9,9,9,9,9,9,9,9,__NA__,999,1,1,3,2,0,0,4,1,1,1,1,1,2,2,1,2,1,1,2,2,1,2,1,1,2,1,2,1,0,1,1,0,1,1,1,1,2,2,3,2,1,2,1,1,1,2,2,2,1,1,2,1,3,1,1,3,1,2,1,1,2,1,2,1,1,2,2,2,1,2,1,2,1,1,2,1,3,3,2,1,1,2,0,1,2,1,1,3,2,1,2,1,3,2,1,2,2,1,1,1,1,2,1,2,2,1,2,1,2,2,1,2,1,1,1,2,2,1,1,1,3,1,2,1,2,1,0,0,2,1,2,1,1,2,2,2,2,2,2,2,2,1,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,1,2,...,-2,-2,-2,-2,-2,-2,-2,-2,-2,-2,-2,-2,-2,-2,-2,-2,-2,-2,-2,-2,-2,-2,-2,-2,-2,-2,-2,-2,-2,-2,-2,-2,-2,-2,-1,-2,-2,-2,-2,-2,-2,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,No Data,No Data,No Data,No Data,No Data,,0,False,,0,False,,0,False,,0,False,,0,False,,0,False,False,True,True,False,False,False,False,10,7,6,13,5,14,-18,-10,-8,-18,-14,-16,15,-20,12,-14,6,-8,6,-6,5,-8,5,-10,4,-6,5,-8,8,-12,8,-16,7,-8,9,-10,18,-20,16,-20,108,-146,23,-36,False,False,genpop
3,1250168852,0.910403,1,2,2,2,2,2,1,2,9,9,9,9,9,9,9,9,__NA__,NaN,9,9,9,9,9,9,9,9,9,9,9,9,9,9,9,9,9,9,9,9,9,__NA__,999,2,9,9,9,9,9,9,9,9,9,9,__NA__,NaN,9,9,9,9,9,9,9,9,9,9,9,9,__NA__,999,2,9,9,9,9,__NA__,NaN,9,9,9,9,9,9,9,9,9,9,9,__NA__,999,0,0,0,1,0,0,4,1,1,1,0,0,0,0,0,0,0,0,0,0,1,0,0,0,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,2,1,0,0,0,0,3,0,0,0,0,0,0,2,0,1,0,0,0,0,0,0,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,2,3,3,2,1,0,2,1,0,0,0,0,0,0,0,0,0,0,0,3,0,0,0,0,0,1,0,0,1,0,1,1,0,0,0,0,0,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,1,2,2,2,2,...,0,0,1,3,1,3,3,1,0,3,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,1,0,0,0,1,1,0,1,3,0,0,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,1,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,1,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,1,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,1,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,1,50.0,0.0,0.0,2023-09-02T13:27:15.438,2023-09-02T13:48:31.670,,0,False,,0,False,,0,False,,0,False,,0,False,,0,False,False,True,True,False,False,True,False,4,0,0,3,0,0,2,1,0,1,0,0,1,4,0,5,3,0,0,6,1,1,0,0,0,1,6,4,1,3,0,1,0,1,4,3,1,0,13,11,17,29,4,3,False,False,genpop
4,1250099672,1.123096,1,2,2,1,1,2,1,2,9,9,9,9,9,9,9,9,__NA__,NaN,9,9,9,9,9,9,9,9,9,9,9,9,9,9,9,9,9,9,9,9,9,__NA__,999,2,9,9,9,9,9,9,9,9,9,9,__NA__,NaN,9,9,9,9,9,9,9,9,9,9,9,9,__NA__,999,2,9,9,9,9,__NA__,NaN,9,9,9,9,9,9,9,9,9,9,9,__NA__,999,1,1,1,1,0,0,4,1,1,2,2,0,1,0,0,0,2,2,1,1,1,1,1,2,2,2,1,0,0,1,1,1,1,0,0,3,0,2,2,3,0,3,0,3,0,1,3,3,3,3,0,1,3,2,0,1,0,2,2,1,0,3,2,1,1,2,0,1,3,2,1,1,3,3,1,1,0,0,0,1,2,1,0,1,2,3,1,1,0,2,3,1,0,0,1,3,0,0,1,2,0,0,0,1,0,0,2,2,0,3,1,1,1,2,0,1,1,1,0,3,1,1,1,1,1,0,0,2,2,1,2,1,1,2,1,1,1,1,2,2,2,2,2,2,2,1,2,1,1,1,1,1,1,1,2,2,2,2,2,2,...,1,2,0,2,1,0,0,0,2,1,0,0,1,1,2,0,1,0,0,2,2,1,3,1,0,1,1,0,1,0,0,0,2,1,1,1,1,1,2,0,2,1,1,1,1,2,2,1,1,1,1,2,1,1,2,2,1,1,1,1,2,1,1,1,2,1,2,1,2,1,1,1,1,1,2,1,1,1,2,1,1,1,1,2,2,1,2,1,2,2,1,2,2,1,1,2,2,2,2,1,1,2,2,2,2,2,2,1,1,1,1,2,1,2,2,2,1,2,1,2,1,2,1,1,2,2,2,1,2,1,1,2,2,2,2,2,2,2,2,1,2,2,2,2,2,1,2,1,2,2,1,1,2,1,2,2,1,2,2,2,2,2,2,1,1,1,2,2,1,1,2,1,2,40.0,0.0,2.0,2023-09-01T21:51:18.176,2023-09-01T22:06:47.415,,0,False,,0,False,,0,False,,0,False,,0,False,,0,False,True,True,True,True,True,True,True,8,3,5,11,4,13,10,4,4,11,7,9,16,15,6,10,12,7,0,4,9,8,2,2,3,4,10,7,9,5,8,4,4,4,2,0,11,7,8,4,92,77,16,18,False,False,genpop

In [53]:
for c in data_genpop_enriched_full.columns:
    print(c)

caseid
weight
sample_type
screener_1ongoing
screener_2impact
screener_3depression
screener_4anxiety
screener_5attention
consent
mood_yn
FNM_Q25_1
FNM_Q25_2
FNM_Q25_3
FNM_Q25_4
FNM_Q25_5
FNM_Q25_6
FNM_Q25_955
FNM_Q25_933
FNM_Q25_open1
mood_years
FNM_Q27_1
FNM_Q27_2
FNM_Q27_3
FNM_Q27_4
FNM_Q27_5
FNM_Q27_6
FNM_Q27_7
FNM_Q27_8
FNM_Q27_9
FNM_Q27_10
FNM_Q27_11
FNM_Q27_12
FNM_Q27_13
FNM_Q27_14
FNM_Q27_15
FNM_Q27_16
FNM_Q27_17
FNM_Q27_18
FNM_Q27_19
FNM_Q27_955
FNM_Q27_933
FNM_Q27_open1
mood_bothered_orig
anxiety_yn
FNM_Q30_m_1
FNM_Q30_m_2
FNM_Q30_m_3
FNM_Q30_m_4
FNM_Q30_m_5
FNM_Q30_m_6
FNM_Q30_m_7
FNM_Q30_m_8
FNM_Q30_m_955
FNM_Q30_m_933
FNM_Q30_open1
anxiety_years
FNM_Q32_1
FNM_Q32_2
FNM_Q32_3
FNM_Q32_4
FNM_Q32_5
FNM_Q32_6
FNM_Q32_7
FNM_Q32_8
FNM_Q32_9
FNM_Q32_10
FNM_Q32_955
FNM_Q32_933
FNM_Q32_open1
anxiety_bothered_orig
attention_yn
FNM_Q35_m_1
FNM_Q35_m_2
FNM_Q35_m_3
FNM_Q35_m_933
FNM_Q35_open1
attention_years
FNM_Q37_m_1
FNM_Q37_m_2
FNM_Q37_m_3
FNM_Q37_m_4
FNM_Q37_m_5
FNM_Q37_m_6
FNM_Q37_m_7
FNM_Q37_m_8
FNM_Q37_m_9
FNM_Q37_m_955
FNM_Q37_m_933
FNM_Q37_open1
attention_bothered_orig
inattention_1
inattention_2
inattention_3
inattention_4
inattention_5
inattention_6
FNM_Q1_attn
inattention_7
inattention_8
inattention_9
hyperactivity_1
hyperactivity_2
hyperactivity_3
hyperactivity_4
hyperactivity_5
impulsivity_1
impulsivity_2
impulsivity_3
impulsivity_4
sct_1
sct_2
sct_3
sct_4
sct_5
sct_6
sct_7
sct_8
sct_9
gad_1
gad_2
gad_3
gad_4
gad_5
gad_6
gad_7
phq_1
phq_2
phq_3
phq_4
phq_5
phq_6
phq_7
phq_8
hitop157
hitop81
hitop34
hitop54
hitop243
hitop182
hitop69
hitop89
hitop50
check_moderately
hitop129
hitop265
hitop124
hitop231
hitop93
hitop67
hitop245
hitop281
hitop141
hitop40
hitop204
hitop21
hitop236
hitop280
hitop84
hitop120
hitop77
hitop92
hitop258
hitop39
hitop254
hitop215
hitop95
hitop106
hitop283
hitop16
hitop20
hitop189
hitop1
hitop136
hitop246
hitop248
hitop257
hitop114
hitop117
hitop250
hitop200
hitop160
hitop23
hitop165
hitop244
hitop9
hitop142
hitop230
hitop149
hitop247
hitop99
hitop66
hitop240
hitop222
hitop90
hitop113
hitop278
hitop203
hitop159
hitop123
hitop275
hitop268
hitop225
hitop143
hitop151
hitop181
hitop211
hitop17
hitop126
hitop5
hitop261
hitop220
check_notatall
hitop15
hitop72
hitop140
hitop109
hitop197
hitop104
todayinattention_1
todayinattention_2
todayinattention_3
todayinattention_4
todayinattention_5
todayinattention_6
todayinattention_7
todayinattention_8
todayinattention_9
todayhyperactivity_1
todayhyperactivity_2
todayhyperactivity_3
todayhyperactivity_4
todayhyperactivity_5
todayimpulsivity_1
todayimpulsivity_2
todayimpulsivity_3
todayimpulsivity_4
todaysct_1
todaysct_2
todaysct_3
todaysct_4
todaysct_5
todaysct_6
todaysct_7
todaysct_8
todaysct_9
today_na1
todaygad_1
todaygad_2
todaygad_3
todaygad_4
todaygad_5
todaygad_6
todaygad_7
todayphq_1
todayphq_2
todayphq_3
todayphq_4
todayphq_5
todayphq_6
todayphq_7
todayphq_8
today_na2
todayhitop157
todayhitop81
todayhitop34
todayhitop54
todayhitop243
todayhitop182
todayhitop69
todayhitop89
todayhitop50
todaycheck_1
todayhitop129
todayhitop265
todayhitop124
todayhitop231
todayhitop93
todayhitop67
todayhitop245
todayhitop281
today_na3
todayhitop141
todayhitop40
todayhitop204
todayhitop21
todayhitop236
todayhitop280
todayhitop84
todayhitop120
todayhitop77
todayhitop92
todayhitop258
todayhitop39
todayhitop254
todayhitop215
todayhitop95
todayhitop106
todayhitop283
todayhitop16
todayhitop20
todayhitop189
todayhitop1
todayhitop136
todayhitop246
todayhitop248
todayhitop257
todayhitop114
todayhitop117
todayhitop250
todayhitop200
todayhitop160
todayhitop23
todayhitop165
todayhitop244
today_na4
todayhitop9
todayhitop142
todayhitop230
todayhitop149
todayhitop247
todayhitop99
todayhitop66
todayhitop240
todayhitop222
todayhitop90
todayhitop113
todayhitop278
todayhitop203
todayhitop159
todayhitop123
todayhitop275
todayhitop268
todayhitop225
todayhitop143
todayhitop151
todayhitop181
todayhitop211
todayhitop17
todayhitop126
todayhitop5
todayhitop261
todayhitop220
todaycheck_2
todayhitop15
todayhitop72
todayhitop140
todayhitop109
todayhitop197
todayhitop104
today_na5
family_wealth
WHODAS_H2
WHODAS_H3
genhealth
healthinsur_srg_1
healthinsur_srg_2
healthinsur_srg_3
healthinsur_srg_4
healthinsur_srg_5
healthinsur_srg_6
healthinsur_srg_7
healthinsur_srg_8
healthinsur_srg_99
race_client
hispanic
birthyr
gender
sex
educ
marstat
employ
inputstate
faminc_new
child18
starttime
endtime
screener_1ongoing_recontact
screener_2impact_recontact
screener_3depression_recontact
screener_4anxiety_recontact
screener_5attention_recontact
consent_recontact
mood_yn_recontact
FNM_Q25_1_recontact
FNM_Q25_2_recontact
FNM_Q25_3_recontact
FNM_Q25_4_recontact
FNM_Q25_5_recontact
FNM_Q25_6_recontact
FNM_Q25_955_recontact
FNM_Q25_933_recontact
FNM_Q25_open1_recontact
mood_years_recontact
FNM_Q27_1_recontact
FNM_Q27_2_recontact
FNM_Q27_3_recontact
FNM_Q27_4_recontact
FNM_Q27_5_recontact
FNM_Q27_6_recontact
FNM_Q27_7_recontact
FNM_Q27_8_recontact
FNM_Q27_9_recontact
FNM_Q27_10_recontact
FNM_Q27_11_recontact
FNM_Q27_12_recontact
FNM_Q27_13_recontact
FNM_Q27_14_recontact
FNM_Q27_15_recontact
FNM_Q27_16_recontact
FNM_Q27_17_recontact
FNM_Q27_18_recontact
FNM_Q27_19_recontact
FNM_Q27_955_recontact
FNM_Q27_933_recontact
FNM_Q27_open1_recontact
mood_bothered_recontact_orig
anxiety_yn_recontact
FNM_Q30_m_1_recontact
FNM_Q30_m_2_recontact
FNM_Q30_m_3_recontact
FNM_Q30_m_4_recontact
FNM_Q30_m_5_recontact
FNM_Q30_m_6_recontact
FNM_Q30_m_7_recontact
FNM_Q30_m_8_recontact
FNM_Q30_m_955_recontact
FNM_Q30_m_933_recontact
FNM_Q30_open1_recontact
anxiety_years_recontact
FNM_Q32_1_recontact
FNM_Q32_2_recontact
FNM_Q32_3_recontact
FNM_Q32_4_recontact
FNM_Q32_5_recontact
FNM_Q32_6_recontact
FNM_Q32_7_recontact
FNM_Q32_8_recontact
FNM_Q32_9_recontact
FNM_Q32_10_recontact
FNM_Q32_955_recontact
FNM_Q32_933_recontact
FNM_Q32_open1_recontact
anxiety_bothered_recontact_orig
attention_yn_recontact
FNM_Q35_m_1_recontact
FNM_Q35_m_2_recontact
FNM_Q35_m_3_recontact
FNM_Q35_m_933_recontact
FNM_Q35_open1_recontact
attention_years_recontact
FNM_Q37_m_1_recontact
FNM_Q37_m_2_recontact
FNM_Q37_m_3_recontact
FNM_Q37_m_4_recontact
FNM_Q37_m_5_recontact
FNM_Q37_m_6_recontact
FNM_Q37_m_7_recontact
FNM_Q37_m_8_recontact
FNM_Q37_m_9_recontact
FNM_Q37_m_955_recontact
FNM_Q37_m_933_recontact
FNM_Q37_open1_recontact
attention_bothered_recontact_orig
inattention_1_recontact
inattention_2_recontact
inattention_3_recontact
inattention_4_recontact
inattention_5_recontact
inattention_6_recontact
FNM_Q1_attn_recontact
inattention_7_recontact
inattention_8_recontact
inattention_9_recontact
hyperactivity_1_recontact
hyperactivity_2_recontact
hyperactivity_3_recontact
hyperactivity_4_recontact
hyperactivity_5_recontact
impulsivity_1_recontact
impulsivity_2_recontact
impulsivity_3_recontact
impulsivity_4_recontact
sct_1_recontact
sct_2_recontact
sct_3_recontact
sct_4_recontact
sct_5_recontact
sct_6_recontact
sct_7_recontact
sct_8_recontact
sct_9_recontact
gad_1_recontact
gad_2_recontact
gad_3_recontact
gad_4_recontact
gad_5_recontact
gad_6_recontact
gad_7_recontact
phq_1_recontact
phq_2_recontact
phq_3_recontact
phq_4_recontact
phq_5_recontact
phq_6_recontact
phq_7_recontact
phq_8_recontact
hitop157_recontact
hitop81_recontact
hitop34_recontact
hitop54_recontact
hitop243_recontact
hitop182_recontact
hitop69_recontact
hitop89_recontact
hitop50_recontact
check_moderately_recontact
hitop129_recontact
hitop265_recontact
hitop124_recontact
hitop231_recontact
hitop93_recontact
hitop67_recontact
hitop245_recontact
hitop281_recontact
hitop141_recontact
hitop40_recontact
hitop204_recontact
hitop21_recontact
hitop236_recontact
hitop280_recontact
hitop84_recontact
hitop120_recontact
hitop77_recontact
hitop92_recontact
hitop258_recontact
hitop39_recontact
hitop254_recontact
hitop215_recontact
hitop95_recontact
hitop106_recontact
hitop283_recontact
hitop16_recontact
hitop20_recontact
hitop189_recontact
hitop1_recontact
hitop136_recontact
hitop246_recontact
hitop248_recontact
hitop257_recontact
hitop114_recontact
hitop117_recontact
hitop250_recontact
hitop200_recontact
hitop160_recontact
hitop23_recontact
hitop165_recontact
hitop244_recontact
hitop9_recontact
hitop142_recontact
hitop230_recontact
hitop149_recontact
hitop247_recontact
hitop99_recontact
hitop66_recontact
hitop240_recontact
hitop222_recontact
hitop90_recontact
hitop113_recontact
hitop278_recontact
hitop203_recontact
hitop159_recontact
hitop123_recontact
hitop275_recontact
hitop268_recontact
hitop225_recontact
hitop143_recontact
hitop151_recontact
hitop181_recontact
hitop211_recontact
hitop17_recontact
hitop126_recontact
hitop5_recontact
hitop261_recontact
hitop220_recontact
check_notatall_recontact
hitop15_recontact
hitop72_recontact
hitop140_recontact
hitop109_recontact
hitop197_recontact
hitop104_recontact
todayinattention_1_recontact
todayinattention_2_recontact
todayinattention_3_recontact
todayinattention_4_recontact
todayinattention_5_recontact
todayinattention_6_recontact
todayinattention_7_recontact
todayinattention_8_recontact
todayinattention_9_recontact
todayhyperactivity_1_recontact
todayhyperactivity_2_recontact
todayhyperactivity_3_recontact
todayhyperactivity_4_recontact
todayhyperactivity_5_recontact
todayimpulsivity_1_recontact
todayimpulsivity_2_recontact
todayimpulsivity_3_recontact
todayimpulsivity_4_recontact
todaysct_1_recontact
todaysct_2_recontact
todaysct_3_recontact
todaysct_4_recontact
todaysct_5_recontact
todaysct_6_recontact
todaysct_7_recontact
todaysct_8_recontact
todaysct_9_recontact
today_na1_recontact
todaygad_1_recontact
todaygad_2_recontact
todaygad_3_recontact
todaygad_4_recontact
todaygad_5_recontact
todaygad_6_recontact
todaygad_7_recontact
todayphq_1_recontact
todayphq_2_recontact
todayphq_3_recontact
todayphq_4_recontact
todayphq_5_recontact
todayphq_6_recontact
todayphq_7_recontact
todayphq_8_recontact
today_na2_recontact
todayhitop157_recontact
todayhitop81_recontact
todayhitop34_recontact
todayhitop54_recontact
todayhitop243_recontact
todayhitop182_recontact
todayhitop69_recontact
todayhitop89_recontact
todayhitop50_recontact
todaycheck_1_recontact
todayhitop129_recontact
todayhitop265_recontact
todayhitop124_recontact
todayhitop231_recontact
todayhitop93_recontact
todayhitop67_recontact
todayhitop245_recontact
todayhitop281_recontact
today_na3_recontact
todayhitop141_recontact
todayhitop40_recontact
todayhitop204_recontact
todayhitop21_recontact
todayhitop236_recontact
todayhitop280_recontact
todayhitop84_recontact
todayhitop120_recontact
todayhitop77_recontact
todayhitop92_recontact
todayhitop258_recontact
todayhitop39_recontact
todayhitop254_recontact
todayhitop215_recontact
todayhitop95_recontact
todayhitop106_recontact
todayhitop283_recontact
todayhitop16_recontact
todayhitop20_recontact
todayhitop189_recontact
todayhitop1_recontact
todayhitop136_recontact
todayhitop246_recontact
todayhitop248_recontact
todayhitop257_recontact
todayhitop114_recontact
todayhitop117_recontact
todayhitop250_recontact
todayhitop200_recontact
todayhitop160_recontact
todayhitop23_recontact
todayhitop165_recontact
todayhitop244_recontact
today_na4_recontact
todayhitop9_recontact
todayhitop142_recontact
todayhitop230_recontact
todayhitop149_recontact
todayhitop247_recontact
todayhitop99_recontact
todayhitop66_recontact
todayhitop240_recontact
todayhitop222_recontact
todayhitop90_recontact
todayhitop113_recontact
todayhitop278_recontact
todayhitop203_recontact
todayhitop159_recontact
todayhitop123_recontact
todayhitop275_recontact
todayhitop268_recontact
todayhitop225_recontact
todayhitop143_recontact
todayhitop151_recontact
todayhitop181_recontact
todayhitop211_recontact
todayhitop17_recontact
todayhitop126_recontact
todayhitop5_recontact
todayhitop261_recontact
todayhitop220_recontact
todaycheck_2_recontact
todayhitop15_recontact
todayhitop72_recontact
todayhitop140_recontact
todayhitop109_recontact
todayhitop197_recontact
todayhitop104_recontact
today_na5_recontact
family_wealth_recontact
WHODAS_H2_recontact
WHODAS_H3_recontact
starttime_recontact
endtime_recontact
mood_dx
n_mood_dx
mood_bothered
mood_dx_recontact
n_mood_dx_recontact
mood_bothered_recontact
anxiety_dx
n_anxiety_dx
anxiety_bothered
anxiety_dx_recontact
n_anxiety_dx_recontact
anxiety_bothered_recontact
attention_dx
n_attention_dx
attention_bothered
attention_dx_recontact
n_attention_dx_recontact
attention_bothered_recontact
passed_checks
passed_grid
passed_grid_initialonly
passed_list
passed_checks_recontact
passed_grid_recontact
passed_list_recontact
baars_inattention_sum
baars_hyperactivity_sum
baars_impulsivity_sum
baars_sct_sum
gad_sum
phq_sum
baars_inattention_sum_recontact
baars_hyperactivity_sum_recontact
baars_impulsivity_sum_recontact
baars_sct_sum_recontact
gad_sum_recontact
phq_sum_recontact
hitop_anhedonic_depression
hitop_anhedonic_depression_recontact
hitop_anxious_worry
hitop_anxious_worry_recontact
hitop_appetite_gain
hitop_appetite_gain_recontact
hitop_appetite_loss
hitop_appetite_loss_recontact
hitop_cognitive_problems
hitop_cognitive_problems_recontact
hitop_hyposomnia
hitop_hyposomnia_recontact
hitop_indecisiveness
hitop_indecisiveness_recontact
hitop_insomnia
hitop_insomnia_recontact
hitop_panic
hitop_panic_recontact
hitop_separation_insecurity
hitop_separation_insecurity_recontact
hitop_shame_guilt
hitop_shame_guilt_recontact
hitop_situational_phobia
hitop_situational_phobia_recontact
hitop_social_anxiety
hitop_social_anxiety_recontact
hitop_well_being
hitop_well_being_recontact
hitop_sum
hitop_sum_recontact
baars_sum
baars_sum_recontact
moodanxiety_bothered
moodanxiety_bothered_recontact
whichdata

In [16]:
# TO REMOVE: quickly check loaded data
print('val - genpop')
flag_metric, pconfig, pmetric, pscalar, pstrict = cfa_helper_func(
    scalename = 'insomnia',
    list_of_items = ['hitop160', 'hitop254', 'hitop261', 'hitop268'],
    do_metric = True, do_scalar = True, do_strict = True, 
    mydata_python = mydata_val_enriched, 
    mydata_temp_path = '/Users/zeleninam2/Documents/1_projects/hitop/data/CFA/temp/cfa_temp.csv')

val - genpop

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG chisq p = 0.004
PASSED SECONDARY CRITERIA WITH CFI = 0.998 TLI = 0.995 RMSEA = 0.055

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT chisq p = 0.652
SCALAR INVARIANT NOT PASSED, chisq p = 0
STRICT N/A

# Do main CFA analysis

## 3-way CFA

### 1. Check original items
Get full 3-way CFA results (config, metric, scalar, strict) for all original scales.

In [16]:
orig_items = {'anhedonic_depression': 'anhedonic_depression =~hitop39 + hitop77 + hitop84 + hitop92 + hitop93 + hitop123 + hitop157 + hitop182 + hitop230 + hitop246',
         'anxious_worry': 'anxious_worry =~hitop20 + hitop34 + hitop89 + hitop203 + hitop248 + hitop265',
         'appetite_gain': 'appetite_gain =~hitop120 + hitop141 + hitop243 + hitop275',
         'appetite_loss': 'appetite_loss =~hitop280 + hitop283 + hitop109',
         'cognitive_problems': 'cognitive_problems =~hitop67 + hitop189 + hitop142',
         'hyposomnia': 'hyposomnia =~hitop99 + hitop181 + hitop5 + hitop66 + hitop231',
         'insomnia': 'insomnia =~hitop160 + hitop254 + hitop261 + hitop268',
         'panic': 'panic =~hitop15 + hitop104 + hitop126 + hitop211 + hitop215 + hitop257',
         'separation_insecurity': 'separation_insecurity =~hitop40 + hitop50 + hitop69 + hitop81 + hitop113 + hitop136 + hitop151 + hitop197',
         'shame_guilt': 'shame_guilt =~hitop72 + hitop140 + hitop143 + hitop220',
         'situational_phobia': 'situational_phobia =~hitop16 + hitop165 + hitop225 + hitop247 + hitop278',
         'social_anxiety': 'social_anxiety =~hitop1 + hitop17 + hitop114 + hitop117 + hitop124 + hitop129 + hitop204 + hitop222 + hitop236 + hitop258',
         'well_being': 'well_being =~hitop9 + hitop23 + hitop54 + hitop106 + hitop149 + hitop200 + hitop244 + hitop245 + hitop250 + hitop281'}

In [37]:
with open("logs/mylog_3wayCFA_origscales_seed12345_v2.txt", "w") as f:
    with redirect_stdout(f):
        for scale, items in orig_items.items():
            # print which scale we are processing through R - this way it doesn't get saved in the log file
            ro.globalenv['scale_to_print'] = scale
            ro.r('print(scale_to_print)')
            # create a neat list of items to test for this scale
            items_only = items.split("=~",1)[1]
            items_list = items_only.split(" + ")
            # test   
            run_specific_cfa(whichscale=scale,\
                         item_list=items_list, \
                         whichcfa='strict')

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

### 2. Find invariant subsets

#### Looping through all scales where full scales did not pass metric invariance:

In [74]:
with open("logs/mylog_3wayCFA_lookingforinv_seed12345_v1.txt", "w") as f:
    with redirect_stdout(f):
        for scale in ['anhedonic_depression', 'anxious_worry', 'appetite_gain', 'separation_insecurity', 'situation_phobia', 'social_anxiety', 'well_being']:
            print(f'\n\n\n======================================\nTESTING SCALE {scale.upper()}\n======================================\n')
            items = orig_items[scale]
            # create a neat FULL list of items to test for this scale
            items_only = items.split("=~",1)[1]
            items_list = items_only.split(" + ")
            # how many items are there in total?
            howmany = len(items_list)
            # remove items one by one
            for i in range (1, howmany):
                how_many_to_try = howmany - i
                print(f'\n-----------------------------\nTESTING n - {i} = {how_many_to_try} ITEMS for scale {scale}\n-----------------------------\n')
                if how_many_to_try <= 2: # the min amount of items we can test is 3
                    print("\nWe ran out of items! No inv subset can be found")
                    break
                # test cfa
                successful_combinations_for_scale = do_three_way_cfa_ablations(whichscale=scale, whichcfa='metric', howmanyitems=how_many_to_try)
                # if found any number of successful items, save them and stop trying for this scale
                if successful_combinations_for_scale: 
                    print(f'\n!!!!! Found at least one invariant subset for SCALE {scale} with ITEMS = {how_many_to_try} (removing {i} items)\n')
                    print(successful_combinations_for_scale)
                    break

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.



#### An option to do it manually:
For each scale, start with x-1 items, then x-2 etc; check all compbinations of those items.

Running only down to metric level because this can get very computationally-heavy. For the selected inv subsets, I'll then test all CFA levels later.

In [75]:
successful_combinations_for_scale = do_three_way_cfa_ablations(whichscale='social_anxiety', whichcfa='metric', howmanyitems=6)
successful_combinations_for_scale

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

FOR SCALE SOCIAL_ANXIETY:
RUN ALL COMBINATIONS OF 6 ITEMS and checks if a combination is 3-way invariant.


Running SOCIAL_ANXIETY
Items: social_anxiety =~hitop1 + hitop17 + hitop114 + hitop117 + hitop124 + hitop129 + hitop204 + hitop222 + hitop236 + hitop258

+++ TESTING 1th COMBINATION out of 210 possible combinations of 6 items +++
Items to test: ('hitop1', 'hitop17', 'hitop114', 'hitop117', 'hitop124', 'hitop129')

 -----> VALID VS GENPOP <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG INVARIANT NOT PASSED, chisq p = 0
METRIC N/A
SCALAR N/A
STRICT N/A

 -----> VALID VS ENRICHED <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG INVARIANT NOT PASSED, chisq p = 0.005
METRIC N/A
SCALAR N/A
STRICT N/A

 -----> GENPOP VS ENRICHED <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG chisq p = 0.01
PASSED SECONDARY CRITERIA WITH CFI = 0.999 TLI = 0.998 RMSEA = 0.049

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT NOT PASSED, chisq p = 0.03
SCALAR N/A
STRICT N/A

+++ TESTING 2th COMBINATION out of 210 possible combinations of 6 items +++
Items to test: ('hitop1', 'hitop17', 'hitop114', 'hitop117', 'hitop124', 'hitop204')

 -----> VALID VS GENPOP <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG chisq p = 0
PASSED SECONDARY CRITERIA WITH CFI = 0.995 TLI = 0.992 RMSEA = 0.049

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT NOT PASSED, chisq p = 0.003
SCALAR N/A
STRICT N/A

 -----> VALID VS ENRICHED <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG chisq p = 0.004
PASSED SECONDARY CRITERIA WITH CFI = 0.995 TLI = 0.991 RMSEA = 0.057

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT chisq p = 0.158
SCALAR N/A
STRICT N/A

 -----> GENPOP VS ENRICHED <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG INVARIANT chisq p = 0.061

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT NOT PASSED, chisq p = 0.014
SCALAR N/A
STRICT N/A

+++ TESTING 3th COMBINATION out of 210 possible combinations of 6 items +++
Items to test: ('hitop1', 'hitop17', 'hitop114', 'hitop117', 'hitop124', 'hitop222')

 -----> VALID VS GENPOP <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG chisq p = 0
PASSED SECONDARY CRITERIA WITH CFI = 0.995 TLI = 0.991 RMSEA = 0.052

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT NOT PASSED, chisq p = 0.006
SCALAR N/A
STRICT N/A

 -----> VALID VS ENRICHED <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG INVARIANT NOT PASSED, chisq p = 0.033
METRIC N/A
SCALAR N/A
STRICT N/A

 -----> GENPOP VS ENRICHED <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG INVARIANT chisq p = 0.071

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT NOT PASSED, chisq p = 0.005
SCALAR N/A
STRICT N/A

+++ TESTING 4th COMBINATION out of 210 possible combinations of 6 items +++
Items to test: ('hitop1', 'hitop17', 'hitop114', 'hitop117', 'hitop124', 'hitop236')

 -----> VALID VS GENPOP <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG chisq p = 0
PASSED SECONDARY CRITERIA WITH CFI = 0.997 TLI = 0.995 RMSEA = 0.04

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT NOT PASSED, chisq p = 0.002
SCALAR N/A
STRICT N/A

 -----> VALID VS ENRICHED <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG chisq p = 0.001
PASSED SECONDARY CRITERIA WITH CFI = 0.999 TLI = 0.998 RMSEA = 0.052

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT chisq p = 0.343
SCALAR N/A
STRICT N/A

 -----> GENPOP VS ENRICHED <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG chisq p = 0.011
PASSED SECONDARY CRITERIA WITH CFI = 0.998 TLI = 0.997 RMSEA = 0.03

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT NOT PASSED, chisq p = 0.014
SCALAR N/A
STRICT N/A

+++ TESTING 5th COMBINATION out of 210 possible combinations of 6 items +++
Items to test: ('hitop1', 'hitop17', 'hitop114', 'hitop117', 'hitop124', 'hitop258')

 -----> VALID VS GENPOP <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG chisq p = 0
PASSED SECONDARY CRITERIA WITH CFI = 1.0 TLI = 1.0 RMSEA = 0.04

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT NOT PASSED, chisq p = 0
SCALAR N/A
STRICT N/A

 -----> VALID VS ENRICHED <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG chisq p = 0.002
PASSED SECONDARY CRITERIA WITH CFI = 0.996 TLI = 0.993 RMSEA = 0.051

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT chisq p = 0.133
SCALAR N/A
STRICT N/A

 -----> GENPOP VS ENRICHED <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG chisq p = 0.003
PASSED SECONDARY CRITERIA WITH CFI = 1.0 TLI = 1.004 RMSEA = 0.028

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT NOT PASSED, chisq p = 0.011
SCALAR N/A
STRICT N/A

+++ TESTING 6th COMBINATION out of 210 possible combinations of 6 items +++
Items to test: ('hitop1', 'hitop17', 'hitop114', 'hitop117', 'hitop129', 'hitop204')

 -----> VALID VS GENPOP <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG INVARIANT chisq p = 0.202

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT NOT PASSED, chisq p = 0.01
SCALAR N/A
STRICT N/A

 -----> VALID VS ENRICHED <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG INVARIANT chisq p = 0.102

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT chisq p = 0.153
SCALAR N/A
STRICT N/A

 -----> GENPOP VS ENRICHED <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG INVARIANT chisq p = 0.063

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT NOT PASSED, chisq p = 0.014
SCALAR N/A
STRICT N/A

+++ TESTING 7th COMBINATION out of 210 possible combinations of 6 items +++
Items to test: ('hitop1', 'hitop17', 'hitop114', 'hitop117', 'hitop129', 'hitop222')

 -----> VALID VS GENPOP <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG chisq p = 0
PASSED SECONDARY CRITERIA WITH CFI = 0.997 TLI = 0.994 RMSEA = 0.041

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT NOT PASSED, chisq p = 0.012
SCALAR N/A
STRICT N/A

 -----> VALID VS ENRICHED <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG chisq p = 0.007
PASSED SECONDARY CRITERIA WITH CFI = 0.999 TLI = 0.998 RMSEA = 0.048

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT chisq p = 0.076
SCALAR N/A
STRICT N/A

 -----> GENPOP VS ENRICHED <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG INVARIANT chisq p = 0.153

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT NOT PASSED, chisq p = 0.008
SCALAR N/A
STRICT N/A

+++ TESTING 8th COMBINATION out of 210 possible combinations of 6 items +++
Items to test: ('hitop1', 'hitop17', 'hitop114', 'hitop117', 'hitop129', 'hitop236')

 -----> VALID VS GENPOP <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG chisq p = 0.006
PASSED SECONDARY CRITERIA WITH CFI = 0.998 TLI = 0.997 RMSEA = 0.028

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT NOT PASSED, chisq p = 0.005
SCALAR N/A
STRICT N/A

 -----> VALID VS ENRICHED <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG chisq p = 0.008
PASSED SECONDARY CRITERIA WITH CFI = 1.0 TLI = 0.999 RMSEA = 0.044

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT chisq p = 0.205
SCALAR N/A
STRICT N/A

 -----> GENPOP VS ENRICHED <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG chisq p = 0.01
PASSED SECONDARY CRITERIA WITH CFI = 1.0 TLI = 1.004 RMSEA = 0.026

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT NOT PASSED, chisq p = 0.025
SCALAR N/A
STRICT N/A

+++ TESTING 9th COMBINATION out of 210 possible combinations of 6 items +++
Items to test: ('hitop1', 'hitop17', 'hitop114', 'hitop117', 'hitop129', 'hitop258')

 -----> VALID VS GENPOP <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG INVARIANT chisq p = 0.154

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT NOT PASSED, chisq p = 0.002
SCALAR N/A
STRICT N/A

 -----> VALID VS ENRICHED <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG chisq p = 0.012
PASSED SECONDARY CRITERIA WITH CFI = 0.997 TLI = 0.996 RMSEA = 0.057

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT chisq p = 0.144
SCALAR N/A
STRICT N/A

 -----> GENPOP VS ENRICHED <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG chisq p = 0.006
PASSED SECONDARY CRITERIA WITH CFI = 1.0 TLI = 1.0 RMSEA = 0.042

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT NOT PASSED, chisq p = 0.007
SCALAR N/A
STRICT N/A

+++ TESTING 10th COMBINATION out of 210 possible combinations of 6 items +++
Items to test: ('hitop1', 'hitop17', 'hitop114', 'hitop117', 'hitop204', 'hitop222')

 -----> VALID VS GENPOP <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG chisq p = 0
PASSED SECONDARY CRITERIA WITH CFI = 1.0 TLI = 1.001 RMSEA = 0.036

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT NOT PASSED, chisq p = 0.011
SCALAR N/A
STRICT N/A

 -----> VALID VS ENRICHED <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG chisq p = 0.026
PASSED SECONDARY CRITERIA WITH CFI = 0.997 TLI = 0.995 RMSEA = 0.042

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT NOT PASSED, chisq p = 0.031
SCALAR N/A
STRICT N/A

 -----> GENPOP VS ENRICHED <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG INVARIANT chisq p = 0.152

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT NOT PASSED, chisq p = 0.003
SCALAR N/A
STRICT N/A

+++ TESTING 11th COMBINATION out of 210 possible combinations of 6 items +++
Items to test: ('hitop1', 'hitop17', 'hitop114', 'hitop117', 'hitop204', 'hitop236')

 -----> VALID VS GENPOP <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG chisq p = 0.015
PASSED SECONDARY CRITERIA WITH CFI = 0.998 TLI = 0.997 RMSEA = 0.029

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT NOT PASSED, chisq p = 0.004
SCALAR N/A
STRICT N/A

 -----> VALID VS ENRICHED <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG chisq p = 0.025
PASSED SECONDARY CRITERIA WITH CFI = 1.0 TLI = 1.001 RMSEA = 0.038

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT chisq p = 0.162
SCALAR N/A
STRICT N/A

 -----> GENPOP VS ENRICHED <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG chisq p = 0
PASSED SECONDARY CRITERIA WITH CFI = 0.998 TLI = 0.997 RMSEA = 0.03

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT NOT PASSED, chisq p = 0.007
SCALAR N/A
STRICT N/A

+++ TESTING 12th COMBINATION out of 210 possible combinations of 6 items +++
Items to test: ('hitop1', 'hitop17', 'hitop114', 'hitop117', 'hitop204', 'hitop258')

 -----> VALID VS GENPOP <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG INVARIANT chisq p = 0.113

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT NOT PASSED, chisq p = 0.003
SCALAR N/A
STRICT N/A

 -----> VALID VS ENRICHED <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG chisq p = 0.043
PASSED SECONDARY CRITERIA WITH CFI = 0.997 TLI = 0.995 RMSEA = 0.043

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT chisq p = 0.164
SCALAR N/A
STRICT N/A

 -----> GENPOP VS ENRICHED <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG chisq p = 0.014
PASSED SECONDARY CRITERIA WITH CFI = 0.998 TLI = 0.996 RMSEA = 0.033

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT NOT PASSED, chisq p = 0.002
SCALAR N/A
STRICT N/A

+++ TESTING 13th COMBINATION out of 210 possible combinations of 6 items +++
Items to test: ('hitop1', 'hitop17', 'hitop114', 'hitop117', 'hitop222', 'hitop236')

 -----> VALID VS GENPOP <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG chisq p = 0
PASSED SECONDARY CRITERIA WITH CFI = 0.999 TLI = 0.999 RMSEA = 0.043

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT NOT PASSED, chisq p = 0.011
SCALAR N/A
STRICT N/A

 -----> VALID VS ENRICHED <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG chisq p = 0
PASSED SECONDARY CRITERIA WITH CFI = 0.995 TLI = 0.992 RMSEA = 0.053

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT chisq p = 0.116
SCALAR N/A
STRICT N/A

 -----> GENPOP VS ENRICHED <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG chisq p = 0.035
PASSED SECONDARY CRITERIA WITH CFI = 1.0 TLI = 1.003 RMSEA = 0.029

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT NOT PASSED, chisq p = 0.002
SCALAR N/A
STRICT N/A

+++ TESTING 14th COMBINATION out of 210 possible combinations of 6 items +++
Items to test: ('hitop1', 'hitop17', 'hitop114', 'hitop117', 'hitop222', 'hitop258')

 -----> VALID VS GENPOP <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG chisq p = 0
PASSED SECONDARY CRITERIA WITH CFI = 0.999 TLI = 0.999 RMSEA = 0.043

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT NOT PASSED, chisq p = 0.002
SCALAR N/A
STRICT N/A

 -----> VALID VS ENRICHED <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG chisq p = 0.008
PASSED SECONDARY CRITERIA WITH CFI = 0.999 TLI = 0.998 RMSEA = 0.053

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT NOT PASSED, chisq p = 0.036
SCALAR N/A
STRICT N/A

 -----> GENPOP VS ENRICHED <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG chisq p = 0.005
PASSED SECONDARY CRITERIA WITH CFI = 1.0 TLI = 1.003 RMSEA = 0.029

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT NOT PASSED, chisq p = 0.001
SCALAR N/A
STRICT N/A

+++ TESTING 15th COMBINATION out of 210 possible combinations of 6 items +++
Items to test: ('hitop1', 'hitop17', 'hitop114', 'hitop117', 'hitop236', 'hitop258')

 -----> VALID VS GENPOP <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG chisq p = 0.002
PASSED SECONDARY CRITERIA WITH CFI = 1.0 TLI = 1.002 RMSEA = 0.032

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT NOT PASSED, chisq p = 0.002
SCALAR N/A
STRICT N/A

 -----> VALID VS ENRICHED <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG chisq p = 0.002
PASSED SECONDARY CRITERIA WITH CFI = 0.999 TLI = 0.999 RMSEA = 0.047

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT chisq p = 0.143
SCALAR N/A
STRICT N/A

 -----> GENPOP VS ENRICHED <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG chisq p = 0
PASSED SECONDARY CRITERIA WITH CFI = 1.0 TLI = 1.004 RMSEA = 0.028

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT NOT PASSED, chisq p = 0.002
SCALAR N/A
STRICT N/A

+++ TESTING 16th COMBINATION out of 210 possible combinations of 6 items +++
Items to test: ('hitop1', 'hitop17', 'hitop114', 'hitop124', 'hitop129', 'hitop204')

 -----> VALID VS GENPOP <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG INVARIANT NOT PASSED, chisq p = 0.002
METRIC N/A
SCALAR N/A
STRICT N/A

 -----> VALID VS ENRICHED <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG INVARIANT chisq p = 0.059

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT chisq p = 0.065
SCALAR N/A
STRICT N/A

 -----> GENPOP VS ENRICHED <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG INVARIANT chisq p = 0.099

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT chisq p = 0.216
SCALAR N/A
STRICT N/A

+++ TESTING 17th COMBINATION out of 210 possible combinations of 6 items +++
Items to test: ('hitop1', 'hitop17', 'hitop114', 'hitop124', 'hitop129', 'hitop222')

 -----> VALID VS GENPOP <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG INVARIANT NOT PASSED, chisq p = 0
METRIC N/A
SCALAR N/A
STRICT N/A

 -----> VALID VS ENRICHED <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG INVARIANT chisq p = 0.087

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT NOT PASSED, chisq p = 0.033
SCALAR N/A
STRICT N/A

 -----> GENPOP VS ENRICHED <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG INVARIANT chisq p = 0.14

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT chisq p = 0.287
SCALAR N/A
STRICT N/A

+++ TESTING 18th COMBINATION out of 210 possible combinations of 6 items +++
Items to test: ('hitop1', 'hitop17', 'hitop114', 'hitop124', 'hitop129', 'hitop236')

 -----> VALID VS GENPOP <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG chisq p = 0
PASSED SECONDARY CRITERIA WITH CFI = 0.996 TLI = 0.994 RMSEA = 0.056

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT NOT PASSED, chisq p = 0
SCALAR N/A
STRICT N/A

 -----> VALID VS ENRICHED <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG INVARIANT NOT PASSED, chisq p = 0.014
METRIC N/A
SCALAR N/A
STRICT N/A

 -----> GENPOP VS ENRICHED <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG INVARIANT chisq p = 0.077

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT NOT PASSED, chisq p = 0.045
SCALAR N/A
STRICT N/A

+++ TESTING 19th COMBINATION out of 210 possible combinations of 6 items +++
Items to test: ('hitop1', 'hitop17', 'hitop114', 'hitop124', 'hitop129', 'hitop258')

 -----> VALID VS GENPOP <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG INVARIANT NOT PASSED, chisq p = 0
METRIC N/A
SCALAR N/A
STRICT N/A

 -----> VALID VS ENRICHED <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG INVARIANT NOT PASSED, chisq p = 0.011
METRIC N/A
SCALAR N/A
STRICT N/A

 -----> GENPOP VS ENRICHED <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG chisq p = 0.039
PASSED SECONDARY CRITERIA WITH CFI = 0.996 TLI = 0.993 RMSEA = 0.043

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT chisq p = 0.426
SCALAR N/A
STRICT N/A

+++ TESTING 20th COMBINATION out of 210 possible combinations of 6 items +++
Items to test: ('hitop1', 'hitop17', 'hitop114', 'hitop124', 'hitop204', 'hitop222')

 -----> VALID VS GENPOP <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG chisq p = 0
PASSED SECONDARY CRITERIA WITH CFI = 0.993 TLI = 0.989 RMSEA = 0.056

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT NOT PASSED, chisq p = 0.004
SCALAR N/A
STRICT N/A

 -----> VALID VS ENRICHED <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG INVARIANT chisq p = 0.171

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT NOT PASSED, chisq p = 0.032
SCALAR N/A
STRICT N/A

 -----> GENPOP VS ENRICHED <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG INVARIANT chisq p = 0.359

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT chisq p = 0.122
SCALAR N/A
STRICT N/A

+++ TESTING 21th COMBINATION out of 210 possible combinations of 6 items +++
Items to test: ('hitop1', 'hitop17', 'hitop114', 'hitop124', 'hitop204', 'hitop236')

 -----> VALID VS GENPOP <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG chisq p = 0
PASSED SECONDARY CRITERIA WITH CFI = 0.995 TLI = 0.991 RMSEA = 0.05

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT NOT PASSED, chisq p = 0.002
SCALAR N/A
STRICT N/A

 -----> VALID VS ENRICHED <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG chisq p = 0.023
PASSED SECONDARY CRITERIA WITH CFI = 0.998 TLI = 0.996 RMSEA = 0.055

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT NOT PASSED, chisq p = 0.039
SCALAR N/A
STRICT N/A

 -----> GENPOP VS ENRICHED <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG INVARIANT chisq p = 0.137

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT NOT PASSED, chisq p = 0.011
SCALAR N/A
STRICT N/A

+++ TESTING 22th COMBINATION out of 210 possible combinations of 6 items +++
Items to test: ('hitop1', 'hitop17', 'hitop114', 'hitop124', 'hitop204', 'hitop258')

 -----> VALID VS GENPOP <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG chisq p = 0
PASSED SECONDARY CRITERIA WITH CFI = 0.998 TLI = 0.997 RMSEA = 0.05

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT NOT PASSED, chisq p = 0.002
SCALAR N/A
STRICT N/A

 -----> VALID VS ENRICHED <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG chisq p = 0.012
PASSED SECONDARY CRITERIA WITH CFI = 0.995 TLI = 0.992 RMSEA = 0.054

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT chisq p = 0.076
SCALAR N/A
STRICT N/A

 -----> GENPOP VS ENRICHED <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG INVARIANT chisq p = 0.193

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT chisq p = 0.221
SCALAR N/A
STRICT N/A

+++ TESTING 23th COMBINATION out of 210 possible combinations of 6 items +++
Items to test: ('hitop1', 'hitop17', 'hitop114', 'hitop124', 'hitop222', 'hitop236')

 -----> VALID VS GENPOP <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG chisq p = 0
PASSED SECONDARY CRITERIA WITH CFI = 0.994 TLI = 0.99 RMSEA = 0.053

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT NOT PASSED, chisq p = 0.002
SCALAR N/A
STRICT N/A

 -----> VALID VS ENRICHED <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG INVARIANT NOT PASSED, chisq p = 0.014
METRIC N/A
SCALAR N/A
STRICT N/A

 -----> GENPOP VS ENRICHED <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG INVARIANT chisq p = 0.124

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT NOT PASSED, chisq p = 0.005
SCALAR N/A
STRICT N/A

+++ TESTING 24th COMBINATION out of 210 possible combinations of 6 items +++
Items to test: ('hitop1', 'hitop17', 'hitop114', 'hitop124', 'hitop222', 'hitop258')

 -----> VALID VS GENPOP <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG chisq p = 0
PASSED SECONDARY CRITERIA WITH CFI = 0.995 TLI = 0.991 RMSEA = 0.051

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT NOT PASSED, chisq p = 0
SCALAR N/A
STRICT N/A

 -----> VALID VS ENRICHED <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG INVARIANT chisq p = 0.067

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT NOT PASSED, chisq p = 0.015
SCALAR N/A
STRICT N/A

 -----> GENPOP VS ENRICHED <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG chisq p = 0.035
PASSED SECONDARY CRITERIA WITH CFI = 0.999 TLI = 0.998 RMSEA = 0.022

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT chisq p = 0.199
SCALAR N/A
STRICT N/A

+++ TESTING 25th COMBINATION out of 210 possible combinations of 6 items +++
Items to test: ('hitop1', 'hitop17', 'hitop114', 'hitop124', 'hitop236', 'hitop258')

 -----> VALID VS GENPOP <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG chisq p = 0
PASSED SECONDARY CRITERIA WITH CFI = 0.999 TLI = 0.999 RMSEA = 0.043

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT NOT PASSED, chisq p = 0
SCALAR N/A
STRICT N/A

 -----> VALID VS ENRICHED <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG chisq p = 0.013
PASSED SECONDARY CRITERIA WITH CFI = 0.999 TLI = 0.998 RMSEA = 0.049

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT NOT PASSED, chisq p = 0.014
SCALAR N/A
STRICT N/A

 -----> GENPOP VS ENRICHED <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG INVARIANT chisq p = 0.215

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT NOT PASSED, chisq p = 0.02
SCALAR N/A
STRICT N/A

+++ TESTING 26th COMBINATION out of 210 possible combinations of 6 items +++
Items to test: ('hitop1', 'hitop17', 'hitop114', 'hitop129', 'hitop204', 'hitop222')

 -----> VALID VS GENPOP <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG chisq p = 0
PASSED SECONDARY CRITERIA WITH CFI = 0.995 TLI = 0.991 RMSEA = 0.046

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT NOT PASSED, chisq p = 0.025
SCALAR N/A
STRICT N/A

 -----> VALID VS ENRICHED <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG INVARIANT chisq p = 0.066

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT NOT PASSED, chisq p = 0.017
SCALAR N/A
STRICT N/A

 -----> GENPOP VS ENRICHED <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG INVARIANT chisq p = 0.243

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT chisq p = 0.191
SCALAR N/A
STRICT N/A

+++ TESTING 27th COMBINATION out of 210 possible combinations of 6 items +++
Items to test: ('hitop1', 'hitop17', 'hitop114', 'hitop129', 'hitop204', 'hitop236')

 -----> VALID VS GENPOP <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG chisq p = 0.015
PASSED SECONDARY CRITERIA WITH CFI = 0.996 TLI = 0.993 RMSEA = 0.042

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT NOT PASSED, chisq p = 0.007
SCALAR N/A
STRICT N/A

 -----> VALID VS ENRICHED <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG chisq p = 0.031
PASSED SECONDARY CRITERIA WITH CFI = 0.997 TLI = 0.995 RMSEA = 0.038

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT NOT PASSED, chisq p = 0.029
SCALAR N/A
STRICT N/A

 -----> GENPOP VS ENRICHED <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG INVARIANT chisq p = 0.151

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT NOT PASSED, chisq p = 0.013
SCALAR N/A
STRICT N/A

+++ TESTING 28th COMBINATION out of 210 possible combinations of 6 items +++
Items to test: ('hitop1', 'hitop17', 'hitop114', 'hitop129', 'hitop204', 'hitop258')

 -----> VALID VS GENPOP <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG INVARIANT chisq p = 0.138

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT chisq p = 0.067
SCALAR N/A
STRICT N/A

 -----> VALID VS ENRICHED <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG INVARIANT chisq p = 0.06

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT chisq p = 0.066
SCALAR N/A
STRICT N/A

 -----> GENPOP VS ENRICHED <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG INVARIANT chisq p = 0.167

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT chisq p = 0.255
SCALAR N/A
STRICT N/A
Combination 28 passes 3-way invariance!

+++ TESTING 29th COMBINATION out of 210 possible combinations of 6 items +++
Items to test: ('hitop1', 'hitop17', 'hitop114', 'hitop129', 'hitop222', 'hitop236')

 -----> VALID VS GENPOP <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG chisq p = 0
PASSED SECONDARY CRITERIA WITH CFI = 0.996 TLI = 0.993 RMSEA = 0.043

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT NOT PASSED, chisq p = 0.005
SCALAR N/A
STRICT N/A

 -----> VALID VS ENRICHED <-----
CONFIG chisq p = 0.001
PASSED SECONDARY CRITERIA WITH CFI = 0.995 TLI = 0.992 RMSEA = 0.051

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT NOT PASSED, chisq p = 0.009
SCALAR N/A
STRICT N/A

 -----> GENPOP VS ENRICHED <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG INVARIANT chisq p = 0.236

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT NOT PASSED, chisq p = 0.022
SCALAR N/A
STRICT N/A

+++ TESTING 30th COMBINATION out of 210 possible combinations of 6 items +++
Items to test: ('hitop1', 'hitop17', 'hitop114', 'hitop129', 'hitop222', 'hitop258')

 -----> VALID VS GENPOP <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG chisq p = 0
PASSED SECONDARY CRITERIA WITH CFI = 0.998 TLI = 0.996 RMSEA = 0.051

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT NOT PASSED, chisq p = 0.006
SCALAR N/A
STRICT N/A

 -----> VALID VS ENRICHED <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG chisq p = 0.015
PASSED SECONDARY CRITERIA WITH CFI = 0.998 TLI = 0.997 RMSEA = 0.052

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT NOT PASSED, chisq p = 0.014
SCALAR N/A
STRICT N/A

 -----> GENPOP VS ENRICHED <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG INVARIANT chisq p = 0.181

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT chisq p = 0.544
SCALAR N/A
STRICT N/A

+++ TESTING 31th COMBINATION out of 210 possible combinations of 6 items +++
Items to test: ('hitop1', 'hitop17', 'hitop114', 'hitop129', 'hitop236', 'hitop258')

 -----> VALID VS GENPOP <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG chisq p = 0.013
PASSED SECONDARY CRITERIA WITH CFI = 0.999 TLI = 0.998 RMSEA = 0.046

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT NOT PASSED, chisq p = 0.001
SCALAR N/A
STRICT N/A

 -----> VALID VS ENRICHED <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG chisq p = 0.004
PASSED SECONDARY CRITERIA WITH CFI = 0.999 TLI = 0.998 RMSEA = 0.048

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT NOT PASSED, chisq p = 0.016
SCALAR N/A
STRICT N/A

 -----> GENPOP VS ENRICHED <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG INVARIANT chisq p = 0.117

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT chisq p = 0.056
SCALAR N/A
STRICT N/A

+++ TESTING 32th COMBINATION out of 210 possible combinations of 6 items +++
Items to test: ('hitop1', 'hitop17', 'hitop114', 'hitop204', 'hitop222', 'hitop236')

 -----> VALID VS GENPOP <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG chisq p = 0
PASSED SECONDARY CRITERIA WITH CFI = 0.996 TLI = 0.993 RMSEA = 0.045

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT NOT PASSED, chisq p = 0.007
SCALAR N/A
STRICT N/A

 -----> VALID VS ENRICHED <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG chisq p = 0.001
PASSED SECONDARY CRITERIA WITH CFI = 0.999 TLI = 0.998 RMSEA = 0.049

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT NOT PASSED, chisq p = 0.006
SCALAR N/A
STRICT N/A

 -----> GENPOP VS ENRICHED <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG INVARIANT chisq p = 0.134

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT NOT PASSED, chisq p = 0.001
SCALAR N/A
STRICT N/A

+++ TESTING 33th COMBINATION out of 210 possible combinations of 6 items +++
Items to test: ('hitop1', 'hitop17', 'hitop114', 'hitop204', 'hitop222', 'hitop258')

 -----> VALID VS GENPOP <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG chisq p = 0
PASSED SECONDARY CRITERIA WITH CFI = 0.996 TLI = 0.994 RMSEA = 0.042

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT NOT PASSED, chisq p = 0.008
SCALAR N/A
STRICT N/A

 -----> VALID VS ENRICHED <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG chisq p = 0.046
PASSED SECONDARY CRITERIA WITH CFI = 1.0 TLI = 0.999 RMSEA = 0.045

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT NOT PASSED, chisq p = 0.029
SCALAR N/A
STRICT N/A

 -----> GENPOP VS ENRICHED <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG INVARIANT chisq p = 0.317

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT chisq p = 0.287
SCALAR N/A
STRICT N/A

+++ TESTING 34th COMBINATION out of 210 possible combinations of 6 items +++
Items to test: ('hitop1', 'hitop17', 'hitop114', 'hitop204', 'hitop236', 'hitop258')

 -----> VALID VS GENPOP <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG chisq p = 0.003
PASSED SECONDARY CRITERIA WITH CFI = 1.0 TLI = 1.0 RMSEA = 0.038

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT NOT PASSED, chisq p = 0.003
SCALAR N/A
STRICT N/A

 -----> VALID VS ENRICHED <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG chisq p = 0.018
PASSED SECONDARY CRITERIA WITH CFI = 1.0 TLI = 1.001 RMSEA = 0.04

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT NOT PASSED, chisq p = 0.044
SCALAR N/A
STRICT N/A

 -----> GENPOP VS ENRICHED <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG INVARIANT chisq p = 0.104

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT NOT PASSED, chisq p = 0.005
SCALAR N/A
STRICT N/A

+++ TESTING 35th COMBINATION out of 210 possible combinations of 6 items +++
Items to test: ('hitop1', 'hitop17', 'hitop114', 'hitop222', 'hitop236', 'hitop258')

 -----> VALID VS GENPOP <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG chisq p = 0
PASSED SECONDARY CRITERIA WITH CFI = 0.996 TLI = 0.993 RMSEA = 0.044

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT NOT PASSED, chisq p = 0
SCALAR N/A
STRICT N/A

 -----> VALID VS ENRICHED <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG chisq p = 0
PASSED SECONDARY CRITERIA WITH CFI = 0.999 TLI = 0.998 RMSEA = 0.052

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT NOT PASSED, chisq p = 0.003
SCALAR N/A
STRICT N/A

 -----> GENPOP VS ENRICHED <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG INVARIANT chisq p = 0.128

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT NOT PASSED, chisq p = 0.005
SCALAR N/A
STRICT N/A

+++ TESTING 36th COMBINATION out of 210 possible combinations of 6 items +++
Items to test: ('hitop1', 'hitop17', 'hitop117', 'hitop124', 'hitop129', 'hitop204')

 -----> VALID VS GENPOP <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG INVARIANT chisq p = 0.144

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT NOT PASSED, chisq p = 0.023
SCALAR N/A
STRICT N/A

 -----> VALID VS ENRICHED <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG INVARIANT chisq p = 0.945

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT NOT PASSED, chisq p = 0.039
SCALAR N/A
STRICT N/A

 -----> GENPOP VS ENRICHED <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG INVARIANT chisq p = 0.149

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT NOT PASSED, chisq p = 0.03
SCALAR N/A
STRICT N/A

+++ TESTING 37th COMBINATION out of 210 possible combinations of 6 items +++
Items to test: ('hitop1', 'hitop17', 'hitop117', 'hitop124', 'hitop129', 'hitop222')

 -----> VALID VS GENPOP <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG INVARIANT NOT PASSED, chisq p = 0
METRIC N/A
SCALAR N/A
STRICT N/A

 -----> VALID VS ENRICHED <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG INVARIANT chisq p = 0.998

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT NOT PASSED, chisq p = 0.014
SCALAR N/A
STRICT N/A

 -----> GENPOP VS ENRICHED <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG INVARIANT chisq p = 0.662

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT NOT PASSED, chisq p = 0.004
SCALAR N/A
STRICT N/A

+++ TESTING 38th COMBINATION out of 210 possible combinations of 6 items +++
Items to test: ('hitop1', 'hitop17', 'hitop117', 'hitop124', 'hitop129', 'hitop236')

 -----> VALID VS GENPOP <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG INVARIANT NOT PASSED, chisq p = 0.003
METRIC N/A
SCALAR N/A
STRICT N/A

 -----> VALID VS ENRICHED <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG INVARIANT chisq p = 0.102

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT chisq p = 0.065
SCALAR N/A
STRICT N/A

 -----> GENPOP VS ENRICHED <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG chisq p = 0.032
PASSED SECONDARY CRITERIA WITH CFI = 1.0 TLI = 0.999 RMSEA = 0.046

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT chisq p = 0.051
SCALAR N/A
STRICT N/A

+++ TESTING 39th COMBINATION out of 210 possible combinations of 6 items +++
Items to test: ('hitop1', 'hitop17', 'hitop117', 'hitop124', 'hitop129', 'hitop258')

 -----> VALID VS GENPOP <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG INVARIANT chisq p = 0.092

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT NOT PASSED, chisq p = 0.004
SCALAR N/A
STRICT N/A

 -----> VALID VS ENRICHED <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG INVARIANT chisq p = 0.204

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT NOT PASSED, chisq p = 0.038
SCALAR N/A
STRICT N/A

 -----> GENPOP VS ENRICHED <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG chisq p = 0.038
PASSED SECONDARY CRITERIA WITH CFI = 0.996 TLI = 0.993 RMSEA = 0.047

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT NOT PASSED, chisq p = 0.008
SCALAR N/A
STRICT N/A

+++ TESTING 40th COMBINATION out of 210 possible combinations of 6 items +++
Items to test: ('hitop1', 'hitop17', 'hitop117', 'hitop124', 'hitop204', 'hitop222')

 -----> VALID VS GENPOP <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG chisq p = 0
PASSED SECONDARY CRITERIA WITH CFI = 0.994 TLI = 0.99 RMSEA = 0.056

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT NOT PASSED, chisq p = 0.045
SCALAR N/A
STRICT N/A

 -----> VALID VS ENRICHED <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG INVARIANT chisq p = 1

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT NOT PASSED, chisq p = 0.004
SCALAR N/A
STRICT N/A

 -----> GENPOP VS ENRICHED <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG INVARIANT chisq p = 0.837

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT NOT PASSED, chisq p = 0
SCALAR N/A
STRICT N/A

+++ TESTING 41th COMBINATION out of 210 possible combinations of 6 items +++
Items to test: ('hitop1', 'hitop17', 'hitop117', 'hitop124', 'hitop204', 'hitop236')

 -----> VALID VS GENPOP <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG chisq p = 0.012
PASSED SECONDARY CRITERIA WITH CFI = 0.996 TLI = 0.993 RMSEA = 0.049

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT NOT PASSED, chisq p = 0.033
SCALAR N/A
STRICT N/A

 -----> VALID VS ENRICHED <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG INVARIANT chisq p = 0.319

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT NOT PASSED, chisq p = 0.044
SCALAR N/A
STRICT N/A

 -----> GENPOP VS ENRICHED <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG chisq p = 0.024
PASSED SECONDARY CRITERIA WITH CFI = 0.998 TLI = 0.996 RMSEA = 0.036

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT NOT PASSED, chisq p = 0.025
SCALAR N/A
STRICT N/A

+++ TESTING 42th COMBINATION out of 210 possible combinations of 6 items +++
Items to test: ('hitop1', 'hitop17', 'hitop117', 'hitop124', 'hitop204', 'hitop258')

 -----> VALID VS GENPOP <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG INVARIANT chisq p = 0.081

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT NOT PASSED, chisq p = 0.001
SCALAR N/A
STRICT N/A

 -----> VALID VS ENRICHED <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG INVARIANT chisq p = 0.393

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT NOT PASSED, chisq p = 0.038
SCALAR N/A
STRICT N/A

 -----> GENPOP VS ENRICHED <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG INVARIANT chisq p = 0.129

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT NOT PASSED, chisq p = 0.003
SCALAR N/A
STRICT N/A

+++ TESTING 43th COMBINATION out of 210 possible combinations of 6 items +++
Items to test: ('hitop1', 'hitop17', 'hitop117', 'hitop124', 'hitop222', 'hitop236')

 -----> VALID VS GENPOP <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG chisq p = 0
PASSED SECONDARY CRITERIA WITH CFI = 0.995 TLI = 0.991 RMSEA = 0.055

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT chisq p = 0.105
SCALAR N/A
STRICT N/A

 -----> VALID VS ENRICHED <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG INVARIANT chisq p = 0.102

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT NOT PASSED, chisq p = 0.015
SCALAR N/A
STRICT N/A

 -----> GENPOP VS ENRICHED <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG INVARIANT chisq p = 0.157

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT NOT PASSED, chisq p = 0
SCALAR N/A
STRICT N/A

+++ TESTING 44th COMBINATION out of 210 possible combinations of 6 items +++
Items to test: ('hitop1', 'hitop17', 'hitop117', 'hitop124', 'hitop222', 'hitop258')

 -----> VALID VS GENPOP <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG chisq p = 0
PASSED SECONDARY CRITERIA WITH CFI = 0.998 TLI = 0.996 RMSEA = 0.054

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT NOT PASSED, chisq p = 0.003
SCALAR N/A
STRICT N/A

 -----> VALID VS ENRICHED <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG INVARIANT chisq p = 0.971

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT NOT PASSED, chisq p = 0.003
SCALAR N/A
STRICT N/A

 -----> GENPOP VS ENRICHED <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG INVARIANT chisq p = 0.129

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT NOT PASSED, chisq p = 0
SCALAR N/A
STRICT N/A

+++ TESTING 45th COMBINATION out of 210 possible combinations of 6 items +++
Items to test: ('hitop1', 'hitop17', 'hitop117', 'hitop124', 'hitop236', 'hitop258')

 -----> VALID VS GENPOP <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG chisq p = 0
PASSED SECONDARY CRITERIA WITH CFI = 1.0 TLI = 0.999 RMSEA = 0.043

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT NOT PASSED, chisq p = 0.001
SCALAR N/A
STRICT N/A

 -----> VALID VS ENRICHED <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG chisq p = 0.048
PASSED SECONDARY CRITERIA WITH CFI = 0.996 TLI = 0.993 RMSEA = 0.052

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT NOT PASSED, chisq p = 0.03
SCALAR N/A
STRICT N/A

 -----> GENPOP VS ENRICHED <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG chisq p = 0.024
PASSED SECONDARY CRITERIA WITH CFI = 0.999 TLI = 0.998 RMSEA = 0.024

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT NOT PASSED, chisq p = 0.008
SCALAR N/A
STRICT N/A

+++ TESTING 46th COMBINATION out of 210 possible combinations of 6 items +++
Items to test: ('hitop1', 'hitop17', 'hitop117', 'hitop129', 'hitop204', 'hitop222')

 -----> VALID VS GENPOP <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG chisq p = 0.007
PASSED SECONDARY CRITERIA WITH CFI = 0.995 TLI = 0.992 RMSEA = 0.049

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT chisq p = 0.054
SCALAR N/A
STRICT N/A

 -----> VALID VS ENRICHED <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG INVARIANT chisq p = 0.289

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT NOT PASSED, chisq p = 0.004
SCALAR N/A
STRICT N/A

 -----> GENPOP VS ENRICHED <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG INVARIANT chisq p = 0.223

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT NOT PASSED, chisq p = 0.001
SCALAR N/A
STRICT N/A

+++ TESTING 47th COMBINATION out of 210 possible combinations of 6 items +++
Items to test: ('hitop1', 'hitop17', 'hitop117', 'hitop129', 'hitop204', 'hitop236')

 -----> VALID VS GENPOP <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG INVARIANT chisq p = 0.071

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT NOT PASSED, chisq p = 0.01
SCALAR N/A
STRICT N/A

 -----> VALID VS ENRICHED <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG chisq p = 0.024
PASSED SECONDARY CRITERIA WITH CFI = 0.996 TLI = 0.993 RMSEA = 0.047

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT chisq p = 0.091
SCALAR N/A
STRICT N/A

 -----> GENPOP VS ENRICHED <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG chisq p = 0.021
PASSED SECONDARY CRITERIA WITH CFI = 1.0 TLI = 1.001 RMSEA = 0.039

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT NOT PASSED, chisq p = 0.045
SCALAR N/A
STRICT N/A

+++ TESTING 48th COMBINATION out of 210 possible combinations of 6 items +++
Items to test: ('hitop1', 'hitop17', 'hitop117', 'hitop129', 'hitop204', 'hitop258')

 -----> VALID VS GENPOP <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG INVARIANT chisq p = 0.996

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT NOT PASSED, chisq p = 0.012
SCALAR N/A
STRICT N/A

 -----> VALID VS ENRICHED <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG INVARIANT chisq p = 0.258

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT chisq p = 0.09
SCALAR N/A
STRICT N/A

 -----> GENPOP VS ENRICHED <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG INVARIANT chisq p = 0.185

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT NOT PASSED, chisq p = 0.003
SCALAR N/A
STRICT N/A

+++ TESTING 49th COMBINATION out of 210 possible combinations of 6 items +++
Items to test: ('hitop1', 'hitop17', 'hitop117', 'hitop129', 'hitop222', 'hitop236')

 -----> VALID VS GENPOP <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG chisq p = 0
PASSED SECONDARY CRITERIA WITH CFI = 0.996 TLI = 0.993 RMSEA = 0.047

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT NOT PASSED, chisq p = 0.032
SCALAR N/A
STRICT N/A

 -----> VALID VS ENRICHED <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG chisq p = 0.001
PASSED SECONDARY CRITERIA WITH CFI = 0.997 TLI = 0.996 RMSEA = 0.057

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT NOT PASSED, chisq p = 0.018
SCALAR N/A
STRICT N/A

 -----> GENPOP VS ENRICHED <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG INVARIANT chisq p = 0.102

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT NOT PASSED, chisq p = 0.009
SCALAR N/A
STRICT N/A

+++ TESTING 50th COMBINATION out of 210 possible combinations of 6 items +++
Items to test: ('hitop1', 'hitop17', 'hitop117', 'hitop129', 'hitop222', 'hitop258')

 -----> VALID VS GENPOP <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG chisq p = 0.005
PASSED SECONDARY CRITERIA WITH CFI = 0.993 TLI = 0.989 RMSEA = 0.059

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT NOT PASSED, chisq p = 0.008
SCALAR N/A
STRICT N/A

 -----> VALID VS ENRICHED <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG INVARIANT chisq p = 0.143

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT NOT PASSED, chisq p = 0.005
SCALAR N/A
STRICT N/A

 -----> GENPOP VS ENRICHED <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG INVARIANT chisq p = 0.273

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT NOT PASSED, chisq p = 0
SCALAR N/A
STRICT N/A

+++ TESTING 51th COMBINATION out of 210 possible combinations of 6 items +++
Items to test: ('hitop1', 'hitop17', 'hitop117', 'hitop129', 'hitop236', 'hitop258')

 -----> VALID VS GENPOP <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG chisq p = 0.022
PASSED SECONDARY CRITERIA WITH CFI = 0.998 TLI = 0.996 RMSEA = 0.054

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT NOT PASSED, chisq p = 0.002
SCALAR N/A
STRICT N/A

 -----> VALID VS ENRICHED <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG INVARIANT NOT PASSED, chisq p = 0.006
METRIC N/A
SCALAR N/A
STRICT N/A

 -----> GENPOP VS ENRICHED <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG chisq p = 0.045
PASSED SECONDARY CRITERIA WITH CFI = 1.0 TLI = 1.0 RMSEA = 0.043

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT NOT PASSED, chisq p = 0.011
SCALAR N/A
STRICT N/A

+++ TESTING 52th COMBINATION out of 210 possible combinations of 6 items +++
Items to test: ('hitop1', 'hitop17', 'hitop117', 'hitop204', 'hitop222', 'hitop236')

 -----> VALID VS GENPOP <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG chisq p = 0
PASSED SECONDARY CRITERIA WITH CFI = 0.996 TLI = 0.994 RMSEA = 0.045

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT NOT PASSED, chisq p = 0.046
SCALAR N/A
STRICT N/A

 -----> VALID VS ENRICHED <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG chisq p = 0.001
PASSED SECONDARY CRITERIA WITH CFI = 0.996 TLI = 0.993 RMSEA = 0.051

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT NOT PASSED, chisq p = 0.006
SCALAR N/A
STRICT N/A

 -----> GENPOP VS ENRICHED <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG chisq p = 0.013
PASSED SECONDARY CRITERIA WITH CFI = 0.998 TLI = 0.997 RMSEA = 0.032

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT NOT PASSED, chisq p = 0.001
SCALAR N/A
STRICT N/A

+++ TESTING 53th COMBINATION out of 210 possible combinations of 6 items +++
Items to test: ('hitop1', 'hitop17', 'hitop117', 'hitop204', 'hitop222', 'hitop258')

 -----> VALID VS GENPOP <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG chisq p = 0.002
PASSED SECONDARY CRITERIA WITH CFI = 0.999 TLI = 0.999 RMSEA = 0.045

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT NOT PASSED, chisq p = 0.005
SCALAR N/A
STRICT N/A

 -----> VALID VS ENRICHED <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG INVARIANT chisq p = 0.388

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT NOT PASSED, chisq p = 0
SCALAR N/A
STRICT N/A

 -----> GENPOP VS ENRICHED <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG INVARIANT chisq p = 0.415

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT NOT PASSED, chisq p = 0
SCALAR N/A
STRICT N/A

+++ TESTING 54th COMBINATION out of 210 possible combinations of 6 items +++
Items to test: ('hitop1', 'hitop17', 'hitop117', 'hitop204', 'hitop236', 'hitop258')

 -----> VALID VS GENPOP <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG chisq p = 0.015
PASSED SECONDARY CRITERIA WITH CFI = 0.997 TLI = 0.996 RMSEA = 0.038

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT NOT PASSED, chisq p = 0.001
SCALAR N/A
STRICT N/A

 -----> VALID VS ENRICHED <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG chisq p = 0.013
PASSED SECONDARY CRITERIA WITH CFI = 1.0 TLI = 0.999 RMSEA = 0.047

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT chisq p = 0.09
SCALAR N/A
STRICT N/A

 -----> GENPOP VS ENRICHED <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG chisq p = 0.008
PASSED SECONDARY CRITERIA WITH CFI = 0.998 TLI = 0.997 RMSEA = 0.033

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT NOT PASSED, chisq p = 0.004
SCALAR N/A
STRICT N/A

+++ TESTING 55th COMBINATION out of 210 possible combinations of 6 items +++
Items to test: ('hitop1', 'hitop17', 'hitop117', 'hitop222', 'hitop236', 'hitop258')

 -----> VALID VS GENPOP <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG chisq p = 0
PASSED SECONDARY CRITERIA WITH CFI = 0.999 TLI = 0.998 RMSEA = 0.048

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT NOT PASSED, chisq p = 0
SCALAR N/A
STRICT N/A

 -----> VALID VS ENRICHED <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG chisq p = 0.001
PASSED SECONDARY CRITERIA WITH CFI = 0.995 TLI = 0.992 RMSEA = 0.059

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT NOT PASSED, chisq p = 0.003
SCALAR N/A
STRICT N/A

 -----> GENPOP VS ENRICHED <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG chisq p = 0.029
PASSED SECONDARY CRITERIA WITH CFI = 1.0 TLI = 1.003 RMSEA = 0.031

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT NOT PASSED, chisq p = 0
SCALAR N/A
STRICT N/A

+++ TESTING 56th COMBINATION out of 210 possible combinations of 6 items +++
Items to test: ('hitop1', 'hitop17', 'hitop124', 'hitop129', 'hitop204', 'hitop222')

 -----> VALID VS GENPOP <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG INVARIANT NOT PASSED, chisq p = 0
METRIC N/A
SCALAR N/A
STRICT N/A

 -----> VALID VS ENRICHED <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG INVARIANT chisq p = 0.939

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT NOT PASSED, chisq p = 0.012
SCALAR N/A
STRICT N/A

 -----> GENPOP VS ENRICHED <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG INVARIANT chisq p = 0.186

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT chisq p = 0.114
SCALAR N/A
STRICT N/A

+++ TESTING 57th COMBINATION out of 210 possible combinations of 6 items +++
Items to test: ('hitop1', 'hitop17', 'hitop124', 'hitop129', 'hitop204', 'hitop236')

 -----> VALID VS GENPOP <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG chisq p = 0.006
PASSED SECONDARY CRITERIA WITH CFI = 0.996 TLI = 0.993 RMSEA = 0.059

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT NOT PASSED, chisq p = 0.014
SCALAR N/A
STRICT N/A

 -----> VALID VS ENRICHED <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG INVARIANT chisq p = 0.177

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT NOT PASSED, chisq p = 0.009
SCALAR N/A
STRICT N/A

 -----> GENPOP VS ENRICHED <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG INVARIANT chisq p = 0.072

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT NOT PASSED, chisq p = 0.015
SCALAR N/A
STRICT N/A

+++ TESTING 58th COMBINATION out of 210 possible combinations of 6 items +++
Items to test: ('hitop1', 'hitop17', 'hitop124', 'hitop129', 'hitop204', 'hitop258')

 -----> VALID VS GENPOP <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG INVARIANT chisq p = 0.05

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT NOT PASSED, chisq p = 0.015
SCALAR N/A
STRICT N/A

 -----> VALID VS ENRICHED <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG INVARIANT chisq p = 0.132

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT NOT PASSED, chisq p = 0.038
SCALAR N/A
STRICT N/A

 -----> GENPOP VS ENRICHED <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG INVARIANT chisq p = 0.05

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT chisq p = 0.177
SCALAR N/A
STRICT N/A

+++ TESTING 59th COMBINATION out of 210 possible combinations of 6 items +++
Items to test: ('hitop1', 'hitop17', 'hitop124', 'hitop129', 'hitop222', 'hitop236')

 -----> VALID VS GENPOP <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG INVARIANT NOT PASSED, chisq p = 0
METRIC N/A
SCALAR N/A
STRICT N/A

 -----> VALID VS ENRICHED <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG INVARIANT chisq p = 0.068

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT NOT PASSED, chisq p = 0.002
SCALAR N/A
STRICT N/A

 -----> GENPOP VS ENRICHED <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG INVARIANT chisq p = 0.249

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT NOT PASSED, chisq p = 0.006
SCALAR N/A
STRICT N/A

+++ TESTING 60th COMBINATION out of 210 possible combinations of 6 items +++
Items to test: ('hitop1', 'hitop17', 'hitop124', 'hitop129', 'hitop222', 'hitop258')

 -----> VALID VS GENPOP <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG INVARIANT NOT PASSED, chisq p = 0
METRIC N/A
SCALAR N/A
STRICT N/A

 -----> VALID VS ENRICHED <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG INVARIANT chisq p = 0.449

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT NOT PASSED, chisq p = 0.005
SCALAR N/A
STRICT N/A

 -----> GENPOP VS ENRICHED <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG chisq p = 0.034
PASSED SECONDARY CRITERIA WITH CFI = 0.997 TLI = 0.996 RMSEA = 0.036

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT chisq p = 0.189
SCALAR N/A
STRICT N/A

+++ TESTING 61th COMBINATION out of 210 possible combinations of 6 items +++
Items to test: ('hitop1', 'hitop17', 'hitop124', 'hitop129', 'hitop236', 'hitop258')

 -----> VALID VS GENPOP <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG INVARIANT NOT PASSED, chisq p = 0.008
METRIC N/A
SCALAR N/A
STRICT N/A

 -----> VALID VS ENRICHED <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG INVARIANT NOT PASSED, chisq p = 0.045
METRIC N/A
SCALAR N/A
STRICT N/A

 -----> GENPOP VS ENRICHED <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG INVARIANT chisq p = 0.088

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT NOT PASSED, chisq p = 0.019
SCALAR N/A
STRICT N/A

+++ TESTING 62th COMBINATION out of 210 possible combinations of 6 items +++
Items to test: ('hitop1', 'hitop17', 'hitop124', 'hitop204', 'hitop222', 'hitop236')

 -----> VALID VS GENPOP <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG chisq p = 0
PASSED SECONDARY CRITERIA WITH CFI = 0.994 TLI = 0.99 RMSEA = 0.055

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT NOT PASSED, chisq p = 0.043
SCALAR N/A
STRICT N/A

 -----> VALID VS ENRICHED <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG INVARIANT chisq p = 0.123

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT NOT PASSED, chisq p = 0.002
SCALAR N/A
STRICT N/A

 -----> GENPOP VS ENRICHED <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG INVARIANT chisq p = 0.205

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT NOT PASSED, chisq p = 0
SCALAR N/A
STRICT N/A

+++ TESTING 63th COMBINATION out of 210 possible combinations of 6 items +++
Items to test: ('hitop1', 'hitop17', 'hitop124', 'hitop204', 'hitop222', 'hitop258')

 -----> VALID VS GENPOP <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG chisq p = 0
PASSED SECONDARY CRITERIA WITH CFI = 0.994 TLI = 0.99 RMSEA = 0.054

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT NOT PASSED, chisq p = 0.005
SCALAR N/A
STRICT N/A

 -----> VALID VS ENRICHED <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG INVARIANT chisq p = 0.627

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT NOT PASSED, chisq p = 0.014
SCALAR N/A
STRICT N/A

 -----> GENPOP VS ENRICHED <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG INVARIANT chisq p = 0.162
METRIC INVARIANT chisq p = 0.074
SCALAR N/A
STRICT N/A

+++ TESTING 64th COMBINATION out of 210 possible combinations of 6 items +++
Items to test: ('hitop1', 'hitop17', 'hitop124', 'hitop204', 'hitop236', 'hitop258')

 -----> VALID VS GENPOP <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG chisq p = 0.002
PASSED SECONDARY CRITERIA WITH CFI = 0.996 TLI = 0.993 RMSEA = 0.047

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT NOT PASSED, chisq p = 0.002
SCALAR N/A
STRICT N/A

 -----> VALID VS ENRICHED <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG INVARIANT chisq p = 0.066

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT NOT PASSED, chisq p = 0.01
SCALAR N/A
STRICT N/A

 -----> GENPOP VS ENRICHED <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG INVARIANT chisq p = 0.163

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT NOT PASSED, chisq p = 0.004
SCALAR N/A
STRICT N/A

+++ TESTING 65th COMBINATION out of 210 possible combinations of 6 items +++
Items to test: ('hitop1', 'hitop17', 'hitop124', 'hitop222', 'hitop236', 'hitop258')

 -----> VALID VS GENPOP <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG chisq p = 0
PASSED SECONDARY CRITERIA WITH CFI = 0.998 TLI = 0.997 RMSEA = 0.051

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT NOT PASSED, chisq p = 0
SCALAR N/A
STRICT N/A

 -----> VALID VS ENRICHED <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG INVARIANT chisq p = 0.07

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT NOT PASSED, chisq p = 0.001
SCALAR N/A
STRICT N/A

 -----> GENPOP VS ENRICHED <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG INVARIANT chisq p = 0.145

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT NOT PASSED, chisq p = 0.001
SCALAR N/A
STRICT N/A

+++ TESTING 66th COMBINATION out of 210 possible combinations of 6 items +++
Items to test: ('hitop1', 'hitop17', 'hitop129', 'hitop204', 'hitop222', 'hitop236')

 -----> VALID VS GENPOP <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG chisq p = 0
PASSED SECONDARY CRITERIA WITH CFI = 0.998 TLI = 0.996 RMSEA = 0.05

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT chisq p = 0.056
SCALAR N/A
STRICT N/A

 -----> VALID VS ENRICHED <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG chisq p = 0.005
PASSED SECONDARY CRITERIA WITH CFI = 0.995 TLI = 0.992 RMSEA = 0.05

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT NOT PASSED, chisq p = 0.002
SCALAR N/A
STRICT N/A

 -----> GENPOP VS ENRICHED <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG INVARIANT chisq p = 0.066

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT NOT PASSED, chisq p = 0.005
SCALAR N/A
STRICT N/A

+++ TESTING 67th COMBINATION out of 210 possible combinations of 6 items +++
Items to test: ('hitop1', 'hitop17', 'hitop129', 'hitop204', 'hitop222', 'hitop258')

 -----> VALID VS GENPOP <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG chisq p = 0.002
PASSED SECONDARY CRITERIA WITH CFI = 0.998 TLI = 0.996 RMSEA = 0.052

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT chisq p = 0.072
SCALAR N/A
STRICT N/A

 -----> VALID VS ENRICHED <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG INVARIANT chisq p = 0.135

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT NOT PASSED, chisq p = 0.002
SCALAR N/A
STRICT N/A

 -----> GENPOP VS ENRICHED <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG INVARIANT chisq p = 0.115

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT chisq p = 0.133
SCALAR N/A
STRICT N/A

+++ TESTING 68th COMBINATION out of 210 possible combinations of 6 items +++
Items to test: ('hitop1', 'hitop17', 'hitop129', 'hitop204', 'hitop236', 'hitop258')

 -----> VALID VS GENPOP <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG chisq p = 0.041
PASSED SECONDARY CRITERIA WITH CFI = 0.998 TLI = 0.996 RMSEA = 0.051

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT NOT PASSED, chisq p = 0.012
SCALAR N/A
STRICT N/A

 -----> VALID VS ENRICHED <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG chisq p = 0.008
PASSED SECONDARY CRITERIA WITH CFI = 0.999 TLI = 0.998 RMSEA = 0.049

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT NOT PASSED, chisq p = 0.011
SCALAR N/A
STRICT N/A

 -----> GENPOP VS ENRICHED <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG INVARIANT chisq p = 0.146

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT NOT PASSED, chisq p = 0.006
SCALAR N/A
STRICT N/A

+++ TESTING 69th COMBINATION out of 210 possible combinations of 6 items +++
Items to test: ('hitop1', 'hitop17', 'hitop129', 'hitop222', 'hitop236', 'hitop258')

 -----> VALID VS GENPOP <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG chisq p = 0
PASSED SECONDARY CRITERIA WITH CFI = 0.994 TLI = 0.99 RMSEA = 0.053

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT NOT PASSED, chisq p = 0.002
SCALAR N/A
STRICT N/A

 -----> VALID VS ENRICHED <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG chisq p = 0.002
PASSED SECONDARY CRITERIA WITH CFI = 0.998 TLI = 0.996 RMSEA = 0.056

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT NOT PASSED, chisq p = 0
SCALAR N/A
STRICT N/A

 -----> GENPOP VS ENRICHED <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG INVARIANT chisq p = 0.226

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT NOT PASSED, chisq p = 0.008
SCALAR N/A
STRICT N/A

+++ TESTING 70th COMBINATION out of 210 possible combinations of 6 items +++
Items to test: ('hitop1', 'hitop17', 'hitop204', 'hitop222', 'hitop236', 'hitop258')

 -----> VALID VS GENPOP <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG chisq p = 0
PASSED SECONDARY CRITERIA WITH CFI = 0.996 TLI = 0.993 RMSEA = 0.046

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT NOT PASSED, chisq p = 0.005
SCALAR N/A
STRICT N/A

 -----> VALID VS ENRICHED <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG chisq p = 0.001
PASSED SECONDARY CRITERIA WITH CFI = 0.999 TLI = 0.998 RMSEA = 0.05

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT NOT PASSED, chisq p = 0
SCALAR N/A
STRICT N/A

 -----> GENPOP VS ENRICHED <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG INVARIANT chisq p = 0.208

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT NOT PASSED, chisq p = 0.001
SCALAR N/A
STRICT N/A

+++ TESTING 71th COMBINATION out of 210 possible combinations of 6 items +++
Items to test: ('hitop1', 'hitop114', 'hitop117', 'hitop124', 'hitop129', 'hitop204')

 -----> VALID VS GENPOP <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG INVARIANT chisq p = 0.958

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT NOT PASSED, chisq p = 0
SCALAR N/A
STRICT N/A

 -----> VALID VS ENRICHED <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG INVARIANT chisq p = 0.548

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT NOT PASSED, chisq p = 0.038
SCALAR N/A
STRICT N/A

 -----> GENPOP VS ENRICHED <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG chisq p = 0.033
PASSED SECONDARY CRITERIA WITH CFI = 0.996 TLI = 0.994 RMSEA = 0.058

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT chisq p = 0.164
SCALAR N/A
STRICT N/A

+++ TESTING 72th COMBINATION out of 210 possible combinations of 6 items +++
Items to test: ('hitop1', 'hitop114', 'hitop117', 'hitop124', 'hitop129', 'hitop222')

 -----> VALID VS GENPOP <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG INVARIANT chisq p = 1

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT NOT PASSED, chisq p = 0
SCALAR N/A
STRICT N/A

 -----> VALID VS ENRICHED <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG INVARIANT chisq p = 0.909

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT NOT PASSED, chisq p = 0.022
SCALAR N/A
STRICT N/A

 -----> GENPOP VS ENRICHED <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG INVARIANT chisq p = 0.076

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT NOT PASSED, chisq p = 0.026
SCALAR N/A
STRICT N/A

+++ TESTING 73th COMBINATION out of 210 possible combinations of 6 items +++
Items to test: ('hitop1', 'hitop114', 'hitop117', 'hitop124', 'hitop129', 'hitop236')

 -----> VALID VS GENPOP <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG INVARIANT chisq p = 0.82

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT NOT PASSED, chisq p = 0
SCALAR N/A
STRICT N/A

 -----> VALID VS ENRICHED <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG INVARIANT chisq p = 0.201

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT NOT PASSED, chisq p = 0.015
SCALAR N/A
STRICT N/A

 -----> GENPOP VS ENRICHED <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG chisq p = 0.015
PASSED SECONDARY CRITERIA WITH CFI = 0.995 TLI = 0.991 RMSEA = 0.05

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT chisq p = 0.177
SCALAR N/A
STRICT N/A

+++ TESTING 74th COMBINATION out of 210 possible combinations of 6 items +++
Items to test: ('hitop1', 'hitop114', 'hitop117', 'hitop124', 'hitop129', 'hitop258')

 -----> VALID VS GENPOP <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG INVARIANT chisq p = 0.997

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT NOT PASSED, chisq p = 0
SCALAR N/A
STRICT N/A

 -----> VALID VS ENRICHED <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG INVARIANT chisq p = 0.477

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT NOT PASSED, chisq p = 0.015
SCALAR N/A
STRICT N/A

 -----> GENPOP VS ENRICHED <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG chisq p = 0.001
PASSED SECONDARY CRITERIA WITH CFI = 0.997 TLI = 0.995 RMSEA = 0.057

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT chisq p = 0.146
SCALAR N/A
STRICT N/A

+++ TESTING 75th COMBINATION out of 210 possible combinations of 6 items +++
Items to test: ('hitop1', 'hitop114', 'hitop117', 'hitop124', 'hitop204', 'hitop222')

 -----> VALID VS GENPOP <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG INVARIANT chisq p = 0.664

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT NOT PASSED, chisq p = 0
SCALAR N/A
STRICT N/A

 -----> VALID VS ENRICHED <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG INVARIANT chisq p = 0.845

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT NOT PASSED, chisq p = 0.015
SCALAR N/A
STRICT N/A

 -----> GENPOP VS ENRICHED <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG INVARIANT chisq p = 0.181

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT NOT PASSED, chisq p = 0.008
SCALAR N/A
STRICT N/A

+++ TESTING 76th COMBINATION out of 210 possible combinations of 6 items +++
Items to test: ('hitop1', 'hitop114', 'hitop117', 'hitop124', 'hitop204', 'hitop236')

 -----> VALID VS GENPOP <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG INVARIANT chisq p = 0.437

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT NOT PASSED, chisq p = 0.002
SCALAR N/A
STRICT N/A

 -----> VALID VS ENRICHED <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG INVARIANT chisq p = 0.198

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT NOT PASSED, chisq p = 0.026
SCALAR N/A
STRICT N/A

 -----> GENPOP VS ENRICHED <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG INVARIANT chisq p = 0.051

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT chisq p = 0.078
SCALAR N/A
STRICT N/A

+++ TESTING 77th COMBINATION out of 210 possible combinations of 6 items +++
Items to test: ('hitop1', 'hitop114', 'hitop117', 'hitop124', 'hitop204', 'hitop258')

 -----> VALID VS GENPOP <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG INVARIANT chisq p = 0.467

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT NOT PASSED, chisq p = 0
SCALAR N/A
STRICT N/A

 -----> VALID VS ENRICHED <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG INVARIANT chisq p = 0.228

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT NOT PASSED, chisq p = 0.026
SCALAR N/A
STRICT N/A

 -----> GENPOP VS ENRICHED <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG chisq p = 0.014
PASSED SECONDARY CRITERIA WITH CFI = 0.995 TLI = 0.992 RMSEA = 0.047

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT chisq p = 0.072
SCALAR N/A
STRICT N/A

+++ TESTING 78th COMBINATION out of 210 possible combinations of 6 items +++
Items to test: ('hitop1', 'hitop114', 'hitop117', 'hitop124', 'hitop222', 'hitop236')

 -----> VALID VS GENPOP <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG INVARIANT chisq p = 0.636

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT NOT PASSED, chisq p = 0
SCALAR N/A
STRICT N/A

 -----> VALID VS ENRICHED <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG INVARIANT chisq p = 0.348

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT NOT PASSED, chisq p = 0.017
SCALAR N/A
STRICT N/A

 -----> GENPOP VS ENRICHED <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG INVARIANT chisq p = 0.068

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT NOT PASSED, chisq p = 0.007
SCALAR N/A
STRICT N/A

+++ TESTING 79th COMBINATION out of 210 possible combinations of 6 items +++
Items to test: ('hitop1', 'hitop114', 'hitop117', 'hitop124', 'hitop222', 'hitop258')

 -----> VALID VS GENPOP <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG INVARIANT chisq p = 0.592

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT NOT PASSED, chisq p = 0
SCALAR N/A
STRICT N/A

 -----> VALID VS ENRICHED <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG INVARIANT chisq p = 0.941

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT NOT PASSED, chisq p = 0.003
SCALAR N/A
STRICT N/A

 -----> GENPOP VS ENRICHED <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG chisq p = 0.004
PASSED SECONDARY CRITERIA WITH CFI = 0.997 TLI = 0.995 RMSEA = 0.038

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT NOT PASSED, chisq p = 0.002
SCALAR N/A
STRICT N/A

+++ TESTING 80th COMBINATION out of 210 possible combinations of 6 items +++
Items to test: ('hitop1', 'hitop114', 'hitop117', 'hitop124', 'hitop236', 'hitop258')

 -----> VALID VS GENPOP <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG INVARIANT chisq p = 0.173

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT NOT PASSED, chisq p = 0
SCALAR N/A
STRICT N/A

 -----> VALID VS ENRICHED <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG INVARIANT chisq p = 0.357

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT NOT PASSED, chisq p = 0.004
SCALAR N/A
STRICT N/A

 -----> GENPOP VS ENRICHED <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG chisq p = 0.026
PASSED SECONDARY CRITERIA WITH CFI = 0.998 TLI = 0.997 RMSEA = 0.028

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT chisq p = 0.071
SCALAR N/A
STRICT N/A

+++ TESTING 81th COMBINATION out of 210 possible combinations of 6 items +++
Items to test: ('hitop1', 'hitop114', 'hitop117', 'hitop129', 'hitop204', 'hitop222')

 -----> VALID VS GENPOP <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG INVARIANT chisq p = 0.893

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT NOT PASSED, chisq p = 0
SCALAR N/A
STRICT N/A

 -----> VALID VS ENRICHED <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG INVARIANT chisq p = 0.706

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT NOT PASSED, chisq p = 0.009
SCALAR N/A
STRICT N/A

 -----> GENPOP VS ENRICHED <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG INVARIANT chisq p = 0.163

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT NOT PASSED, chisq p = 0.013
SCALAR N/A
STRICT N/A

+++ TESTING 82th COMBINATION out of 210 possible combinations of 6 items +++
Items to test: ('hitop1', 'hitop114', 'hitop117', 'hitop129', 'hitop204', 'hitop236')

 -----> VALID VS GENPOP <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG INVARIANT chisq p = 0.84

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT NOT PASSED, chisq p = 0.001
SCALAR N/A
STRICT N/A

 -----> VALID VS ENRICHED <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG INVARIANT chisq p = 0.391

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT NOT PASSED, chisq p = 0.008
SCALAR N/A
STRICT N/A

 -----> GENPOP VS ENRICHED <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG INVARIANT chisq p = 0.128

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT chisq p = 0.081
SCALAR N/A
STRICT N/A

+++ TESTING 83th COMBINATION out of 210 possible combinations of 6 items +++
Items to test: ('hitop1', 'hitop114', 'hitop117', 'hitop129', 'hitop204', 'hitop258')

 -----> VALID VS GENPOP <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG INVARIANT chisq p = 1

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT NOT PASSED, chisq p = 0
SCALAR N/A
STRICT N/A

 -----> VALID VS ENRICHED <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG INVARIANT chisq p = 0.57

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT NOT PASSED, chisq p = 0.029
SCALAR N/A
STRICT N/A

 -----> GENPOP VS ENRICHED <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG chisq p = 0.033
PASSED SECONDARY CRITERIA WITH CFI = 0.998 TLI = 0.997 RMSEA = 0.051

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT NOT PASSED, chisq p = 0.048
SCALAR N/A
STRICT N/A

+++ TESTING 84th COMBINATION out of 210 possible combinations of 6 items +++
Items to test: ('hitop1', 'hitop114', 'hitop117', 'hitop129', 'hitop222', 'hitop236')

 -----> VALID VS GENPOP <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG INVARIANT chisq p = 0.865

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT NOT PASSED, chisq p = 0
SCALAR N/A
STRICT N/A

 -----> VALID VS ENRICHED <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG INVARIANT chisq p = 0.096

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT NOT PASSED, chisq p = 0.011
SCALAR N/A
STRICT N/A

 -----> GENPOP VS ENRICHED <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG INVARIANT chisq p = 0.103

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT NOT PASSED, chisq p = 0.03
SCALAR N/A
STRICT N/A

+++ TESTING 85th COMBINATION out of 210 possible combinations of 6 items +++
Items to test: ('hitop1', 'hitop114', 'hitop117', 'hitop129', 'hitop222', 'hitop258')

 -----> VALID VS GENPOP <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG INVARIANT chisq p = 1

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT NOT PASSED, chisq p = 0
SCALAR N/A
STRICT N/A

 -----> VALID VS ENRICHED <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG INVARIANT chisq p = 0.734

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT NOT PASSED, chisq p = 0.008
SCALAR N/A
STRICT N/A

 -----> GENPOP VS ENRICHED <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG chisq p = 0.027
PASSED SECONDARY CRITERIA WITH CFI = 1.0 TLI = 1.0 RMSEA = 0.043

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT NOT PASSED, chisq p = 0.006
SCALAR N/A
STRICT N/A

+++ TESTING 86th COMBINATION out of 210 possible combinations of 6 items +++
Items to test: ('hitop1', 'hitop114', 'hitop117', 'hitop129', 'hitop236', 'hitop258')

 -----> VALID VS GENPOP <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG INVARIANT chisq p = 1

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT NOT PASSED, chisq p = 0
SCALAR N/A
STRICT N/A

 -----> VALID VS ENRICHED <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG INVARIANT chisq p = 0.232

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT NOT PASSED, chisq p = 0.002
SCALAR N/A
STRICT N/A

 -----> GENPOP VS ENRICHED <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG chisq p = 0.018
PASSED SECONDARY CRITERIA WITH CFI = 0.999 TLI = 0.999 RMSEA = 0.045

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT chisq p = 0.091
SCALAR N/A
STRICT N/A

+++ TESTING 87th COMBINATION out of 210 possible combinations of 6 items +++
Items to test: ('hitop1', 'hitop114', 'hitop117', 'hitop204', 'hitop222', 'hitop236')

 -----> VALID VS GENPOP <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG INVARIANT chisq p = 0.402

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT NOT PASSED, chisq p = 0.002
SCALAR N/A
STRICT N/A

 -----> VALID VS ENRICHED <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG INVARIANT chisq p = 0.056

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT NOT PASSED, chisq p = 0.01
SCALAR N/A
STRICT N/A

 -----> GENPOP VS ENRICHED <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG chisq p = 0.028
PASSED SECONDARY CRITERIA WITH CFI = 0.998 TLI = 0.997 RMSEA = 0.03

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT NOT PASSED, chisq p = 0.003
SCALAR N/A
STRICT N/A

+++ TESTING 88th COMBINATION out of 210 possible combinations of 6 items +++
Items to test: ('hitop1', 'hitop114', 'hitop117', 'hitop204', 'hitop222', 'hitop258')

 -----> VALID VS GENPOP <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG INVARIANT chisq p = 0.893

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT NOT PASSED, chisq p = 0
SCALAR N/A
STRICT N/A

 -----> VALID VS ENRICHED <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG INVARIANT chisq p = 0.503

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT NOT PASSED, chisq p = 0.006
SCALAR N/A
STRICT N/A

 -----> GENPOP VS ENRICHED <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG chisq p = 0.032
PASSED SECONDARY CRITERIA WITH CFI = 0.997 TLI = 0.996 RMSEA = 0.036

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT NOT PASSED, chisq p = 0.001
SCALAR N/A
STRICT N/A

+++ TESTING 89th COMBINATION out of 210 possible combinations of 6 items +++
Items to test: ('hitop1', 'hitop114', 'hitop117', 'hitop204', 'hitop236', 'hitop258')

 -----> VALID VS GENPOP <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG INVARIANT chisq p = 0.814

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT NOT PASSED, chisq p = 0
SCALAR N/A
STRICT N/A

 -----> VALID VS ENRICHED <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG INVARIANT chisq p = 0.097

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT NOT PASSED, chisq p = 0.011
SCALAR N/A
STRICT N/A

 -----> GENPOP VS ENRICHED <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG chisq p = 0.001
PASSED SECONDARY CRITERIA WITH CFI = 0.997 TLI = 0.995 RMSEA = 0.039

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT NOT PASSED, chisq p = 0.023
SCALAR N/A
STRICT N/A

+++ TESTING 90th COMBINATION out of 210 possible combinations of 6 items +++
Items to test: ('hitop1', 'hitop114', 'hitop117', 'hitop222', 'hitop236', 'hitop258')

 -----> VALID VS GENPOP <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG INVARIANT chisq p = 0.796

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT NOT PASSED, chisq p = 0
SCALAR N/A
STRICT N/A

 -----> VALID VS ENRICHED <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG INVARIANT chisq p = 0.08

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT NOT PASSED, chisq p = 0.001
SCALAR N/A
STRICT N/A

 -----> GENPOP VS ENRICHED <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG chisq p = 0.003
PASSED SECONDARY CRITERIA WITH CFI = 1.0 TLI = 1.003 RMSEA = 0.033

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT NOT PASSED, chisq p = 0.002
SCALAR N/A
STRICT N/A

+++ TESTING 91th COMBINATION out of 210 possible combinations of 6 items +++
Items to test: ('hitop1', 'hitop114', 'hitop124', 'hitop129', 'hitop204', 'hitop222')

 -----> VALID VS GENPOP <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG INVARIANT chisq p = 0.291

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT NOT PASSED, chisq p = 0
SCALAR N/A
STRICT N/A

 -----> VALID VS ENRICHED <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG INVARIANT chisq p = 0.884

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT NOT PASSED, chisq p = 0.007
SCALAR N/A
STRICT N/A

 -----> GENPOP VS ENRICHED <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG INVARIANT chisq p = 0.205

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT chisq p = 0.133
SCALAR N/A
STRICT N/A

+++ TESTING 92th COMBINATION out of 210 possible combinations of 6 items +++
Items to test: ('hitop1', 'hitop114', 'hitop124', 'hitop129', 'hitop204', 'hitop236')

 -----> VALID VS GENPOP <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG INVARIANT chisq p = 0.608

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT NOT PASSED, chisq p = 0
SCALAR N/A
STRICT N/A

 -----> VALID VS ENRICHED <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG INVARIANT chisq p = 0.42

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT NOT PASSED, chisq p = 0.002
SCALAR N/A
STRICT N/A

 -----> GENPOP VS ENRICHED <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG INVARIANT chisq p = 0.119

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT chisq p = 0.153
SCALAR N/A
STRICT N/A

+++ TESTING 93th COMBINATION out of 210 possible combinations of 6 items +++
Items to test: ('hitop1', 'hitop114', 'hitop124', 'hitop129', 'hitop204', 'hitop258')

 -----> VALID VS GENPOP <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG INVARIANT chisq p = 0.142

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT NOT PASSED, chisq p = 0.001
SCALAR N/A
STRICT N/A

 -----> VALID VS ENRICHED <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG INVARIANT chisq p = 0.503

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT NOT PASSED, chisq p = 0.009
SCALAR N/A
STRICT N/A

 -----> GENPOP VS ENRICHED <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG INVARIANT chisq p = 0.08

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT chisq p = 0.639
SCALAR N/A
STRICT N/A

+++ TESTING 94th COMBINATION out of 210 possible combinations of 6 items +++
Items to test: ('hitop1', 'hitop114', 'hitop124', 'hitop129', 'hitop222', 'hitop236')

 -----> VALID VS GENPOP <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG INVARIANT chisq p = 0.968

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT NOT PASSED, chisq p = 0
SCALAR N/A
STRICT N/A

 -----> VALID VS ENRICHED <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG INVARIANT chisq p = 0.416

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT NOT PASSED, chisq p = 0.001
SCALAR N/A
STRICT N/A

 -----> GENPOP VS ENRICHED <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG INVARIANT chisq p = 0.135

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT NOT PASSED, chisq p = 0.032
SCALAR N/A
STRICT N/A

+++ TESTING 95th COMBINATION out of 210 possible combinations of 6 items +++
Items to test: ('hitop1', 'hitop114', 'hitop124', 'hitop129', 'hitop222', 'hitop258')

 -----> VALID VS GENPOP <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG INVARIANT chisq p = 0.199

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT NOT PASSED, chisq p = 0
SCALAR N/A
STRICT N/A

 -----> VALID VS ENRICHED <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG INVARIANT chisq p = 0.996

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT NOT PASSED, chisq p = 0.001
SCALAR N/A
STRICT N/A

 -----> GENPOP VS ENRICHED <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG chisq p = 0.046
PASSED SECONDARY CRITERIA WITH CFI = 1.0 TLI = 1.001 RMSEA = 0.039

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT chisq p = 0.241
SCALAR N/A
STRICT N/A

+++ TESTING 96th COMBINATION out of 210 possible combinations of 6 items +++
Items to test: ('hitop1', 'hitop114', 'hitop124', 'hitop129', 'hitop236', 'hitop258')

 -----> VALID VS GENPOP <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG INVARIANT chisq p = 0.8

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT NOT PASSED, chisq p = 0
SCALAR N/A
STRICT N/A

 -----> VALID VS ENRICHED <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG INVARIANT chisq p = 0.843

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT NOT PASSED, chisq p = 0
SCALAR N/A
STRICT N/A

 -----> GENPOP VS ENRICHED <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG INVARIANT chisq p = 0.211

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT chisq p = 0.163
SCALAR N/A
STRICT N/A

+++ TESTING 97th COMBINATION out of 210 possible combinations of 6 items +++
Items to test: ('hitop1', 'hitop114', 'hitop124', 'hitop204', 'hitop222', 'hitop236')

 -----> VALID VS GENPOP <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG INVARIANT chisq p = 0.215

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT NOT PASSED, chisq p = 0
SCALAR N/A
STRICT N/A

 -----> VALID VS ENRICHED <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG INVARIANT chisq p = 0.294

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT NOT PASSED, chisq p = 0
SCALAR N/A
STRICT N/A

 -----> GENPOP VS ENRICHED <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG INVARIANT chisq p = 0.161

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT NOT PASSED, chisq p = 0.007
SCALAR N/A
STRICT N/A

+++ TESTING 98th COMBINATION out of 210 possible combinations of 6 items +++
Items to test: ('hitop1', 'hitop114', 'hitop124', 'hitop204', 'hitop222', 'hitop258')

 -----> VALID VS GENPOP <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG chisq p = 0.039
PASSED SECONDARY CRITERIA WITH CFI = 0.998 TLI = 0.997 RMSEA = 0.03

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT NOT PASSED, chisq p = 0
SCALAR N/A
STRICT N/A

 -----> VALID VS ENRICHED <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG INVARIANT chisq p = 0.91

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT NOT PASSED, chisq p = 0.001
SCALAR N/A
STRICT N/A

 -----> GENPOP VS ENRICHED <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG INVARIANT chisq p = 0.183

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT chisq p = 0.096
SCALAR N/A
STRICT N/A

+++ TESTING 99th COMBINATION out of 210 possible combinations of 6 items +++
Items to test: ('hitop1', 'hitop114', 'hitop124', 'hitop204', 'hitop236', 'hitop258')

 -----> VALID VS GENPOP <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG INVARIANT chisq p = 0.138

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT NOT PASSED, chisq p = 0
SCALAR N/A
STRICT N/A

 -----> VALID VS ENRICHED <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG INVARIANT chisq p = 0.478

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT NOT PASSED, chisq p = 0
SCALAR N/A
STRICT N/A

 -----> GENPOP VS ENRICHED <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG INVARIANT chisq p = 0.281

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT chisq p = 0.05
SCALAR N/A
STRICT N/A

+++ TESTING 100th COMBINATION out of 210 possible combinations of 6 items +++
Items to test: ('hitop1', 'hitop114', 'hitop124', 'hitop222', 'hitop236', 'hitop258')

 -----> VALID VS GENPOP <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG INVARIANT chisq p = 0.206

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT NOT PASSED, chisq p = 0
SCALAR N/A
STRICT N/A

 -----> VALID VS ENRICHED <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG INVARIANT chisq p = 0.887

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT NOT PASSED, chisq p = 0
SCALAR N/A
STRICT N/A

 -----> GENPOP VS ENRICHED <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG INVARIANT chisq p = 0.14

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT NOT PASSED, chisq p = 0.007
SCALAR N/A
STRICT N/A

+++ TESTING 101th COMBINATION out of 210 possible combinations of 6 items +++
Items to test: ('hitop1', 'hitop114', 'hitop129', 'hitop204', 'hitop222', 'hitop236')

 -----> VALID VS GENPOP <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG INVARIANT chisq p = 0.423

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT NOT PASSED, chisq p = 0.001
SCALAR N/A
STRICT N/A

 -----> VALID VS ENRICHED <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG INVARIANT chisq p = 0.326

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT NOT PASSED, chisq p = 0
SCALAR N/A
STRICT N/A

 -----> GENPOP VS ENRICHED <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG INVARIANT chisq p = 0.203

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT NOT PASSED, chisq p = 0.016
SCALAR N/A
STRICT N/A

+++ TESTING 102th COMBINATION out of 210 possible combinations of 6 items +++
Items to test: ('hitop1', 'hitop114', 'hitop129', 'hitop204', 'hitop222', 'hitop258')

 -----> VALID VS GENPOP <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG INVARIANT chisq p = 0.386

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT NOT PASSED, chisq p = 0.001
SCALAR N/A
STRICT N/A

 -----> VALID VS ENRICHED <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG INVARIANT chisq p = 0.868

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT NOT PASSED, chisq p = 0.002
SCALAR N/A
STRICT N/A

 -----> GENPOP VS ENRICHED <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG INVARIANT chisq p = 0.354

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT chisq p = 0.147
SCALAR N/A
STRICT N/A

+++ TESTING 103th COMBINATION out of 210 possible combinations of 6 items +++
Items to test: ('hitop1', 'hitop114', 'hitop129', 'hitop204', 'hitop236', 'hitop258')

 -----> VALID VS GENPOP <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG INVARIANT chisq p = 0.953

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT NOT PASSED, chisq p = 0
SCALAR N/A
STRICT N/A

 -----> VALID VS ENRICHED <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG INVARIANT chisq p = 0.486

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT NOT PASSED, chisq p = 0
SCALAR N/A
STRICT N/A

 -----> GENPOP VS ENRICHED <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG INVARIANT chisq p = 0.49

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT chisq p = 0.054
SCALAR N/A
STRICT N/A

+++ TESTING 104th COMBINATION out of 210 possible combinations of 6 items +++
Items to test: ('hitop1', 'hitop114', 'hitop129', 'hitop222', 'hitop236', 'hitop258')

 -----> VALID VS GENPOP <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG INVARIANT chisq p = 0.993

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT NOT PASSED, chisq p = 0
SCALAR N/A
STRICT N/A

 -----> VALID VS ENRICHED <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG INVARIANT chisq p = 0.486

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT NOT PASSED, chisq p = 0
SCALAR N/A
STRICT N/A

 -----> GENPOP VS ENRICHED <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG INVARIANT chisq p = 0.371

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT NOT PASSED, chisq p = 0.028
SCALAR N/A
STRICT N/A

+++ TESTING 105th COMBINATION out of 210 possible combinations of 6 items +++
Items to test: ('hitop1', 'hitop114', 'hitop204', 'hitop222', 'hitop236', 'hitop258')

 -----> VALID VS GENPOP <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG INVARIANT chisq p = 0.298
METRIC INVARIANT NOT PASSED, chisq p = 0
SCALAR N/A
STRICT N/A

 -----> VALID VS ENRICHED <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG INVARIANT chisq p = 0.213

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT NOT PASSED, chisq p = 0.001
SCALAR N/A
STRICT N/A

 -----> GENPOP VS ENRICHED <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG INVARIANT chisq p = 0.241

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT NOT PASSED, chisq p = 0.002
SCALAR N/A
STRICT N/A

+++ TESTING 106th COMBINATION out of 210 possible combinations of 6 items +++
Items to test: ('hitop1', 'hitop117', 'hitop124', 'hitop129', 'hitop204', 'hitop222')

 -----> VALID VS GENPOP <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG INVARIANT chisq p = 1

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT NOT PASSED, chisq p = 0.007
SCALAR N/A
STRICT N/A

 -----> VALID VS ENRICHED <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG INVARIANT chisq p = 1

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT NOT PASSED, chisq p = 0.001
SCALAR N/A
STRICT N/A

 -----> GENPOP VS ENRICHED <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG INVARIANT chisq p = 0.444

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT NOT PASSED, chisq p = 0.009
SCALAR N/A
STRICT N/A

+++ TESTING 107th COMBINATION out of 210 possible combinations of 6 items +++
Items to test: ('hitop1', 'hitop117', 'hitop124', 'hitop129', 'hitop204', 'hitop236')

 -----> VALID VS GENPOP <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG INVARIANT chisq p = 1

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT NOT PASSED, chisq p = 0.009
SCALAR N/A
STRICT N/A

 -----> VALID VS ENRICHED <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG INVARIANT chisq p = 0.864

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT NOT PASSED, chisq p = 0.003
SCALAR N/A
STRICT N/A

 -----> GENPOP VS ENRICHED <-----
CONFIG INVARIANT chisq p = 0.063

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT chisq p = 0.257
SCALAR N/A
STRICT N/A

+++ TESTING 108th COMBINATION out of 210 possible combinations of 6 items +++
Items to test: ('hitop1', 'hitop117', 'hitop124', 'hitop129', 'hitop204', 'hitop258')

 -----> VALID VS GENPOP <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG INVARIANT chisq p = 1

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT NOT PASSED, chisq p = 0.002
SCALAR N/A
STRICT N/A

 -----> VALID VS ENRICHED <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG INVARIANT chisq p = 0.998

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT NOT PASSED, chisq p = 0.004
SCALAR N/A
STRICT N/A

 -----> GENPOP VS ENRICHED <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG chisq p = 0.038
PASSED SECONDARY CRITERIA WITH CFI = 0.994 TLI = 0.991 RMSEA = 0.052

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT chisq p = 0.09
SCALAR N/A
STRICT N/A

+++ TESTING 109th COMBINATION out of 210 possible combinations of 6 items +++
Items to test: ('hitop1', 'hitop117', 'hitop124', 'hitop129', 'hitop222', 'hitop236')

 -----> VALID VS GENPOP <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG INVARIANT chisq p = 1

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT NOT PASSED, chisq p = 0.001
SCALAR N/A
STRICT N/A

 -----> VALID VS ENRICHED <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG INVARIANT chisq p = 0.842

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT NOT PASSED, chisq p = 0.003
SCALAR N/A
STRICT N/A

 -----> GENPOP VS ENRICHED <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG INVARIANT chisq p = 0.081

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT NOT PASSED, chisq p = 0.008
SCALAR N/A
STRICT N/A

+++ TESTING 110th COMBINATION out of 210 possible combinations of 6 items +++
Items to test: ('hitop1', 'hitop117', 'hitop124', 'hitop129', 'hitop222', 'hitop258')

 -----> VALID VS GENPOP <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG INVARIANT chisq p = 1

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT NOT PASSED, chisq p = 0
SCALAR N/A
STRICT N/A

 -----> VALID VS ENRICHED <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG INVARIANT chisq p = 1

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT NOT PASSED, chisq p = 0.001
SCALAR N/A
STRICT N/A

 -----> GENPOP VS ENRICHED <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG chisq p = 0.047
PASSED SECONDARY CRITERIA WITH CFI = 0.996 TLI = 0.993 RMSEA = 0.048

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT NOT PASSED, chisq p = 0.002
SCALAR N/A
STRICT N/A

+++ TESTING 111th COMBINATION out of 210 possible combinations of 6 items +++
Items to test: ('hitop1', 'hitop117', 'hitop124', 'hitop129', 'hitop236', 'hitop258')

 -----> VALID VS GENPOP <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG INVARIANT chisq p = 1

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT NOT PASSED, chisq p = 0
SCALAR N/A
STRICT N/A

 -----> VALID VS ENRICHED <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG INVARIANT chisq p = 0.826

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT NOT PASSED, chisq p = 0.002
SCALAR N/A
STRICT N/A

 -----> GENPOP VS ENRICHED <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG chisq p = 0.02
PASSED SECONDARY CRITERIA WITH CFI = 0.998 TLI = 0.996 RMSEA = 0.055

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT chisq p = 0.087
SCALAR N/A
STRICT N/A

+++ TESTING 112th COMBINATION out of 210 possible combinations of 6 items +++
Items to test: ('hitop1', 'hitop117', 'hitop124', 'hitop204', 'hitop222', 'hitop236')

 -----> VALID VS GENPOP <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG INVARIANT chisq p = 0.977

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT NOT PASSED, chisq p = 0.003
SCALAR N/A
STRICT N/A

 -----> VALID VS ENRICHED <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG INVARIANT chisq p = 0.823

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT NOT PASSED, chisq p = 0.002
SCALAR N/A
STRICT N/A

 -----> GENPOP VS ENRICHED <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG INVARIANT chisq p = 0.073

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT NOT PASSED, chisq p = 0
SCALAR N/A
STRICT N/A

+++ TESTING 113th COMBINATION out of 210 possible combinations of 6 items +++
Items to test: ('hitop1', 'hitop117', 'hitop124', 'hitop204', 'hitop222', 'hitop258')

 -----> VALID VS GENPOP <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG INVARIANT chisq p = 0.993

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT NOT PASSED, chisq p = 0
SCALAR N/A
STRICT N/A

 -----> VALID VS ENRICHED <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG INVARIANT chisq p = 1

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT NOT PASSED, chisq p = 0.001
SCALAR N/A
STRICT N/A

 -----> GENPOP VS ENRICHED <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG INVARIANT chisq p = 0.156

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT NOT PASSED, chisq p = 0
SCALAR N/A
STRICT N/A

+++ TESTING 114th COMBINATION out of 210 possible combinations of 6 items +++
Items to test: ('hitop1', 'hitop117', 'hitop124', 'hitop204', 'hitop236', 'hitop258')

 -----> VALID VS GENPOP <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG INVARIANT chisq p = 0.971

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT NOT PASSED, chisq p = 0.001
SCALAR N/A
STRICT N/A

 -----> VALID VS ENRICHED <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG INVARIANT chisq p = 0.593

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT NOT PASSED, chisq p = 0.002
SCALAR N/A
STRICT N/A

 -----> GENPOP VS ENRICHED <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG chisq p = 0.021
PASSED SECONDARY CRITERIA WITH CFI = 0.997 TLI = 0.995 RMSEA = 0.04

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT NOT PASSED, chisq p = 0.046
SCALAR N/A
STRICT N/A

+++ TESTING 115th COMBINATION out of 210 possible combinations of 6 items +++
Items to test: ('hitop1', 'hitop117', 'hitop124', 'hitop222', 'hitop236', 'hitop258')

 -----> VALID VS GENPOP <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG INVARIANT chisq p = 0.912

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT NOT PASSED, chisq p = 0
SCALAR N/A
STRICT N/A

 -----> VALID VS ENRICHED <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG INVARIANT chisq p = 0.985

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT NOT PASSED, chisq p = 0
SCALAR N/A
STRICT N/A

 -----> GENPOP VS ENRICHED <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG chisq p = 0.009
PASSED SECONDARY CRITERIA WITH CFI = 0.998 TLI = 0.996 RMSEA = 0.036

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT NOT PASSED, chisq p = 0
SCALAR N/A
STRICT N/A

+++ TESTING 116th COMBINATION out of 210 possible combinations of 6 items +++
Items to test: ('hitop1', 'hitop117', 'hitop129', 'hitop204', 'hitop222', 'hitop236')

 -----> VALID VS GENPOP <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG INVARIANT chisq p = 0.937

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT NOT PASSED, chisq p = 0.005
SCALAR N/A
STRICT N/A

 -----> VALID VS ENRICHED <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG INVARIANT chisq p = 0.116

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT NOT PASSED, chisq p = 0.002
SCALAR N/A
STRICT N/A

 -----> GENPOP VS ENRICHED <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG chisq p = 0.044
PASSED SECONDARY CRITERIA WITH CFI = 1.0 TLI = 1.001 RMSEA = 0.04

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT NOT PASSED, chisq p = 0.013
SCALAR N/A
STRICT N/A

+++ TESTING 117th COMBINATION out of 210 possible combinations of 6 items +++
Items to test: ('hitop1', 'hitop117', 'hitop129', 'hitop204', 'hitop222', 'hitop258')

 -----> VALID VS GENPOP <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG INVARIANT chisq p = 1

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT NOT PASSED, chisq p = 0
SCALAR N/A
STRICT N/A

 -----> VALID VS ENRICHED <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG INVARIANT chisq p = 0.999

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT NOT PASSED, chisq p = 0.002
SCALAR N/A
STRICT N/A

 -----> GENPOP VS ENRICHED <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG INVARIANT chisq p = 0.264

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT NOT PASSED, chisq p = 0
SCALAR N/A
STRICT N/A

+++ TESTING 118th COMBINATION out of 210 possible combinations of 6 items +++
Items to test: ('hitop1', 'hitop117', 'hitop129', 'hitop204', 'hitop236', 'hitop258')

 -----> VALID VS GENPOP <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG INVARIANT chisq p = 1

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT NOT PASSED, chisq p = 0
SCALAR N/A
STRICT N/A

 -----> VALID VS ENRICHED <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG INVARIANT chisq p = 0.273

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT NOT PASSED, chisq p = 0.004
SCALAR N/A
STRICT N/A

 -----> GENPOP VS ENRICHED <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG INVARIANT chisq p = 0.113

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT NOT PASSED, chisq p = 0.036
SCALAR N/A
STRICT N/A

+++ TESTING 119th COMBINATION out of 210 possible combinations of 6 items +++
Items to test: ('hitop1', 'hitop117', 'hitop129', 'hitop222', 'hitop236', 'hitop258')

 -----> VALID VS GENPOP <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG INVARIANT chisq p = 1

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT NOT PASSED, chisq p = 0
SCALAR N/A
STRICT N/A

 -----> VALID VS ENRICHED <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG INVARIANT chisq p = 0.184

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT NOT PASSED, chisq p = 0
SCALAR N/A
STRICT N/A

 -----> GENPOP VS ENRICHED <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG INVARIANT chisq p = 0.054

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT NOT PASSED, chisq p = 0.002
SCALAR N/A
STRICT N/A

+++ TESTING 120th COMBINATION out of 210 possible combinations of 6 items +++
Items to test: ('hitop1', 'hitop117', 'hitop204', 'hitop222', 'hitop236', 'hitop258')

 -----> VALID VS GENPOP <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG INVARIANT chisq p = 0.801

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT NOT PASSED, chisq p = 0
SCALAR N/A
STRICT N/A

 -----> VALID VS ENRICHED <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG INVARIANT chisq p = 0.063

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT NOT PASSED, chisq p = 0.001
SCALAR N/A
STRICT N/A

 -----> GENPOP VS ENRICHED <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG chisq p = 0.01
PASSED SECONDARY CRITERIA WITH CFI = 0.997 TLI = 0.996 RMSEA = 0.037

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT NOT PASSED, chisq p = 0
SCALAR N/A
STRICT N/A

+++ TESTING 121th COMBINATION out of 210 possible combinations of 6 items +++
Items to test: ('hitop1', 'hitop124', 'hitop129', 'hitop204', 'hitop222', 'hitop236')

 -----> VALID VS GENPOP <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG INVARIANT chisq p = 0.349

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT NOT PASSED, chisq p = 0.002
SCALAR N/A
STRICT N/A

 -----> VALID VS ENRICHED <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG INVARIANT chisq p = 0.466

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT NOT PASSED, chisq p = 0
SCALAR N/A
STRICT N/A

 -----> GENPOP VS ENRICHED <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG INVARIANT chisq p = 0.095

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT NOT PASSED, chisq p = 0.005
SCALAR N/A
STRICT N/A

+++ TESTING 122th COMBINATION out of 210 possible combinations of 6 items +++
Items to test: ('hitop1', 'hitop124', 'hitop129', 'hitop204', 'hitop222', 'hitop258')

 -----> VALID VS GENPOP <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG chisq p = 0.045
PASSED SECONDARY CRITERIA WITH CFI = 1.0 TLI = 1.002 RMSEA = 0.032

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT NOT PASSED, chisq p = 0.003
SCALAR N/A
STRICT N/A

 -----> VALID VS ENRICHED <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG INVARIANT chisq p = 0.988

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT NOT PASSED, chisq p = 0.002
SCALAR N/A
STRICT N/A

 -----> GENPOP VS ENRICHED <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG chisq p = 0.03
PASSED SECONDARY CRITERIA WITH CFI = 1.0 TLI = 1.003 RMSEA = 0.032

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT NOT PASSED, chisq p = 0.036
SCALAR N/A
STRICT N/A

+++ TESTING 123th COMBINATION out of 210 possible combinations of 6 items +++
Items to test: ('hitop1', 'hitop124', 'hitop129', 'hitop204', 'hitop236', 'hitop258')

 -----> VALID VS GENPOP <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG INVARIANT chisq p = 0.561

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT NOT PASSED, chisq p = 0
SCALAR N/A
STRICT N/A

 -----> VALID VS ENRICHED <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG INVARIANT chisq p = 0.347

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT NOT PASSED, chisq p = 0
SCALAR N/A
STRICT N/A

 -----> GENPOP VS ENRICHED <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG INVARIANT chisq p = 0.077

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT chisq p = 0.054
SCALAR N/A
STRICT N/A

+++ TESTING 124th COMBINATION out of 210 possible combinations of 6 items +++
Items to test: ('hitop1', 'hitop124', 'hitop129', 'hitop222', 'hitop236', 'hitop258')

 -----> VALID VS GENPOP <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG INVARIANT chisq p = 0.629

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT NOT PASSED, chisq p = 0
SCALAR N/A
STRICT N/A

 -----> VALID VS ENRICHED <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG INVARIANT chisq p = 0.783

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT NOT PASSED, chisq p = 0
SCALAR N/A
STRICT N/A

 -----> GENPOP VS ENRICHED <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG chisq p = 0.034
PASSED SECONDARY CRITERIA WITH CFI = 1.0 TLI = 1.0 RMSEA = 0.042

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT NOT PASSED, chisq p = 0.007
SCALAR N/A
STRICT N/A

+++ TESTING 125th COMBINATION out of 210 possible combinations of 6 items +++
Items to test: ('hitop1', 'hitop124', 'hitop204', 'hitop222', 'hitop236', 'hitop258')

 -----> VALID VS GENPOP <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG INVARIANT chisq p = 0.082

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT NOT PASSED, chisq p = 0
SCALAR N/A
STRICT N/A

 -----> VALID VS ENRICHED <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG INVARIANT chisq p = 0.49

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT NOT PASSED, chisq p = 0
SCALAR N/A
STRICT N/A

 -----> GENPOP VS ENRICHED <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG INVARIANT chisq p = 0.065

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT NOT PASSED, chisq p = 0
SCALAR N/A
STRICT N/A

+++ TESTING 126th COMBINATION out of 210 possible combinations of 6 items +++
Items to test: ('hitop1', 'hitop129', 'hitop204', 'hitop222', 'hitop236', 'hitop258')

 -----> VALID VS GENPOP <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG INVARIANT chisq p = 0.454

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT NOT PASSED, chisq p = 0
SCALAR N/A
STRICT N/A

 -----> VALID VS ENRICHED <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG INVARIANT chisq p = 0.168

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT NOT PASSED, chisq p = 0
SCALAR N/A
STRICT N/A

 -----> GENPOP VS ENRICHED <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG INVARIANT chisq p = 0.189

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT NOT PASSED, chisq p = 0.002
SCALAR N/A
STRICT N/A

+++ TESTING 127th COMBINATION out of 210 possible combinations of 6 items +++
Items to test: ('hitop17', 'hitop114', 'hitop117', 'hitop124', 'hitop129', 'hitop204')

 -----> VALID VS GENPOP <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG INVARIANT chisq p = 0.563

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT NOT PASSED, chisq p = 0.022
SCALAR N/A
STRICT N/A

 -----> VALID VS ENRICHED <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG chisq p = 0.008
PASSED SECONDARY CRITERIA WITH CFI = 0.994 TLI = 0.991 RMSEA = 0.055

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT chisq p = 0.15
SCALAR N/A
STRICT N/A

 -----> GENPOP VS ENRICHED <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG chisq p = 0.016
PASSED SECONDARY CRITERIA WITH CFI = 0.998 TLI = 0.996 RMSEA = 0.052

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT NOT PASSED, chisq p = 0.015
SCALAR N/A
STRICT N/A

+++ TESTING 128th COMBINATION out of 210 possible combinations of 6 items +++
Items to test: ('hitop17', 'hitop114', 'hitop117', 'hitop124', 'hitop129', 'hitop222')

 -----> VALID VS GENPOP <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG INVARIANT chisq p = 0.295

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT NOT PASSED, chisq p = 0.018
SCALAR N/A
STRICT N/A

 -----> VALID VS ENRICHED <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG chisq p = 0.007
PASSED SECONDARY CRITERIA WITH CFI = 0.995 TLI = 0.991 RMSEA = 0.054

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT chisq p = 0.05
SCALAR N/A
STRICT N/A

 -----> GENPOP VS ENRICHED <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG chisq p = 0.017
PASSED SECONDARY CRITERIA WITH CFI = 0.999 TLI = 0.999 RMSEA = 0.046

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT NOT PASSED, chisq p = 0.012
SCALAR N/A
STRICT N/A

+++ TESTING 129th COMBINATION out of 210 possible combinations of 6 items +++
Items to test: ('hitop17', 'hitop114', 'hitop117', 'hitop124', 'hitop129', 'hitop236')

 -----> VALID VS GENPOP <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG INVARIANT chisq p = 0.477

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT NOT PASSED, chisq p = 0.003
SCALAR N/A
STRICT N/A

 -----> VALID VS ENRICHED <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG chisq p = 0.002
PASSED SECONDARY CRITERIA WITH CFI = 0.994 TLI = 0.99 RMSEA = 0.057

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT chisq p = 0.167
SCALAR N/A
STRICT N/A

 -----> GENPOP VS ENRICHED <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG chisq p = 0.006
PASSED SECONDARY CRITERIA WITH CFI = 0.998 TLI = 0.997 RMSEA = 0.051

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT NOT PASSED, chisq p = 0.016
SCALAR N/A
STRICT N/A

+++ TESTING 130th COMBINATION out of 210 possible combinations of 6 items +++
Items to test: ('hitop17', 'hitop114', 'hitop117', 'hitop124', 'hitop129', 'hitop258')

 -----> VALID VS GENPOP <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG INVARIANT chisq p = 0.877

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT NOT PASSED, chisq p = 0.008
SCALAR N/A
STRICT N/A

 -----> VALID VS ENRICHED <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG chisq p = 0.005
PASSED SECONDARY CRITERIA WITH CFI = 0.997 TLI = 0.995 RMSEA = 0.058

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT chisq p = 0.098
SCALAR N/A
STRICT N/A

 -----> GENPOP VS ENRICHED <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG chisq p = 0.006
PASSED SECONDARY CRITERIA WITH CFI = 0.994 TLI = 0.99 RMSEA = 0.051

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT NOT PASSED, chisq p = 0.021
SCALAR N/A
STRICT N/A

+++ TESTING 131th COMBINATION out of 210 possible combinations of 6 items +++
Items to test: ('hitop17', 'hitop114', 'hitop117', 'hitop124', 'hitop204', 'hitop222')

 -----> VALID VS GENPOP <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG INVARIANT chisq p = 0.053

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT NOT PASSED, chisq p = 0.025
SCALAR N/A
STRICT N/A

 -----> VALID VS ENRICHED <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG chisq p = 0.006
PASSED SECONDARY CRITERIA WITH CFI = 0.997 TLI = 0.995 RMSEA = 0.043

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT NOT PASSED, chisq p = 0.039
SCALAR N/A
STRICT N/A

 -----> GENPOP VS ENRICHED <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG chisq p = 0.03
PASSED SECONDARY CRITERIA WITH CFI = 0.996 TLI = 0.994 RMSEA = 0.041

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT NOT PASSED, chisq p = 0.004
SCALAR N/A
STRICT N/A

+++ TESTING 132th COMBINATION out of 210 possible combinations of 6 items +++
Items to test: ('hitop17', 'hitop114', 'hitop117', 'hitop124', 'hitop204', 'hitop236')

 -----> VALID VS GENPOP <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG INVARIANT chisq p = 0.312

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT NOT PASSED, chisq p = 0.01
SCALAR N/A
STRICT N/A

 -----> VALID VS ENRICHED <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG chisq p = 0.001
PASSED SECONDARY CRITERIA WITH CFI = 1.0 TLI = 1.0 RMSEA = 0.043

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT chisq p = 0.253
SCALAR N/A
STRICT N/A

 -----> GENPOP VS ENRICHED <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG chisq p = 0.005
PASSED SECONDARY CRITERIA WITH CFI = 0.996 TLI = 0.994 RMSEA = 0.042

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT NOT PASSED, chisq p = 0.002
SCALAR N/A
STRICT N/A

+++ TESTING 133th COMBINATION out of 210 possible combinations of 6 items +++
Items to test: ('hitop17', 'hitop114', 'hitop117', 'hitop124', 'hitop204', 'hitop258')

 -----> VALID VS GENPOP <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG INVARIANT chisq p = 0.42

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT NOT PASSED, chisq p = 0.006
SCALAR N/A
STRICT N/A

 -----> VALID VS ENRICHED <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG chisq p = 0.003
PASSED SECONDARY CRITERIA WITH CFI = 0.997 TLI = 0.995 RMSEA = 0.043

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT chisq p = 0.199
SCALAR N/A
STRICT N/A

 -----> GENPOP VS ENRICHED <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG chisq p = 0.016
PASSED SECONDARY CRITERIA WITH CFI = 0.996 TLI = 0.994 RMSEA = 0.041

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT NOT PASSED, chisq p = 0.005
SCALAR N/A
STRICT N/A

+++ TESTING 134th COMBINATION out of 210 possible combinations of 6 items +++
Items to test: ('hitop17', 'hitop114', 'hitop117', 'hitop124', 'hitop222', 'hitop236')

 -----> VALID VS GENPOP <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG INVARIANT chisq p = 0.055

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT NOT PASSED, chisq p = 0.01
SCALAR N/A
STRICT N/A

 -----> VALID VS ENRICHED <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG chisq p = 0
PASSED SECONDARY CRITERIA WITH CFI = 0.997 TLI = 0.995 RMSEA = 0.044

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT chisq p = 0.065
SCALAR N/A
STRICT N/A

 -----> GENPOP VS ENRICHED <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG chisq p = 0.029
PASSED SECONDARY CRITERIA WITH CFI = 1.0 TLI = 1.001 RMSEA = 0.038

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT NOT PASSED, chisq p = 0
SCALAR N/A
STRICT N/A

+++ TESTING 135th COMBINATION out of 210 possible combinations of 6 items +++
Items to test: ('hitop17', 'hitop114', 'hitop117', 'hitop124', 'hitop222', 'hitop258')

 -----> VALID VS GENPOP <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG INVARIANT chisq p = 0.089

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT NOT PASSED, chisq p = 0.005
SCALAR N/A
STRICT N/A

 -----> VALID VS ENRICHED <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG chisq p = 0.003
PASSED SECONDARY CRITERIA WITH CFI = 1.0 TLI = 1.0 RMSEA = 0.04

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT NOT PASSED, chisq p = 0.017
SCALAR N/A
STRICT N/A

 -----> GENPOP VS ENRICHED <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG chisq p = 0.007
PASSED SECONDARY CRITERIA WITH CFI = 0.998 TLI = 0.996 RMSEA = 0.033

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT NOT PASSED, chisq p = 0
SCALAR N/A
STRICT N/A

+++ TESTING 136th COMBINATION out of 210 possible combinations of 6 items +++
Items to test: ('hitop17', 'hitop114', 'hitop117', 'hitop124', 'hitop236', 'hitop258')

 -----> VALID VS GENPOP <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG INVARIANT chisq p = 0.17

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT NOT PASSED, chisq p = 0.001
SCALAR N/A
STRICT N/A

 -----> VALID VS ENRICHED <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG chisq p = 0.004
PASSED SECONDARY CRITERIA WITH CFI = 1.0 TLI = 1.001 RMSEA = 0.038

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT chisq p = 0.158
SCALAR N/A
STRICT N/A

 -----> GENPOP VS ENRICHED <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG chisq p = 0.005
PASSED SECONDARY CRITERIA WITH CFI = 0.998 TLI = 0.996 RMSEA = 0.032

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT NOT PASSED, chisq p = 0.002
SCALAR N/A
STRICT N/A

+++ TESTING 137th COMBINATION out of 210 possible combinations of 6 items +++
Items to test: ('hitop17', 'hitop114', 'hitop117', 'hitop129', 'hitop204', 'hitop222')

 -----> VALID VS GENPOP <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG INVARIANT chisq p = 0.116

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT chisq p = 0.06
SCALAR N/A
STRICT N/A

 -----> VALID VS ENRICHED <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG chisq p = 0.028
PASSED SECONDARY CRITERIA WITH CFI = 0.998 TLI = 0.996 RMSEA = 0.035

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT NOT PASSED, chisq p = 0.025
SCALAR N/A
STRICT N/A

 -----> GENPOP VS ENRICHED <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG INVARIANT chisq p = 0.053

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT NOT PASSED, chisq p = 0.004
SCALAR N/A
STRICT N/A

+++ TESTING 138th COMBINATION out of 210 possible combinations of 6 items +++
Items to test: ('hitop17', 'hitop114', 'hitop117', 'hitop129', 'hitop204', 'hitop236')

 -----> VALID VS GENPOP <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG INVARIANT chisq p = 0.433

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT NOT PASSED, chisq p = 0.014
SCALAR N/A
STRICT N/A

 -----> VALID VS ENRICHED <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG chisq p = 0.047
PASSED SECONDARY CRITERIA WITH CFI = 0.997 TLI = 0.995 RMSEA = 0.039

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT chisq p = 0.103
SCALAR N/A
STRICT N/A

 -----> GENPOP VS ENRICHED <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG chisq p = 0.025
PASSED SECONDARY CRITERIA WITH CFI = 1.0 TLI = 1.0 RMSEA = 0.042

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT NOT PASSED, chisq p = 0.006
SCALAR N/A
STRICT N/A

+++ TESTING 139th COMBINATION out of 210 possible combinations of 6 items +++
Items to test: ('hitop17', 'hitop114', 'hitop117', 'hitop129', 'hitop204', 'hitop258')

 -----> VALID VS GENPOP <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG INVARIANT chisq p = 0.992

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT NOT PASSED, chisq p = 0.018
SCALAR N/A
STRICT N/A

 -----> VALID VS ENRICHED <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG INVARIANT chisq p = 0.072

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT chisq p = 0.172
SCALAR N/A
STRICT N/A

 -----> GENPOP VS ENRICHED <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG INVARIANT chisq p = 0.056

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT NOT PASSED, chisq p = 0.003
SCALAR N/A
STRICT N/A

+++ TESTING 140th COMBINATION out of 210 possible combinations of 6 items +++
Items to test: ('hitop17', 'hitop114', 'hitop117', 'hitop129', 'hitop222', 'hitop236')

 -----> VALID VS GENPOP <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG INVARIANT chisq p = 0.074

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT NOT PASSED, chisq p = 0.018
SCALAR N/A
STRICT N/A

 -----> VALID VS ENRICHED <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG chisq p = 0.001
PASSED SECONDARY CRITERIA WITH CFI = 1.0 TLI = 1.0 RMSEA = 0.042

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT NOT PASSED, chisq p = 0.045
SCALAR N/A
STRICT N/A

 -----> GENPOP VS ENRICHED <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG INVARIANT chisq p = 0.078

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT NOT PASSED, chisq p = 0.002
SCALAR N/A
STRICT N/A

+++ TESTING 141th COMBINATION out of 210 possible combinations of 6 items +++
Items to test: ('hitop17', 'hitop114', 'hitop117', 'hitop129', 'hitop222', 'hitop258')

 -----> VALID VS GENPOP <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG INVARIANT chisq p = 0.295

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT NOT PASSED, chisq p = 0.016
SCALAR N/A
STRICT N/A

 -----> VALID VS ENRICHED <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG chisq p = 0.021
PASSED SECONDARY CRITERIA WITH CFI = 0.999 TLI = 0.999 RMSEA = 0.046

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT NOT PASSED, chisq p = 0.024
SCALAR N/A
STRICT N/A

 -----> GENPOP VS ENRICHED <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG chisq p = 0.035
PASSED SECONDARY CRITERIA WITH CFI = 0.997 TLI = 0.994 RMSEA = 0.039

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT NOT PASSED, chisq p = 0.003
SCALAR N/A
STRICT N/A

+++ TESTING 142th COMBINATION out of 210 possible combinations of 6 items +++
Items to test: ('hitop17', 'hitop114', 'hitop117', 'hitop129', 'hitop236', 'hitop258')

 -----> VALID VS GENPOP <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG INVARIANT chisq p = 0.822

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT NOT PASSED, chisq p = 0.003
SCALAR N/A
STRICT N/A

 -----> VALID VS ENRICHED <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG chisq p = 0.022
PASSED SECONDARY CRITERIA WITH CFI = 0.995 TLI = 0.992 RMSEA = 0.052

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT chisq p = 0.098
SCALAR N/A
STRICT N/A

 -----> GENPOP VS ENRICHED <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG chisq p = 0.015
PASSED SECONDARY CRITERIA WITH CFI = 0.999 TLI = 0.999 RMSEA = 0.046

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT NOT PASSED, chisq p = 0.01
SCALAR N/A
STRICT N/A

+++ TESTING 143th COMBINATION out of 210 possible combinations of 6 items +++
Items to test: ('hitop17', 'hitop114', 'hitop117', 'hitop204', 'hitop222', 'hitop236')

 -----> VALID VS GENPOP <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG chisq p = 0.015
PASSED SECONDARY CRITERIA WITH CFI = 0.999 TLI = 0.998 RMSEA = 0.027

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT NOT PASSED, chisq p = 0.025
SCALAR N/A
STRICT N/A

 -----> VALID VS ENRICHED <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG chisq p = 0.002
PASSED SECONDARY CRITERIA WITH CFI = 0.997 TLI = 0.996 RMSEA = 0.038

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT NOT PASSED, chisq p = 0.041
SCALAR N/A
STRICT N/A

 -----> GENPOP VS ENRICHED <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG chisq p = 0.027
PASSED SECONDARY CRITERIA WITH CFI = 1.0 TLI = 1.002 RMSEA = 0.035

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT NOT PASSED, chisq p = 0
SCALAR N/A
STRICT N/A

+++ TESTING 144th COMBINATION out of 210 possible combinations of 6 items +++
Items to test: ('hitop17', 'hitop114', 'hitop117', 'hitop204', 'hitop222', 'hitop258')

 -----> VALID VS GENPOP <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG INVARIANT chisq p = 0.065
METRIC INVARIANT NOT PASSED, chisq p = 0.016
SCALAR N/A
STRICT N/A

 -----> VALID VS ENRICHED <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG chisq p = 0.024
PASSED SECONDARY CRITERIA WITH CFI = 1.0 TLI = 1.001 RMSEA = 0.036

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT NOT PASSED, chisq p = 0.025
SCALAR N/A
STRICT N/A

 -----> GENPOP VS ENRICHED <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG chisq p = 0.038
PASSED SECONDARY CRITERIA WITH CFI = 1.0 TLI = 1.003 RMSEA = 0.032

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT NOT PASSED, chisq p = 0
SCALAR N/A
STRICT N/A

+++ TESTING 145th COMBINATION out of 210 possible combinations of 6 items +++
Items to test: ('hitop17', 'hitop114', 'hitop117', 'hitop204', 'hitop236', 'hitop258')

 -----> VALID VS GENPOP <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG INVARIANT chisq p = 0.357

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT NOT PASSED, chisq p = 0.004
SCALAR N/A
STRICT N/A

 -----> VALID VS ENRICHED <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG chisq p = 0.02
PASSED SECONDARY CRITERIA WITH CFI = 0.997 TLI = 0.995 RMSEA = 0.04

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT chisq p = 0.254
SCALAR N/A
STRICT N/A

 -----> GENPOP VS ENRICHED <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG chisq p = 0.002
PASSED SECONDARY CRITERIA WITH CFI = 1.0 TLI = 1.001 RMSEA = 0.038

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT NOT PASSED, chisq p = 0.001
SCALAR N/A
STRICT N/A

+++ TESTING 146th COMBINATION out of 210 possible combinations of 6 items +++
Items to test: ('hitop17', 'hitop114', 'hitop117', 'hitop222', 'hitop236', 'hitop258')

 -----> VALID VS GENPOP <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG chisq p = 0.042
PASSED SECONDARY CRITERIA WITH CFI = 1.0 TLI = 1.003 RMSEA = 0.027

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT NOT PASSED, chisq p = 0.003
SCALAR N/A
STRICT N/A

 -----> VALID VS ENRICHED <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG chisq p = 0.003
PASSED SECONDARY CRITERIA WITH CFI = 1.0 TLI = 1.0 RMSEA = 0.043

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT NOT PASSED, chisq p = 0.034
SCALAR N/A
STRICT N/A

 -----> GENPOP VS ENRICHED <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG chisq p = 0.011
PASSED SECONDARY CRITERIA WITH CFI = 1.0 TLI = 1.002 RMSEA = 0.035

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT NOT PASSED, chisq p = 0
SCALAR N/A
STRICT N/A

+++ TESTING 147th COMBINATION out of 210 possible combinations of 6 items +++
Items to test: ('hitop17', 'hitop114', 'hitop124', 'hitop129', 'hitop204', 'hitop222')

 -----> VALID VS GENPOP <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG INVARIANT chisq p = 0.118
METRIC INVARIANT NOT PASSED, chisq p = 0.044
SCALAR N/A
STRICT N/A

 -----> VALID VS ENRICHED <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG INVARIANT chisq p = 0.581

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT NOT PASSED, chisq p = 0.003
SCALAR N/A
STRICT N/A

 -----> GENPOP VS ENRICHED <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG INVARIANT chisq p = 0.082

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT chisq p = 0.097
SCALAR N/A
STRICT N/A

+++ TESTING 148th COMBINATION out of 210 possible combinations of 6 items +++
Items to test: ('hitop17', 'hitop114', 'hitop124', 'hitop129', 'hitop204', 'hitop236')

 -----> VALID VS GENPOP <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG INVARIANT chisq p = 0.459

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT NOT PASSED, chisq p = 0.009
SCALAR N/A
STRICT N/A

 -----> VALID VS ENRICHED <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG INVARIANT chisq p = 0.442

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT NOT PASSED, chisq p = 0.011
SCALAR N/A
STRICT N/A

 -----> GENPOP VS ENRICHED <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG INVARIANT chisq p = 0.25

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT NOT PASSED, chisq p = 0.007
SCALAR N/A
STRICT N/A

+++ TESTING 149th COMBINATION out of 210 possible combinations of 6 items +++
Items to test: ('hitop17', 'hitop114', 'hitop124', 'hitop129', 'hitop204', 'hitop258')

 -----> VALID VS GENPOP <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG INVARIANT chisq p = 0.563

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT chisq p = 0.05
SCALAR N/A
STRICT N/A

 -----> VALID VS ENRICHED <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG INVARIANT chisq p = 0.371

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT NOT PASSED, chisq p = 0.025
SCALAR N/A
STRICT N/A

 -----> GENPOP VS ENRICHED <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG INVARIANT chisq p = 0.241

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT chisq p = 0.099
SCALAR N/A
STRICT N/A

+++ TESTING 150th COMBINATION out of 210 possible combinations of 6 items +++
Items to test: ('hitop17', 'hitop114', 'hitop124', 'hitop129', 'hitop222', 'hitop236')

 -----> VALID VS GENPOP <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG INVARIANT chisq p = 0.566

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT NOT PASSED, chisq p = 0.005
SCALAR N/A
STRICT N/A

 -----> VALID VS ENRICHED <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG INVARIANT chisq p = 0.374

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT NOT PASSED, chisq p = 0.004
SCALAR N/A
STRICT N/A

 -----> GENPOP VS ENRICHED <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG INVARIANT chisq p = 0.394

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT NOT PASSED, chisq p = 0.004
SCALAR N/A
STRICT N/A

+++ TESTING 151th COMBINATION out of 210 possible combinations of 6 items +++
Items to test: ('hitop17', 'hitop114', 'hitop124', 'hitop129', 'hitop222', 'hitop258')

 -----> VALID VS GENPOP <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG INVARIANT chisq p = 0.443

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT NOT PASSED, chisq p = 0.02
SCALAR N/A
STRICT N/A

 -----> VALID VS ENRICHED <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG INVARIANT chisq p = 0.917

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT NOT PASSED, chisq p = 0.001
SCALAR N/A
STRICT N/A

 -----> GENPOP VS ENRICHED <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG INVARIANT chisq p = 0.1

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT chisq p = 0.204
SCALAR N/A
STRICT N/A

+++ TESTING 152th COMBINATION out of 210 possible combinations of 6 items +++
Items to test: ('hitop17', 'hitop114', 'hitop124', 'hitop129', 'hitop236', 'hitop258')

 -----> VALID VS GENPOP <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG INVARIANT chisq p = 0.913

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT NOT PASSED, chisq p = 0.005
SCALAR N/A
STRICT N/A

 -----> VALID VS ENRICHED <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG INVARIANT chisq p = 0.67

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT NOT PASSED, chisq p = 0.006
SCALAR N/A
STRICT N/A

 -----> GENPOP VS ENRICHED <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG INVARIANT chisq p = 0.377

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT NOT PASSED, chisq p = 0.01
SCALAR N/A
STRICT N/A

+++ TESTING 153th COMBINATION out of 210 possible combinations of 6 items +++
Items to test: ('hitop17', 'hitop114', 'hitop124', 'hitop204', 'hitop222', 'hitop236')

 -----> VALID VS GENPOP <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG chisq p = 0.033
PASSED SECONDARY CRITERIA WITH CFI = 0.999 TLI = 0.998 RMSEA = 0.025

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT NOT PASSED, chisq p = 0.011
SCALAR N/A
STRICT N/A

 -----> VALID VS ENRICHED <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG INVARIANT chisq p = 0.291

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT NOT PASSED, chisq p = 0
SCALAR N/A
STRICT N/A

 -----> GENPOP VS ENRICHED <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG INVARIANT chisq p = 0.524

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT NOT PASSED, chisq p = 0
SCALAR N/A
STRICT N/A

+++ TESTING 154th COMBINATION out of 210 possible combinations of 6 items +++
Items to test: ('hitop17', 'hitop114', 'hitop124', 'hitop204', 'hitop222', 'hitop258')

 -----> VALID VS GENPOP <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG INVARIANT chisq p = 0.06

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT NOT PASSED, chisq p = 0.029
SCALAR N/A
STRICT N/A

 -----> VALID VS ENRICHED <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG INVARIANT chisq p = 0.578

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT NOT PASSED, chisq p = 0.003
SCALAR N/A
STRICT N/A

 -----> GENPOP VS ENRICHED <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG INVARIANT chisq p = 0.27

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT chisq p = 0.101
SCALAR N/A
STRICT N/A

+++ TESTING 155th COMBINATION out of 210 possible combinations of 6 items +++
Items to test: ('hitop17', 'hitop114', 'hitop124', 'hitop204', 'hitop236', 'hitop258')

 -----> VALID VS GENPOP <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG INVARIANT chisq p = 0.287

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT NOT PASSED, chisq p = 0.003
SCALAR N/A
STRICT N/A

 -----> VALID VS ENRICHED <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG INVARIANT chisq p = 0.428

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT NOT PASSED, chisq p = 0.017
SCALAR N/A
STRICT N/A

 -----> GENPOP VS ENRICHED <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG INVARIANT chisq p = 0.449

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT NOT PASSED, chisq p = 0.002
SCALAR N/A
STRICT N/A

+++ TESTING 156th COMBINATION out of 210 possible combinations of 6 items +++
Items to test: ('hitop17', 'hitop114', 'hitop124', 'hitop222', 'hitop236', 'hitop258')

 -----> VALID VS GENPOP <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG INVARIANT chisq p = 0.239

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT NOT PASSED, chisq p = 0.001
SCALAR N/A
STRICT N/A

 -----> VALID VS ENRICHED <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG INVARIANT chisq p = 0.543

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT NOT PASSED, chisq p = 0.001
SCALAR N/A
STRICT N/A

 -----> GENPOP VS ENRICHED <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG INVARIANT chisq p = 0.36

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT NOT PASSED, chisq p = 0
SCALAR N/A
STRICT N/A

+++ TESTING 157th COMBINATION out of 210 possible combinations of 6 items +++
Items to test: ('hitop17', 'hitop114', 'hitop129', 'hitop204', 'hitop222', 'hitop236')

 -----> VALID VS GENPOP <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG chisq p = 0.04
PASSED SECONDARY CRITERIA WITH CFI = 0.998 TLI = 0.997 RMSEA = 0.027

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT chisq p = 0.061
SCALAR N/A
STRICT N/A

 -----> VALID VS ENRICHED <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG INVARIANT chisq p = 0.749

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT NOT PASSED, chisq p = 0
SCALAR N/A
STRICT N/A

 -----> GENPOP VS ENRICHED <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG INVARIANT chisq p = 0.555

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT NOT PASSED, chisq p = 0
SCALAR N/A
STRICT N/A

+++ TESTING 158th COMBINATION out of 210 possible combinations of 6 items +++
Items to test: ('hitop17', 'hitop114', 'hitop129', 'hitop204', 'hitop222', 'hitop258')

 -----> VALID VS GENPOP <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG INVARIANT chisq p = 0.136

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT chisq p = 0.254
SCALAR N/A
STRICT N/A

 -----> VALID VS ENRICHED <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG INVARIANT chisq p = 0.82

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT NOT PASSED, chisq p = 0.005
SCALAR N/A
STRICT N/A

 -----> GENPOP VS ENRICHED <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG INVARIANT chisq p = 0.359

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT chisq p = 0.118
SCALAR N/A
STRICT N/A

+++ TESTING 159th COMBINATION out of 210 possible combinations of 6 items +++
Items to test: ('hitop17', 'hitop114', 'hitop129', 'hitop204', 'hitop236', 'hitop258')

 -----> VALID VS GENPOP <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG INVARIANT chisq p = 0.648

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT chisq p = 0.058
SCALAR N/A
STRICT N/A

 -----> VALID VS ENRICHED <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG INVARIANT chisq p = 0.914

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT NOT PASSED, chisq p = 0.02
SCALAR N/A
STRICT N/A

 -----> GENPOP VS ENRICHED <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG INVARIANT chisq p = 0.611

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT NOT PASSED, chisq p = 0.004
SCALAR N/A
STRICT N/A

+++ TESTING 160th COMBINATION out of 210 possible combinations of 6 items +++
Items to test: ('hitop17', 'hitop114', 'hitop129', 'hitop222', 'hitop236', 'hitop258')

 -----> VALID VS GENPOP <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG INVARIANT chisq p = 0.624

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT NOT PASSED, chisq p = 0.026
SCALAR N/A
STRICT N/A

 -----> VALID VS ENRICHED <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG INVARIANT chisq p = 0.815

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT NOT PASSED, chisq p = 0
SCALAR N/A
STRICT N/A

 -----> GENPOP VS ENRICHED <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG INVARIANT chisq p = 0.546

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT NOT PASSED, chisq p = 0.005
SCALAR N/A
STRICT N/A

+++ TESTING 161th COMBINATION out of 210 possible combinations of 6 items +++
Items to test: ('hitop17', 'hitop114', 'hitop204', 'hitop222', 'hitop236', 'hitop258')

 -----> VALID VS GENPOP <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG chisq p = 0.029
PASSED SECONDARY CRITERIA WITH CFI = 0.999 TLI = 0.998 RMSEA = 0.021

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT NOT PASSED, chisq p = 0.023
SCALAR N/A
STRICT N/A

 -----> VALID VS ENRICHED <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG INVARIANT chisq p = 0.55

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT NOT PASSED, chisq p = 0
SCALAR N/A
STRICT N/A

 -----> GENPOP VS ENRICHED <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG INVARIANT chisq p = 0.604

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT NOT PASSED, chisq p = 0.001
SCALAR N/A
STRICT N/A

+++ TESTING 162th COMBINATION out of 210 possible combinations of 6 items +++
Items to test: ('hitop17', 'hitop117', 'hitop124', 'hitop129', 'hitop204', 'hitop222')

 -----> VALID VS GENPOP <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG INVARIANT chisq p = 0.242

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT chisq p = 0.248
SCALAR N/A
STRICT N/A

 -----> VALID VS ENRICHED <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG INVARIANT chisq p = 0.548

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT NOT PASSED, chisq p = 0.003
SCALAR N/A
STRICT N/A

 -----> GENPOP VS ENRICHED <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG INVARIANT chisq p = 0.185

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT NOT PASSED, chisq p = 0.004
SCALAR N/A
STRICT N/A

+++ TESTING 163th COMBINATION out of 210 possible combinations of 6 items +++
Items to test: ('hitop17', 'hitop117', 'hitop124', 'hitop129', 'hitop204', 'hitop236')

 -----> VALID VS GENPOP <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG INVARIANT chisq p = 0.719

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT chisq p = 0.094
SCALAR N/A
STRICT N/A

 -----> VALID VS ENRICHED <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG INVARIANT chisq p = 0.089

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT chisq p = 0.056
SCALAR N/A
STRICT N/A

 -----> GENPOP VS ENRICHED <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG chisq p = 0.021
PASSED SECONDARY CRITERIA WITH CFI = 0.996 TLI = 0.993 RMSEA = 0.043

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT NOT PASSED, chisq p = 0.021
SCALAR N/A
STRICT N/A

+++ TESTING 164th COMBINATION out of 210 possible combinations of 6 items +++
Items to test: ('hitop17', 'hitop117', 'hitop124', 'hitop129', 'hitop204', 'hitop258')

 -----> VALID VS GENPOP <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG INVARIANT chisq p = 0.993

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT chisq p = 0.055
SCALAR N/A
STRICT N/A

 -----> VALID VS ENRICHED <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG INVARIANT chisq p = 0.206

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT chisq p = 0.073
SCALAR N/A
STRICT N/A

 -----> GENPOP VS ENRICHED <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG INVARIANT chisq p = 0.091

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT NOT PASSED, chisq p = 0.012
SCALAR N/A
STRICT N/A

+++ TESTING 165th COMBINATION out of 210 possible combinations of 6 items +++
Items to test: ('hitop17', 'hitop117', 'hitop124', 'hitop129', 'hitop222', 'hitop236')

 -----> VALID VS GENPOP <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG INVARIANT chisq p = 0.282

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT chisq p = 0.051
SCALAR N/A
STRICT N/A

 -----> VALID VS ENRICHED <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG chisq p = 0.019
PASSED SECONDARY CRITERIA WITH CFI = 0.998 TLI = 0.997 RMSEA = 0.051

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT NOT PASSED, chisq p = 0.012
SCALAR N/A
STRICT N/A

 -----> GENPOP VS ENRICHED <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG INVARIANT chisq p = 0.175

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT NOT PASSED, chisq p = 0.004
SCALAR N/A
STRICT N/A

+++ TESTING 166th COMBINATION out of 210 possible combinations of 6 items +++
Items to test: ('hitop17', 'hitop117', 'hitop124', 'hitop129', 'hitop222', 'hitop258')

 -----> VALID VS GENPOP <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG INVARIANT chisq p = 0.494

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT NOT PASSED, chisq p = 0.038
SCALAR N/A
STRICT N/A

 -----> VALID VS ENRICHED <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG INVARIANT chisq p = 0.337

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT NOT PASSED, chisq p = 0.002
SCALAR N/A
STRICT N/A

 -----> GENPOP VS ENRICHED <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG INVARIANT chisq p = 0.169

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT NOT PASSED, chisq p = 0
SCALAR N/A
STRICT N/A

+++ TESTING 167th COMBINATION out of 210 possible combinations of 6 items +++
Items to test: ('hitop17', 'hitop117', 'hitop124', 'hitop129', 'hitop236', 'hitop258')

 -----> VALID VS GENPOP <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG INVARIANT chisq p = 0.942

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT NOT PASSED, chisq p = 0.005
SCALAR N/A
STRICT N/A

 -----> VALID VS ENRICHED <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG chisq p = 0.042
PASSED SECONDARY CRITERIA WITH CFI = 0.998 TLI = 0.996 RMSEA = 0.056

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT NOT PASSED, chisq p = 0.047
SCALAR N/A
STRICT N/A

 -----> GENPOP VS ENRICHED <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG chisq p = 0.026
PASSED SECONDARY CRITERIA WITH CFI = 0.995 TLI = 0.992 RMSEA = 0.048

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT NOT PASSED, chisq p = 0.019
SCALAR N/A
STRICT N/A

+++ TESTING 168th COMBINATION out of 210 possible combinations of 6 items +++
Items to test: ('hitop17', 'hitop117', 'hitop124', 'hitop204', 'hitop222', 'hitop236')

 -----> VALID VS GENPOP <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG INVARIANT chisq p = 0.05

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT chisq p = 0.24
SCALAR N/A
STRICT N/A

 -----> VALID VS ENRICHED <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG chisq p = 0.036
PASSED SECONDARY CRITERIA WITH CFI = 1.0 TLI = 1.001 RMSEA = 0.037

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT NOT PASSED, chisq p = 0.005
SCALAR N/A
STRICT N/A

 -----> GENPOP VS ENRICHED <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG INVARIANT chisq p = 0.092

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT NOT PASSED, chisq p = 0.001
SCALAR N/A
STRICT N/A

+++ TESTING 169th COMBINATION out of 210 possible combinations of 6 items +++
Items to test: ('hitop17', 'hitop117', 'hitop124', 'hitop204', 'hitop222', 'hitop258')

 -----> VALID VS GENPOP <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG INVARIANT chisq p = 0.089

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT chisq p = 0.06
SCALAR N/A
STRICT N/A

 -----> VALID VS ENRICHED <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG INVARIANT chisq p = 0.537

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT NOT PASSED, chisq p = 0.003
SCALAR N/A
STRICT N/A

 -----> GENPOP VS ENRICHED <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG INVARIANT chisq p = 0.316

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT NOT PASSED, chisq p = 0
SCALAR N/A
STRICT N/A

+++ TESTING 170th COMBINATION out of 210 possible combinations of 6 items +++
Items to test: ('hitop17', 'hitop117', 'hitop124', 'hitop204', 'hitop236', 'hitop258')

 -----> VALID VS GENPOP <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG INVARIANT chisq p = 0.428

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT NOT PASSED, chisq p = 0.02
SCALAR N/A
STRICT N/A

 -----> VALID VS ENRICHED <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG INVARIANT chisq p = 0.05

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT chisq p = 0.107
SCALAR N/A
STRICT N/A

 -----> GENPOP VS ENRICHED <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG chisq p = 0.008
PASSED SECONDARY CRITERIA WITH CFI = 1.0 TLI = 1.003 RMSEA = 0.031

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT NOT PASSED, chisq p = 0.004
SCALAR N/A
STRICT N/A

+++ TESTING 171th COMBINATION out of 210 possible combinations of 6 items +++
Items to test: ('hitop17', 'hitop117', 'hitop124', 'hitop222', 'hitop236', 'hitop258')

 -----> VALID VS GENPOP <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG INVARIANT chisq p = 0.093

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT NOT PASSED, chisq p = 0.009
SCALAR N/A
STRICT N/A

 -----> VALID VS ENRICHED <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG chisq p = 0.021
PASSED SECONDARY CRITERIA WITH CFI = 1.0 TLI = 1.001 RMSEA = 0.039

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT NOT PASSED, chisq p = 0.002
SCALAR N/A
STRICT N/A

 -----> GENPOP VS ENRICHED <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG INVARIANT chisq p = 0.071

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT NOT PASSED, chisq p = 0
SCALAR N/A
STRICT N/A

+++ TESTING 172th COMBINATION out of 210 possible combinations of 6 items +++
Items to test: ('hitop17', 'hitop117', 'hitop129', 'hitop204', 'hitop222', 'hitop236')

 -----> VALID VS GENPOP <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG chisq p = 0.032
PASSED SECONDARY CRITERIA WITH CFI = 1.0 TLI = 1.001 RMSEA = 0.036

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT chisq p = 0.135
SCALAR N/A
STRICT N/A

 -----> VALID VS ENRICHED <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG chisq p = 0.007
PASSED SECONDARY CRITERIA WITH CFI = 1.0 TLI = 1.001 RMSEA = 0.039

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT NOT PASSED, chisq p = 0.006
SCALAR N/A
STRICT N/A

 -----> GENPOP VS ENRICHED <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG chisq p = 0.031
PASSED SECONDARY CRITERIA WITH CFI = 0.997 TLI = 0.995 RMSEA = 0.038

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT NOT PASSED, chisq p = 0.003
SCALAR N/A
STRICT N/A

+++ TESTING 173th COMBINATION out of 210 possible combinations of 6 items +++
Items to test: ('hitop17', 'hitop117', 'hitop129', 'hitop204', 'hitop222', 'hitop258')

 -----> VALID VS GENPOP <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG INVARIANT chisq p = 0.234

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT chisq p = 0.114
SCALAR N/A
STRICT N/A

 -----> VALID VS ENRICHED <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG INVARIANT chisq p = 0.462

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT NOT PASSED, chisq p = 0.004
SCALAR N/A
STRICT N/A

 -----> GENPOP VS ENRICHED <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG INVARIANT chisq p = 0.285

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT NOT PASSED, chisq p = 0
SCALAR N/A
STRICT N/A

+++ TESTING 174th COMBINATION out of 210 possible combinations of 6 items +++
Items to test: ('hitop17', 'hitop117', 'hitop129', 'hitop204', 'hitop236', 'hitop258')

 -----> VALID VS GENPOP <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG INVARIANT chisq p = 0.685

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT NOT PASSED, chisq p = 0.02
SCALAR N/A
STRICT N/A

 -----> VALID VS ENRICHED <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG INVARIANT chisq p = 0.061

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT chisq p = 0.217
SCALAR N/A
STRICT N/A

 -----> GENPOP VS ENRICHED <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG chisq p = 0.029
PASSED SECONDARY CRITERIA WITH CFI = 1.0 TLI = 0.999 RMSEA = 0.045

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT NOT PASSED, chisq p = 0.01
SCALAR N/A
STRICT N/A

+++ TESTING 175th COMBINATION out of 210 possible combinations of 6 items +++
Items to test: ('hitop17', 'hitop117', 'hitop129', 'hitop222', 'hitop236', 'hitop258')

 -----> VALID VS GENPOP <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG INVARIANT chisq p = 0.227

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT NOT PASSED, chisq p = 0.018
SCALAR N/A
STRICT N/A

 -----> VALID VS ENRICHED <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG chisq p = 0.012
PASSED SECONDARY CRITERIA WITH CFI = 0.996 TLI = 0.993 RMSEA = 0.049

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT NOT PASSED, chisq p = 0.007
SCALAR N/A
STRICT N/A

 -----> GENPOP VS ENRICHED <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG INVARIANT chisq p = 0.137

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT NOT PASSED, chisq p = 0.002
SCALAR N/A
STRICT N/A

+++ TESTING 176th COMBINATION out of 210 possible combinations of 6 items +++
Items to test: ('hitop17', 'hitop117', 'hitop204', 'hitop222', 'hitop236', 'hitop258')

 -----> VALID VS GENPOP <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG chisq p = 0.007
PASSED SECONDARY CRITERIA WITH CFI = 0.998 TLI = 0.997 RMSEA = 0.03

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT NOT PASSED, chisq p = 0.023
SCALAR N/A
STRICT N/A

 -----> VALID VS ENRICHED <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG chisq p = 0.006
PASSED SECONDARY CRITERIA WITH CFI = 1.0 TLI = 1.001 RMSEA = 0.038

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT NOT PASSED, chisq p = 0.006
SCALAR N/A
STRICT N/A

 -----> GENPOP VS ENRICHED <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG chisq p = 0.034
PASSED SECONDARY CRITERIA WITH CFI = 1.0 TLI = 1.003 RMSEA = 0.033

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT NOT PASSED, chisq p = 0
SCALAR N/A
STRICT N/A

+++ TESTING 177th COMBINATION out of 210 possible combinations of 6 items +++
Items to test: ('hitop17', 'hitop124', 'hitop129', 'hitop204', 'hitop222', 'hitop236')

 -----> VALID VS GENPOP <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG chisq p = 0.037
PASSED SECONDARY CRITERIA WITH CFI = 0.998 TLI = 0.997 RMSEA = 0.03

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT chisq p = 0.151
SCALAR N/A
STRICT N/A

 -----> VALID VS ENRICHED <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG INVARIANT chisq p = 0.786

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT NOT PASSED, chisq p = 0
SCALAR N/A
STRICT N/A

 -----> GENPOP VS ENRICHED <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG INVARIANT chisq p = 0.39

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT NOT PASSED, chisq p = 0.002
SCALAR N/A
STRICT N/A

+++ TESTING 178th COMBINATION out of 210 possible combinations of 6 items +++
Items to test: ('hitop17', 'hitop124', 'hitop129', 'hitop204', 'hitop222', 'hitop258')

 -----> VALID VS GENPOP <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG chisq p = 0.036
PASSED SECONDARY CRITERIA WITH CFI = 1.0 TLI = 1.002 RMSEA = 0.029

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT chisq p = 0.192
SCALAR N/A
STRICT N/A

 -----> VALID VS ENRICHED <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG INVARIANT chisq p = 0.937

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT NOT PASSED, chisq p = 0
SCALAR N/A
STRICT N/A

 -----> GENPOP VS ENRICHED <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG INVARIANT chisq p = 0.134

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT NOT PASSED, chisq p = 0.023
SCALAR N/A
STRICT N/A

+++ TESTING 179th COMBINATION out of 210 possible combinations of 6 items +++
Items to test: ('hitop17', 'hitop124', 'hitop129', 'hitop204', 'hitop236', 'hitop258')

 -----> VALID VS GENPOP <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG INVARIANT chisq p = 0.404

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT NOT PASSED, chisq p = 0.03
SCALAR N/A
STRICT N/A

 -----> VALID VS ENRICHED <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG INVARIANT chisq p = 0.752

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT NOT PASSED, chisq p = 0.006
SCALAR N/A
STRICT N/A

 -----> GENPOP VS ENRICHED <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG INVARIANT chisq p = 0.203

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT NOT PASSED, chisq p = 0.006
SCALAR N/A
STRICT N/A

+++ TESTING 180th COMBINATION out of 210 possible combinations of 6 items +++
Items to test: ('hitop17', 'hitop124', 'hitop129', 'hitop222', 'hitop236', 'hitop258')

 -----> VALID VS GENPOP <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG INVARIANT chisq p = 0.535

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT NOT PASSED, chisq p = 0.013
SCALAR N/A
STRICT N/A

 -----> VALID VS ENRICHED <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG INVARIANT chisq p = 0.899

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT NOT PASSED, chisq p = 0.001
SCALAR N/A
STRICT N/A

 -----> GENPOP VS ENRICHED <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG INVARIANT chisq p = 0.361

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT NOT PASSED, chisq p = 0.004
SCALAR N/A
STRICT N/A

+++ TESTING 181th COMBINATION out of 210 possible combinations of 6 items +++
Items to test: ('hitop17', 'hitop124', 'hitop204', 'hitop222', 'hitop236', 'hitop258')

 -----> VALID VS GENPOP <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG chisq p = 0.018
PASSED SECONDARY CRITERIA WITH CFI = 1.0 TLI = 1.004 RMSEA = 0.02

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT NOT PASSED, chisq p = 0.026
SCALAR N/A
STRICT N/A

 -----> VALID VS ENRICHED <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG INVARIANT chisq p = 0.776

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT NOT PASSED, chisq p = 0
SCALAR N/A
STRICT N/A

 -----> GENPOP VS ENRICHED <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG INVARIANT chisq p = 0.478

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT NOT PASSED, chisq p = 0
SCALAR N/A
STRICT N/A

+++ TESTING 182th COMBINATION out of 210 possible combinations of 6 items +++
Items to test: ('hitop17', 'hitop129', 'hitop204', 'hitop222', 'hitop236', 'hitop258')

 -----> VALID VS GENPOP <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG chisq p = 0.042
PASSED SECONDARY CRITERIA WITH CFI = 1.0 TLI = 1.002 RMSEA = 0.03

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT chisq p = 0.149
SCALAR N/A
STRICT N/A

 -----> VALID VS ENRICHED <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG INVARIANT chisq p = 0.786

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT NOT PASSED, chisq p = 0
SCALAR N/A
STRICT N/A

 -----> GENPOP VS ENRICHED <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG INVARIANT chisq p = 0.363

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT NOT PASSED, chisq p = 0.003
SCALAR N/A
STRICT N/A

+++ TESTING 183th COMBINATION out of 210 possible combinations of 6 items +++
Items to test: ('hitop114', 'hitop117', 'hitop124', 'hitop129', 'hitop204', 'hitop222')

 -----> VALID VS GENPOP <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG INVARIANT chisq p = 0.996

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT NOT PASSED, chisq p = 0.008
SCALAR N/A
STRICT N/A

 -----> VALID VS ENRICHED <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG INVARIANT chisq p = 0.103

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT chisq p = 0.158
SCALAR N/A
STRICT N/A

 -----> GENPOP VS ENRICHED <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG INVARIANT chisq p = 0.058

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT NOT PASSED, chisq p = 0.01
SCALAR N/A
STRICT N/A

+++ TESTING 184th COMBINATION out of 210 possible combinations of 6 items +++
Items to test: ('hitop114', 'hitop117', 'hitop124', 'hitop129', 'hitop204', 'hitop236')

 -----> VALID VS GENPOP <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG INVARIANT chisq p = 0.987

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT NOT PASSED, chisq p = 0.003
SCALAR N/A
STRICT N/A

 -----> VALID VS ENRICHED <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG INVARIANT chisq p = 0.088

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT chisq p = 0.287
SCALAR N/A
STRICT N/A

 -----> GENPOP VS ENRICHED <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG chisq p = 0.039
PASSED SECONDARY CRITERIA WITH CFI = 0.997 TLI = 0.996 RMSEA = 0.053

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT chisq p = 0.066
SCALAR N/A
STRICT N/A

+++ TESTING 185th COMBINATION out of 210 possible combinations of 6 items +++
Items to test: ('hitop114', 'hitop117', 'hitop124', 'hitop129', 'hitop204', 'hitop258')

 -----> VALID VS GENPOP <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG INVARIANT chisq p = 0.99

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT NOT PASSED, chisq p = 0.002
SCALAR N/A
STRICT N/A

 -----> VALID VS ENRICHED <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG INVARIANT chisq p = 0.075

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT chisq p = 0.698
SCALAR N/A
STRICT N/A

 -----> GENPOP VS ENRICHED <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG chisq p = 0.031
PASSED SECONDARY CRITERIA WITH CFI = 0.998 TLI = 0.996 RMSEA = 0.052

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT chisq p = 0.128
SCALAR N/A
STRICT N/A

+++ TESTING 186th COMBINATION out of 210 possible combinations of 6 items +++
Items to test: ('hitop114', 'hitop117', 'hitop124', 'hitop129', 'hitop222', 'hitop236')

 -----> VALID VS GENPOP <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG INVARIANT chisq p = 0.993

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT NOT PASSED, chisq p = 0.003
SCALAR N/A
STRICT N/A

 -----> VALID VS ENRICHED <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG INVARIANT chisq p = 0.057

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT chisq p = 0.138
SCALAR N/A
STRICT N/A

 -----> GENPOP VS ENRICHED <-----
CONFIG chisq p = 0.041
PASSED SECONDARY CRITERIA WITH CFI = 0.999 TLI = 0.998 RMSEA = 0.049

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT NOT PASSED, chisq p = 0.008
SCALAR N/A
STRICT N/A

+++ TESTING 187th COMBINATION out of 210 possible combinations of 6 items +++
Items to test: ('hitop114', 'hitop117', 'hitop124', 'hitop129', 'hitop222', 'hitop258')

 -----> VALID VS GENPOP <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG INVARIANT chisq p = 0.979

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT NOT PASSED, chisq p = 0.002
SCALAR N/A
STRICT N/A

 -----> VALID VS ENRICHED <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG INVARIANT chisq p = 0.187

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT chisq p = 0.105
SCALAR N/A
STRICT N/A

 -----> GENPOP VS ENRICHED <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG chisq p = 0.041
PASSED SECONDARY CRITERIA WITH CFI = 0.999 TLI = 0.998 RMSEA = 0.049

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT NOT PASSED, chisq p = 0.006
SCALAR N/A
STRICT N/A

+++ TESTING 188th COMBINATION out of 210 possible combinations of 6 items +++
Items to test: ('hitop114', 'hitop117', 'hitop124', 'hitop129', 'hitop236', 'hitop258')

 -----> VALID VS GENPOP <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG INVARIANT chisq p = 0.993

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT NOT PASSED, chisq p = 0
SCALAR N/A
STRICT N/A

 -----> VALID VS ENRICHED <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG INVARIANT chisq p = 0.201

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT chisq p = 0.294
SCALAR N/A
STRICT N/A

 -----> GENPOP VS ENRICHED <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG chisq p = 0.043
PASSED SECONDARY CRITERIA WITH CFI = 0.997 TLI = 0.995 RMSEA = 0.056

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT chisq p = 0.145
SCALAR N/A
STRICT N/A

+++ TESTING 189th COMBINATION out of 210 possible combinations of 6 items +++
Items to test: ('hitop114', 'hitop117', 'hitop124', 'hitop204', 'hitop222', 'hitop236')

 -----> VALID VS GENPOP <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG INVARIANT chisq p = 0.971

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT NOT PASSED, chisq p = 0.004
SCALAR N/A
STRICT N/A

 -----> VALID VS ENRICHED <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG chisq p = 0.026
PASSED SECONDARY CRITERIA WITH CFI = 0.998 TLI = 0.996 RMSEA = 0.037

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT chisq p = 0.231
SCALAR N/A
STRICT N/A

 -----> GENPOP VS ENRICHED <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG INVARIANT chisq p = 0.051

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT NOT PASSED, chisq p = 0
SCALAR N/A
STRICT N/A

+++ TESTING 190th COMBINATION out of 210 possible combinations of 6 items +++
Items to test: ('hitop114', 'hitop117', 'hitop124', 'hitop204', 'hitop222', 'hitop258')

 -----> VALID VS GENPOP <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG INVARIANT chisq p = 0.977

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT NOT PASSED, chisq p = 0.001
SCALAR N/A
STRICT N/A

 -----> VALID VS ENRICHED <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG INVARIANT chisq p = 0.129

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT chisq p = 0.175
SCALAR N/A
STRICT N/A

 -----> GENPOP VS ENRICHED <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG INVARIANT chisq p = 0.061

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT NOT PASSED, chisq p = 0
SCALAR N/A
STRICT N/A

+++ TESTING 191th COMBINATION out of 210 possible combinations of 6 items +++
Items to test: ('hitop114', 'hitop117', 'hitop124', 'hitop204', 'hitop236', 'hitop258')

 -----> VALID VS GENPOP <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG INVARIANT chisq p = 0.758

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT NOT PASSED, chisq p = 0.002
SCALAR N/A
STRICT N/A

 -----> VALID VS ENRICHED <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG INVARIANT chisq p = 0.068

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT chisq p = 0.639
SCALAR N/A
STRICT N/A

 -----> GENPOP VS ENRICHED <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG chisq p = 0.023
PASSED SECONDARY CRITERIA WITH CFI = 1.0 TLI = 1.0 RMSEA = 0.041

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT NOT PASSED, chisq p = 0.04
SCALAR N/A
STRICT N/A

+++ TESTING 192th COMBINATION out of 210 possible combinations of 6 items +++
Items to test: ('hitop114', 'hitop117', 'hitop124', 'hitop222', 'hitop236', 'hitop258')

 -----> VALID VS GENPOP <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG INVARIANT chisq p = 0.932

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT NOT PASSED, chisq p = 0
SCALAR N/A
STRICT N/A

 -----> VALID VS ENRICHED <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG INVARIANT chisq p = 0.092

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT chisq p = 0.136
SCALAR N/A
STRICT N/A

 -----> GENPOP VS ENRICHED <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG chisq p = 0.022
PASSED SECONDARY CRITERIA WITH CFI = 1.0 TLI = 1.002 RMSEA = 0.038

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT NOT PASSED, chisq p = 0
SCALAR N/A
STRICT N/A

+++ TESTING 193th COMBINATION out of 210 possible combinations of 6 items +++
Items to test: ('hitop114', 'hitop117', 'hitop129', 'hitop204', 'hitop222', 'hitop236')

 -----> VALID VS GENPOP <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG INVARIANT chisq p = 0.969

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT NOT PASSED, chisq p = 0.008
SCALAR N/A
STRICT N/A

 -----> VALID VS ENRICHED <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG INVARIANT chisq p = 0.197

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT chisq p = 0.098
SCALAR N/A
STRICT N/A

 -----> GENPOP VS ENRICHED <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG INVARIANT chisq p = 0.179

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT NOT PASSED, chisq p = 0.003
SCALAR N/A
STRICT N/A

+++ TESTING 194th COMBINATION out of 210 possible combinations of 6 items +++
Items to test: ('hitop114', 'hitop117', 'hitop129', 'hitop204', 'hitop222', 'hitop258')

 -----> VALID VS GENPOP <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG INVARIANT chisq p = 0.997

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT NOT PASSED, chisq p = 0.012
SCALAR N/A
STRICT N/A

 -----> VALID VS ENRICHED <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG INVARIANT chisq p = 0.342

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT chisq p = 0.153
SCALAR N/A
STRICT N/A

 -----> GENPOP VS ENRICHED <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG INVARIANT chisq p = 0.2

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT NOT PASSED, chisq p = 0.002
SCALAR N/A
STRICT N/A

+++ TESTING 195th COMBINATION out of 210 possible combinations of 6 items +++
Items to test: ('hitop114', 'hitop117', 'hitop129', 'hitop204', 'hitop236', 'hitop258')

 -----> VALID VS GENPOP <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG INVARIANT chisq p = 0.999

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT NOT PASSED, chisq p = 0.001
SCALAR N/A
STRICT N/A

 -----> VALID VS ENRICHED <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG INVARIANT chisq p = 0.294

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT chisq p = 0.401
SCALAR N/A
STRICT N/A

 -----> GENPOP VS ENRICHED <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG INVARIANT chisq p = 0.109

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT NOT PASSED, chisq p = 0.047
SCALAR N/A
STRICT N/A

+++ TESTING 196th COMBINATION out of 210 possible combinations of 6 items +++
Items to test: ('hitop114', 'hitop117', 'hitop129', 'hitop222', 'hitop236', 'hitop258')

 -----> VALID VS GENPOP <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG INVARIANT chisq p = 1

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT NOT PASSED, chisq p = 0.001
SCALAR N/A
STRICT N/A

 -----> VALID VS ENRICHED <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG INVARIANT chisq p = 0.185

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT chisq p = 0.096
SCALAR N/A
STRICT N/A

 -----> GENPOP VS ENRICHED <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG INVARIANT chisq p = 0.101

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT NOT PASSED, chisq p = 0.004
SCALAR N/A
STRICT N/A

+++ TESTING 197th COMBINATION out of 210 possible combinations of 6 items +++
Items to test: ('hitop114', 'hitop117', 'hitop204', 'hitop222', 'hitop236', 'hitop258')

 -----> VALID VS GENPOP <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG INVARIANT chisq p = 0.994

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT NOT PASSED, chisq p = 0.001
SCALAR N/A
STRICT N/A

 -----> VALID VS ENRICHED <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG INVARIANT chisq p = 0.061

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT chisq p = 0.222
SCALAR N/A
STRICT N/A

 -----> GENPOP VS ENRICHED <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG chisq p = 0.018
PASSED SECONDARY CRITERIA WITH CFI = 0.997 TLI = 0.995 RMSEA = 0.038

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT NOT PASSED, chisq p = 0.001
SCALAR N/A
STRICT N/A

+++ TESTING 198th COMBINATION out of 210 possible combinations of 6 items +++
Items to test: ('hitop114', 'hitop124', 'hitop129', 'hitop204', 'hitop222', 'hitop236')

 -----> VALID VS GENPOP <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG INVARIANT chisq p = 0.735

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT NOT PASSED, chisq p = 0.015
SCALAR N/A
STRICT N/A

 -----> VALID VS ENRICHED <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG INVARIANT chisq p = 0.412

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT NOT PASSED, chisq p = 0.037
SCALAR N/A
STRICT N/A

 -----> GENPOP VS ENRICHED <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG INVARIANT chisq p = 0.675

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT NOT PASSED, chisq p = 0.005
SCALAR N/A
STRICT N/A

+++ TESTING 199th COMBINATION out of 210 possible combinations of 6 items +++
Items to test: ('hitop114', 'hitop124', 'hitop129', 'hitop204', 'hitop222', 'hitop258')

 -----> VALID VS GENPOP <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG INVARIANT chisq p = 0.909

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT NOT PASSED, chisq p = 0.044
SCALAR N/A
STRICT N/A

 -----> VALID VS ENRICHED <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG INVARIANT chisq p = 0.928

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT chisq p = 0.052
SCALAR N/A
STRICT N/A

 -----> GENPOP VS ENRICHED <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG INVARIANT chisq p = 0.469

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT NOT PASSED, chisq p = 0.039
SCALAR N/A
STRICT N/A

+++ TESTING 200th COMBINATION out of 210 possible combinations of 6 items +++
Items to test: ('hitop114', 'hitop124', 'hitop129', 'hitop204', 'hitop236', 'hitop258')

 -----> VALID VS GENPOP <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG INVARIANT chisq p = 0.691

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT NOT PASSED, chisq p = 0.004
SCALAR N/A
STRICT N/A

 -----> VALID VS ENRICHED <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG INVARIANT chisq p = 0.627

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT chisq p = 0.516
SCALAR N/A
STRICT N/A

 -----> GENPOP VS ENRICHED <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG INVARIANT chisq p = 0.492

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT chisq p = 0.1
SCALAR N/A
STRICT N/A

+++ TESTING 201th COMBINATION out of 210 possible combinations of 6 items +++
Items to test: ('hitop114', 'hitop124', 'hitop129', 'hitop222', 'hitop236', 'hitop258')

 -----> VALID VS GENPOP <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG INVARIANT chisq p = 0.596

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT NOT PASSED, chisq p = 0.022
SCALAR N/A
STRICT N/A

 -----> VALID VS ENRICHED <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG INVARIANT chisq p = 0.559

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT NOT PASSED, chisq p = 0.038
SCALAR N/A
STRICT N/A

 -----> GENPOP VS ENRICHED <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG INVARIANT chisq p = 0.666

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT NOT PASSED, chisq p = 0.005
SCALAR N/A
STRICT N/A

+++ TESTING 202th COMBINATION out of 210 possible combinations of 6 items +++
Items to test: ('hitop114', 'hitop124', 'hitop204', 'hitop222', 'hitop236', 'hitop258')

 -----> VALID VS GENPOP <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG INVARIANT chisq p = 0.683

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT NOT PASSED, chisq p = 0.004
SCALAR N/A
STRICT N/A

 -----> VALID VS ENRICHED <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG INVARIANT chisq p = 0.587

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT chisq p = 0.051
SCALAR N/A
STRICT N/A

 -----> GENPOP VS ENRICHED <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG INVARIANT chisq p = 0.695

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT NOT PASSED, chisq p = 0
SCALAR N/A
STRICT N/A

+++ TESTING 203th COMBINATION out of 210 possible combinations of 6 items +++
Items to test: ('hitop114', 'hitop129', 'hitop204', 'hitop222', 'hitop236', 'hitop258')

 -----> VALID VS GENPOP <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG INVARIANT chisq p = 0.898

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT chisq p = 0.1
SCALAR N/A
STRICT N/A

 -----> VALID VS ENRICHED <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG INVARIANT chisq p = 0.918

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT chisq p = 0.059
SCALAR N/A
STRICT N/A

 -----> GENPOP VS ENRICHED <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG INVARIANT chisq p = 0.917

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT NOT PASSED, chisq p = 0.001
SCALAR N/A
STRICT N/A

+++ TESTING 204th COMBINATION out of 210 possible combinations of 6 items +++
Items to test: ('hitop117', 'hitop124', 'hitop129', 'hitop204', 'hitop222', 'hitop236')

 -----> VALID VS GENPOP <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG INVARIANT chisq p = 0.995

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT NOT PASSED, chisq p = 0.029
SCALAR N/A
STRICT N/A

 -----> VALID VS ENRICHED <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG INVARIANT chisq p = 0.125

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT NOT PASSED, chisq p = 0.039
SCALAR N/A
STRICT N/A

 -----> GENPOP VS ENRICHED <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG INVARIANT chisq p = 0.172

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT NOT PASSED, chisq p = 0.002
SCALAR N/A
STRICT N/A

+++ TESTING 205th COMBINATION out of 210 possible combinations of 6 items +++
Items to test: ('hitop117', 'hitop124', 'hitop129', 'hitop204', 'hitop222', 'hitop258')

 -----> VALID VS GENPOP <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG INVARIANT chisq p = 0.96

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT NOT PASSED, chisq p = 0.02
SCALAR N/A
STRICT N/A

 -----> VALID VS ENRICHED <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG INVARIANT chisq p = 0.707

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT NOT PASSED, chisq p = 0.047
SCALAR N/A
STRICT N/A

 -----> GENPOP VS ENRICHED <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG INVARIANT chisq p = 0.277

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT NOT PASSED, chisq p = 0
SCALAR N/A
STRICT N/A

+++ TESTING 206th COMBINATION out of 210 possible combinations of 6 items +++
Items to test: ('hitop117', 'hitop124', 'hitop129', 'hitop204', 'hitop236', 'hitop258')

 -----> VALID VS GENPOP <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG INVARIANT chisq p = 0.999

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT NOT PASSED, chisq p = 0.004
SCALAR N/A
STRICT N/A

 -----> VALID VS ENRICHED <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG INVARIANT chisq p = 0.164

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT chisq p = 0.307
SCALAR N/A
STRICT N/A

 -----> GENPOP VS ENRICHED <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG INVARIANT chisq p = 0.059

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT chisq p = 0.223
SCALAR N/A
STRICT N/A

+++ TESTING 207th COMBINATION out of 210 possible combinations of 6 items +++
Items to test: ('hitop117', 'hitop124', 'hitop129', 'hitop222', 'hitop236', 'hitop258')

 -----> VALID VS GENPOP <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG INVARIANT chisq p = 1

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT NOT PASSED, chisq p = 0.004
SCALAR N/A
STRICT N/A

 -----> VALID VS ENRICHED <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG INVARIANT chisq p = 0.178

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT NOT PASSED, chisq p = 0.04
SCALAR N/A
STRICT N/A

 -----> GENPOP VS ENRICHED <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG INVARIANT chisq p = 0.105

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT NOT PASSED, chisq p = 0.002
SCALAR N/A
STRICT N/A

+++ TESTING 208th COMBINATION out of 210 possible combinations of 6 items +++
Items to test: ('hitop117', 'hitop124', 'hitop204', 'hitop222', 'hitop236', 'hitop258')

 -----> VALID VS GENPOP <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG INVARIANT chisq p = 0.995

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT NOT PASSED, chisq p = 0.003
SCALAR N/A
STRICT N/A

 -----> VALID VS ENRICHED <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG INVARIANT chisq p = 0.133

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT chisq p = 0.05
SCALAR N/A
STRICT N/A

 -----> GENPOP VS ENRICHED <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG INVARIANT chisq p = 0.056

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT NOT PASSED, chisq p = 0
SCALAR N/A
STRICT N/A

+++ TESTING 209th COMBINATION out of 210 possible combinations of 6 items +++
Items to test: ('hitop117', 'hitop129', 'hitop204', 'hitop222', 'hitop236', 'hitop258')

 -----> VALID VS GENPOP <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG INVARIANT chisq p = 1

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT NOT PASSED, chisq p = 0.005
SCALAR N/A
STRICT N/A

 -----> VALID VS ENRICHED <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG INVARIANT chisq p = 0.118

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT chisq p = 0.072
SCALAR N/A
STRICT N/A

 -----> GENPOP VS ENRICHED <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG INVARIANT chisq p = 0.207

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT NOT PASSED, chisq p = 0.002
SCALAR N/A
STRICT N/A

+++ TESTING 210th COMBINATION out of 210 possible combinations of 6 items +++
Items to test: ('hitop124', 'hitop129', 'hitop204', 'hitop222', 'hitop236', 'hitop258')

 -----> VALID VS GENPOP <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG INVARIANT chisq p = 0.818

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT NOT PASSED, chisq p = 0.031
SCALAR N/A
STRICT N/A

 -----> VALID VS ENRICHED <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG INVARIANT chisq p = 0.758

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT NOT PASSED, chisq p = 0.008
SCALAR N/A
STRICT N/A

 -----> GENPOP VS ENRICHED <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG INVARIANT chisq p = 0.214
METRIC INVARIANT NOT PASSED, chisq p = 0.002
SCALAR N/A
STRICT N/A

CFA DONE


Found 1 combination(s) of 6 that is 3-way invariant.
{('hitop1', 'hitop17', 'hitop114', 'hitop129', 'hitop204', 'hitop258'): {'val_gp': ['0.138', '0.067', 'NA', 'NA'], 'val_en': ['0.06', '0.066', 'NA', 'NA'], 'gp_en': ['0.167', '0.255', 'NA', 'NA']}}

{('hitop1',
  'hitop17',
  'hitop114',
  'hitop129',
  'hitop204',
  'hitop258'): {'val_gp': ['0.138', '0.067', 'NA', 'NA'], 'val_en': ['0.06',
   '0.066',
   'NA',
   'NA'], 'gp_en': ['0.167', '0.255', 'NA', 'NA']}}

### 3. (if needed) Check invariant subsets

In [81]:
##  all inv scales
to_test_inv = {'anhedonic_depression': 'anhedonic_depression =~hitop39 + hitop77 + hitop84 + hitop93 + hitop182 + hitop230 + hitop246',
         'anxious_worry': 'anxious_worry =~hitop34 + hitop89 + hitop203 + hitop248',
         'appetite_gain': 'appetite_gain =~hitop120 + hitop243 + hitop275',
         'appetite_loss': 'appetite_loss =~hitop280 + hitop283 + hitop109',
         'cognitive_problems': 'cognitive_problems =~hitop67 + hitop189 + hitop142',
         'hyposomnia': 'hyposomnia =~hitop99 + hitop181 + hitop5 + hitop66 + hitop231',
         'insomnia': 'insomnia =~hitop160 + hitop254 + hitop261 + hitop268',
         'panic': 'panic =~hitop15 + hitop104 + hitop126 + hitop211 + hitop215 + hitop257',
         'separation_insecurity': 'separation_insecurity =~hitop50 + hitop69 + hitop81 + hitop136 + hitop151 + hitop197',
         'shame_guilt': 'shame_guilt =~hitop72 + hitop140 + hitop143 + hitop220',
         'situational_phobia': 'situational_phobia =~hitop16 + hitop165 + hitop225 + hitop247 + hitop278',
         'social_anxiety': 'social_anxiety =~hitop1 + hitop17 + hitop114 + hitop129 + hitop204 + hitop258',
         'well_being': 'well_being =~hitop9 + hitop23 + hitop149 + hitop200 + hitop244 + hitop250 + hitop281'}

with open("logs/mylog_3wayCFA_invsubsets_seed12345.txt", "w") as f:
    with redirect_stdout(f):
        for scale, items in to_test_inv.items():
            # create a neat list of items to test for this scale
            items_only = items.split("=~",1)[1]
            items_list = items_only.split(" + ")
            # test   
            run_specific_cfa(whichscale=scale,\
                         item_list=items_list, \
                         whichcfa='strict')

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]:

R[write to console]: There were 50 or more warnings (use warnings() to see the first 50)
R[write to console]:

RRuntimeError:

In [82]:
##  all inv scales
to_test_inv = {'social_anxiety': 'social_anxiety =~hitop1 + hitop17 + hitop114 + hitop129 + hitop204 + hitop258',
         'well_being': 'well_being =~hitop9 + hitop23 + hitop149 + hitop200 + hitop244 + hitop250 + hitop281'}

with open("logs/mylog_3wayCFA_invsubsets_seed12345.txt", "a") as f:
    with redirect_stdout(f):
        for scale, items in to_test_inv.items():
            # create a neat list of items to test for this scale
            items_only = items.split("=~",1)[1]
            items_list = items_only.split(" + ")
            # test   
            run_specific_cfa(whichscale=scale,\
                         item_list=items_list, \
                         whichcfa='strict')

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

In [23]:
to_test_inv = {'situational_phobia': 'situational_phobia =~hitop16 + hitop165 + hitop225 + hitop247'}

with open("logs/mylog_3wayCFA_invsubsets_seed12345.txt", "a") as f:
    with redirect_stdout(f):
        for scale, items in to_test_inv.items():
            # create a neat list of items to test for this scale
            items_only = items.split("=~",1)[1]
            items_list = items_only.split(" + ")
            # test   
            run_specific_cfa(whichscale=scale,\
                         item_list=items_list, \
                         whichcfa='strict')

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

## 4. Check exclusion items only

In [77]:
to_test_inv = {'anhedonic_depression': 'anhedonic_depression =~hitop92 + hitop123 + hitop157',
                 'social_anxiety': 'social_anxiety =~hitop117 + hitop124 + hitop222 + hitop236',
                 'well_being': 'well_being =~hitop54 + hitop200 + hitop245',
                 'well_being': 'well_being =~hitop54 + hitop106 + hitop245',
                 'well_being': 'well_being =~hitop23 + hitop54 + hitop245'}

with open("logs/mylog_3wayCFA_excludedonly.txt", "w") as f:
    with redirect_stdout(f):
        for scale, items in to_test_inv.items():
            # create a neat list of items to test for this scale
            items_only = items.split("=~",1)[1]
            items_list = items_only.split(" + ")
            # test   
            run_specific_cfa(whichscale=scale,\
                         item_list=items_list, \
                         whichcfa='strict')

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

In [80]:
to_test_inv = {'well_being1': 'well_being =~hitop54 + hitop200 + hitop245',
                 'well_being2': 'well_being =~hitop54 + hitop106 + hitop245',
                 'well_being3': 'well_being =~hitop23 + hitop54 + hitop245'}

with open("logs/mylog_3wayCFA_excludedonly.txt", "a") as f:
    with redirect_stdout(f):
        for scale, items in to_test_inv.items():
            # create a neat list of items to test for this scale
            items_only = items.split("=~",1)[1]
            items_list = items_only.split(" + ")
            # test   
            run_specific_cfa(whichscale=scale,\
                         item_list=items_list, \
                         whichcfa='strict')

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

## For interpretation - check what items mean

In [32]:
scales = {
    'items_anhedonic_depression':['39','77','84','92','93','123','157','182','230','246'],
    'items_anxious_worry': ['20','34','89','203','248','265'],
    'items_appetite_gain': ['120','141','243','275'],
    'items_appetite_loss': ['280','283','109'],
    'items_cognitive_problems': ['67','189','142'],
    'items_hyposomnia': ['99','181','5','66','231'],
    'items_insomnia': ['160','254','261','268'],
    'items_panic': ['15','104','126','211','215','257'],
    'items_separation_insecurity': ['40','50','69','81','113','136','151','197'],
    'items_shame_guilt': ['72','140','143','220'],
    'items_situational_phobia': ['16','165','225','247','278'],
    'items_social_anxiety': ['1','17','114','117','124','129','204','222','236','258'],
    'items_well_being': ['9','23','54','106','149','200','244','245','250','281']}

for scale, items in scales.items():
    print(scale)
    check_hitop_ids(items, my_item_lookup=item_lookup)

items_anhedonic_depression
   hitop39   It felt like there wasn’t anything interesting or fun to do.
   hitop77   I didn’t look forward to seeing friends or family.
   hitop84   I felt depressed.
   hitop92   It took a lot of effort to do everyday activities.
   hitop93   Nothing seemed interesting to me.
   hitop123   Nothing made me laugh.
   hitop157   I had very little energy.
   hitop182   I was unable to enjoy things like I normally do.
   hitop230   I felt emotionally numb.
   hitop246   I was a lot less talkative than usual.


items_anxious_worry
   hitop20   I felt tense.
   hitop34   Thoughts were racing through my head.
   hitop89   I had a lot of nervous energy.
   hitop203   I felt very stressed.
   hitop248   I worried about almost everything.
   hitop265   I was overwhelmed by anxiety.


items_appetite_gain
   hitop120   I could not keep myself from eating.
   hitop141   I thought a lot about food.
   hitop243   I stuffed myself with food.
   hitop275   I ate even when I was not really hungry.


items_appetite_loss
   hitop280   My appetite was poor.
   hitop283   I lost a significant amount of weight without even trying.
   hitop109   I did not feel much like eating.


items_cognitive_problems
Name: htid, dtype: object)Name: item, dtype: object)
   hitop189   I was easily distracted.
   hitop142   I had trouble remembering things.


items_hyposomnia
   hitop99   I needed much less sleep than usual.
   hitop181   I felt like I could keep going and going without ever getting tired.
   hitop5   I had days when I never got tired.
   hitop66   I did not feel tired, even though I was sleeping less than usual.
   hitop231   I felt like I could go for days without sleeping.


items_insomnia
   hitop160   I had trouble staying asleep.
   hitop254   I slept very poorly.
   hitop261   I woke up early and could not get back to sleep.
   hitop268   I lay awake for a long time before falling asleep.


items_panic
   hitop15   I was short of breath.
   hitop104   I felt nauseated.
   hitop126   My heart was racing or pounding.
   hitop211   I was trembling or shaking.
   hitop215   My hands were cold or sweaty.
   hitop257   I felt dizzy or lightheaded.


items_separation_insecurity
   hitop40   I felt insecure about important relationships in my life.
   hitop50   I wanted someone else to make decisions for me.
   hitop69   I wanted other people to take care of me.
   hitop81   I worried that others would abandon me.
   hitop113   I could not handle rejection.
   hitop136   I often felt jealous.
   hitop151   I felt that I needed the approval of others.
   hitop197   I could not stand being alone.


items_shame_guilt
   hitop72   I was disgusted with myself.
   hitop140   I blamed myself for things.
   hitop143   I felt guilty.
   hitop220   I felt ashamed of things I had done.


items_situational_phobia
   hitop16   I avoided riding in elevators.
   hitop165   I was afraid of flying.
   hitop225   I was afraid of the dark.
   hitop247   I was afraid of heights.
   hitop278   I became very anxious during a storm.


items_social_anxiety
   hitop1   I felt shy around other people.
   hitop17   I was uncomfortable meeting new people.
   hitop114   I had difficulty making eye contact with others.
   hitop117   I felt socially awkward.
   hitop124   I avoided situations in which others were likely to watch me.
   hitop129   I avoided performing or giving a talk in front of others.
   hitop204   I felt uncomfortable being the center of attention.
   hitop222   I was uncomfortable entering a room when others already were present.
   hitop236   I felt self-conscious around others.
   hitop258   I found it difficult to speak up in front of others.


items_well_being
   hitop9   I felt like I was having a lot of fun.
   hitop23   I felt cheerful.
   hitop54   It was easy for me to laugh.
   hitop106   I was proud of myself.
   hitop149   I felt good about myself.
   hitop200   I found compliments very encouraging.
   hitop244   I felt optimistic.
   hitop245   I looked forward to things with enjoyment.
   hitop250   I felt like I had a lot of interesting things to do.
   hitop281   I felt that I had a lot to look forward to.

# Whatever else random stuff I want to do

In [16]:
anh_dep_inv = ['hitop39','hitop77','hitop84', 'hitop93','hitop182','hitop230','hitop246']
run_specific_cfa(whichscale='anhedonic_depression',\
                item_list=anh_dep_inv, \
                whichcfa='strict')

FOR SCALE ANHEDONIC_DEPRESSION:

RUN ALL 3-way CFA for items: ['hitop39', 'hitop77', 'hitop84', 'hitop93', 'hitop182', 'hitop230', 'hitop246'].

 -----> VALID VS GENPOP <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG chisq p = 0
PASSED SECONDARY CRITERIA WITH CFI = 0.995 TLI = 0.992 RMSEA = 0.041

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT chisq p = 0.05

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

SCALAR INVARIANT NOT PASSED, chisq p = 0
STRICT N/A

 -----> VALID VS ENRICHED <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG INVARIANT chisq p = 0.843

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT chisq p = 0.083

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

SCALAR INVARIANT NOT PASSED, chisq p = 0
STRICT N/A

 -----> GENPOP VS ENRICHED <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG INVARIANT chisq p = 0.34

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT chisq p = 0.069
SCALAR INVARIANT NOT PASSED, chisq p = 0
STRICT N/A

!!! PASSES 3-WAY INVARIANCE
DONE

0

In [27]:
with open("logs/mylog_3wayCFA_lookingforinv_anhdep_6items_seed12345.txt", "w") as f:
    with redirect_stdout(f):
        for scale in ['anhedonic_depression']:
            print(f'\n\n\n======================================\nTESTING SCALE {scale.upper()}\n======================================\n')
            items = orig_items[scale]
            # create a neat FULL list of items to test for this scale
            items_only = items.split("=~",1)[1]
            items_list = items_only.split(" + ")
            # how many items are there in total?
            howmany = len(items_list)
            how_many_to_try = 6
            print(f'\n-----------------------------\nTESTING n - {i} = {how_many_to_try} ITEMS for scale {scale}\n-----------------------------\n')
            # test cfa
            successful_combinations_for_scale = do_three_way_cfa_ablations(whichscale=scale, whichcfa='metric', howmanyitems=how_many_to_try)
            # if found any number of successful items, save them and stop trying for this scale
            if successful_combinations_for_scale: 
                print(f'\n!!!!! Found at least one invariant subset for SCALE {scale} with ITEMS = {how_many_to_try} (removing {i} items)\n')
                print(successful_combinations_for_scale)
                break

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.



In [22]:
with open("logs/mylog_3wayCFA_lookingforinv_seed12345_v2.txt", "a") as f:
    with redirect_stdout(f):
        for scale in ['situational_phobia']:
            print(f'\n\n\n======================================\nTESTING SCALE {scale.upper()}\n======================================\n')
            items = orig_items[scale]
            # create a neat FULL list of items to test for this scale
            items_only = items.split("=~",1)[1]
            items_list = items_only.split(" + ")
            # how many items are there in total?
            howmany = len(items_list)
            # remove items one by one
            for i in range (1, howmany):
                how_many_to_try = howmany - i
                print(f'\n-----------------------------\nTESTING n - {i} = {how_many_to_try} ITEMS for scale {scale}\n-----------------------------\n')
                if how_many_to_try <= 2: # the min amount of items we can test is 3
                    print("\nWe ran out of items! No inv subset can be found")
                    break
                # test cfa
                successful_combinations_for_scale = do_three_way_cfa_ablations(whichscale=scale, whichcfa='metric', howmanyitems=how_many_to_try)
                # if found any number of successful items, save them and stop trying for this scale
                if successful_combinations_for_scale: 
                    print(f'\n!!!!! Found at least one invariant subset for SCALE {scale} with ITEMS = {how_many_to_try} (removing {i} items)\n')
                    print(successful_combinations_for_scale)
                    break

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

In [33]:
run_specific_cfa(whichscale='well_being', item_list=['hitop9','hitop106', 'hitop149', 'hitop200', 'hitop244', 'hitop250', 'hitop281'], whichcfa='strict')

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

FOR SCALE WELL_BEING:

RUN ALL 3-way CFA for items: ['hitop9', 'hitop106', 'hitop149', 'hitop200', 'hitop244', 'hitop250', 'hitop281'].

 -----> VALID VS GENPOP <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG chisq p = 0.021
PASSED SECONDARY CRITERIA WITH CFI = 1.0 TLI = 1.001 RMSEA = 0.035

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT chisq p = 0.574

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

SCALAR INVARIANT NOT PASSED, chisq p = 0
STRICT N/A

 -----> VALID VS ENRICHED <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG INVARIANT chisq p = 0.099

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT chisq p = 0.071

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

SCALAR INVARIANT NOT PASSED, chisq p = 0
STRICT N/A

 -----> GENPOP VS ENRICHED <-----

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

CONFIG INVARIANT chisq p = 0.182

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.

METRIC INVARIANT chisq p = 0.05
SCALAR INVARIANT NOT PASSED, chisq p = 0
STRICT N/A

!!! PASSES 3-WAY INVARIANCE
DONE

0

# Analysis for BAARS, GAD, PHQ

In [39]:
for c in data_genpop_enriched_full.columns:
    print(c)

caseid
weight
sample_type
screener_1ongoing
screener_2impact
screener_3depression
screener_4anxiety
screener_5attention
consent
mood_yn
FNM_Q25_1
FNM_Q25_2
FNM_Q25_3
FNM_Q25_4
FNM_Q25_5
FNM_Q25_6
FNM_Q25_955
FNM_Q25_933
FNM_Q25_open1
mood_years
FNM_Q27_1
FNM_Q27_2
FNM_Q27_3
FNM_Q27_4
FNM_Q27_5
FNM_Q27_6
FNM_Q27_7
FNM_Q27_8
FNM_Q27_9
FNM_Q27_10
FNM_Q27_11
FNM_Q27_12
FNM_Q27_13
FNM_Q27_14
FNM_Q27_15
FNM_Q27_16
FNM_Q27_17
FNM_Q27_18
FNM_Q27_19
FNM_Q27_955
FNM_Q27_933
FNM_Q27_open1
mood_bothered
anxiety_yn
FNM_Q30_m_1
FNM_Q30_m_2
FNM_Q30_m_3
FNM_Q30_m_4
FNM_Q30_m_5
FNM_Q30_m_6
FNM_Q30_m_7
FNM_Q30_m_8
FNM_Q30_m_955
FNM_Q30_m_933
FNM_Q30_open1
anxiety_years
FNM_Q32_1
FNM_Q32_2
FNM_Q32_3
FNM_Q32_4
FNM_Q32_5
FNM_Q32_6
FNM_Q32_7
FNM_Q32_8
FNM_Q32_9
FNM_Q32_10
FNM_Q32_955
FNM_Q32_933
FNM_Q32_open1
anxiety_bothered
attention_yn
FNM_Q35_m_1
FNM_Q35_m_2
FNM_Q35_m_3
FNM_Q35_m_933
FNM_Q35_open1
attention_years
FNM_Q37_m_1
FNM_Q37_m_2
FNM_Q37_m_3
FNM_Q37_m_4
FNM_Q37_m_5
FNM_Q37_m_6
FNM_Q37_m_7
FNM_Q37_m_8
FNM_Q37_m_9
FNM_Q37_m_955
FNM_Q37_m_933
FNM_Q37_open1
attention_bothered
inattention_1
inattention_2
inattention_3
inattention_4
inattention_5
inattention_6
FNM_Q1_attn
inattention_7
inattention_8
inattention_9
hyperactivity_1
hyperactivity_2
hyperactivity_3
hyperactivity_4
hyperactivity_5
impulsivity_1
impulsivity_2
impulsivity_3
impulsivity_4
sct_1
sct_2
sct_3
sct_4
sct_5
sct_6
sct_7
sct_8
sct_9
gad_1
gad_2
gad_3
gad_4
gad_5
gad_6
gad_7
phq_1
phq_2
phq_3
phq_4
phq_5
phq_6
phq_7
phq_8
hitop157
hitop81
hitop34
hitop54
hitop243
hitop182
hitop69
hitop89
hitop50
check_moderately
hitop129
hitop265
hitop124
hitop231
hitop93
hitop67
hitop245
hitop281
hitop141
hitop40
hitop204
hitop21
hitop236
hitop280
hitop84
hitop120
hitop77
hitop92
hitop258
hitop39
hitop254
hitop215
hitop95
hitop106
hitop283
hitop16
hitop20
hitop189
hitop1
hitop136
hitop246
hitop248
hitop257
hitop114
hitop117
hitop250
hitop200
hitop160
hitop23
hitop165
hitop244
hitop9
hitop142
hitop230
hitop149
hitop247
hitop99
hitop66
hitop240
hitop222
hitop90
hitop113
hitop278
hitop203
hitop159
hitop123
hitop275
hitop268
hitop225
hitop143
hitop151
hitop181
hitop211
hitop17
hitop126
hitop5
hitop261
hitop220
check_notatall
hitop15
hitop72
hitop140
hitop109
hitop197
hitop104
todayinattention_1
todayinattention_2
todayinattention_3
todayinattention_4
todayinattention_5
todayinattention_6
todayinattention_7
todayinattention_8
todayinattention_9
todayhyperactivity_1
todayhyperactivity_2
todayhyperactivity_3
todayhyperactivity_4
todayhyperactivity_5
todayimpulsivity_1
todayimpulsivity_2
todayimpulsivity_3
todayimpulsivity_4
todaysct_1
todaysct_2
todaysct_3
todaysct_4
todaysct_5
todaysct_6
todaysct_7
todaysct_8
todaysct_9
today_na1
todaygad_1
todaygad_2
todaygad_3
todaygad_4
todaygad_5
todaygad_6
todaygad_7
todayphq_1
todayphq_2
todayphq_3
todayphq_4
todayphq_5
todayphq_6
todayphq_7
todayphq_8
today_na2
todayhitop157
todayhitop81
todayhitop34
todayhitop54
todayhitop243
todayhitop182
todayhitop69
todayhitop89
todayhitop50
todaycheck_1
todayhitop129
todayhitop265
todayhitop124
todayhitop231
todayhitop93
todayhitop67
todayhitop245
todayhitop281
today_na3
todayhitop141
todayhitop40
todayhitop204
todayhitop21
todayhitop236
todayhitop280
todayhitop84
todayhitop120
todayhitop77
todayhitop92
todayhitop258
todayhitop39
todayhitop254
todayhitop215
todayhitop95
todayhitop106
todayhitop283
todayhitop16
todayhitop20
todayhitop189
todayhitop1
todayhitop136
todayhitop246
todayhitop248
todayhitop257
todayhitop114
todayhitop117
todayhitop250
todayhitop200
todayhitop160
todayhitop23
todayhitop165
todayhitop244
today_na4
todayhitop9
todayhitop142
todayhitop230
todayhitop149
todayhitop247
todayhitop99
todayhitop66
todayhitop240
todayhitop222
todayhitop90
todayhitop113
todayhitop278
todayhitop203
todayhitop159
todayhitop123
todayhitop275
todayhitop268
todayhitop225
todayhitop143
todayhitop151
todayhitop181
todayhitop211
todayhitop17
todayhitop126
todayhitop5
todayhitop261
todayhitop220
todaycheck_2
todayhitop15
todayhitop72
todayhitop140
todayhitop109
todayhitop197
todayhitop104
today_na5
family_wealth
WHODAS_H2
WHODAS_H3
genhealth
healthinsur_srg_1
healthinsur_srg_2
healthinsur_srg_3
healthinsur_srg_4
healthinsur_srg_5
healthinsur_srg_6
healthinsur_srg_7
healthinsur_srg_8
healthinsur_srg_99
race_client
hispanic
birthyr
gender
sex
educ
marstat
employ
inputstate
faminc_new
child18
starttime
endtime
screener_1ongoing_recontact
screener_2impact_recontact
screener_3depression_recontact
screener_4anxiety_recontact
screener_5attention_recontact
consent_recontact
mood_yn_recontact
FNM_Q25_1_recontact
FNM_Q25_2_recontact
FNM_Q25_3_recontact
FNM_Q25_4_recontact
FNM_Q25_5_recontact
FNM_Q25_6_recontact
FNM_Q25_955_recontact
FNM_Q25_933_recontact
FNM_Q25_open1_recontact
mood_years_recontact
FNM_Q27_1_recontact
FNM_Q27_2_recontact
FNM_Q27_3_recontact
FNM_Q27_4_recontact
FNM_Q27_5_recontact
FNM_Q27_6_recontact
FNM_Q27_7_recontact
FNM_Q27_8_recontact
FNM_Q27_9_recontact
FNM_Q27_10_recontact
FNM_Q27_11_recontact
FNM_Q27_12_recontact
FNM_Q27_13_recontact
FNM_Q27_14_recontact
FNM_Q27_15_recontact
FNM_Q27_16_recontact
FNM_Q27_17_recontact
FNM_Q27_18_recontact
FNM_Q27_19_recontact
FNM_Q27_955_recontact
FNM_Q27_933_recontact
FNM_Q27_open1_recontact
mood_bothered_recontact
anxiety_yn_recontact
FNM_Q30_m_1_recontact
FNM_Q30_m_2_recontact
FNM_Q30_m_3_recontact
FNM_Q30_m_4_recontact
FNM_Q30_m_5_recontact
FNM_Q30_m_6_recontact
FNM_Q30_m_7_recontact
FNM_Q30_m_8_recontact
FNM_Q30_m_955_recontact
FNM_Q30_m_933_recontact
FNM_Q30_open1_recontact
anxiety_years_recontact
FNM_Q32_1_recontact
FNM_Q32_2_recontact
FNM_Q32_3_recontact
FNM_Q32_4_recontact
FNM_Q32_5_recontact
FNM_Q32_6_recontact
FNM_Q32_7_recontact
FNM_Q32_8_recontact
FNM_Q32_9_recontact
FNM_Q32_10_recontact
FNM_Q32_955_recontact
FNM_Q32_933_recontact
FNM_Q32_open1_recontact
anxiety_bothered_recontact
attention_yn_recontact
FNM_Q35_m_1_recontact
FNM_Q35_m_2_recontact
FNM_Q35_m_3_recontact
FNM_Q35_m_933_recontact
FNM_Q35_open1_recontact
attention_years_recontact
FNM_Q37_m_1_recontact
FNM_Q37_m_2_recontact
FNM_Q37_m_3_recontact
FNM_Q37_m_4_recontact
FNM_Q37_m_5_recontact
FNM_Q37_m_6_recontact
FNM_Q37_m_7_recontact
FNM_Q37_m_8_recontact
FNM_Q37_m_9_recontact
FNM_Q37_m_955_recontact
FNM_Q37_m_933_recontact
FNM_Q37_open1_recontact
attention_bothered_recontact
inattention_1_recontact
inattention_2_recontact
inattention_3_recontact
inattention_4_recontact
inattention_5_recontact
inattention_6_recontact
FNM_Q1_attn_recontact
inattention_7_recontact
inattention_8_recontact
inattention_9_recontact
hyperactivity_1_recontact
hyperactivity_2_recontact
hyperactivity_3_recontact
hyperactivity_4_recontact
hyperactivity_5_recontact
impulsivity_1_recontact
impulsivity_2_recontact
impulsivity_3_recontact
impulsivity_4_recontact
sct_1_recontact
sct_2_recontact
sct_3_recontact
sct_4_recontact
sct_5_recontact
sct_6_recontact
sct_7_recontact
sct_8_recontact
sct_9_recontact
gad_1_recontact
gad_2_recontact
gad_3_recontact
gad_4_recontact
gad_5_recontact
gad_6_recontact
gad_7_recontact
phq_1_recontact
phq_2_recontact
phq_3_recontact
phq_4_recontact
phq_5_recontact
phq_6_recontact
phq_7_recontact
phq_8_recontact
hitop157_recontact
hitop81_recontact
hitop34_recontact
hitop54_recontact
hitop243_recontact
hitop182_recontact
hitop69_recontact
hitop89_recontact
hitop50_recontact
check_moderately_recontact
hitop129_recontact
hitop265_recontact
hitop124_recontact
hitop231_recontact
hitop93_recontact
hitop67_recontact
hitop245_recontact
hitop281_recontact
hitop141_recontact
hitop40_recontact
hitop204_recontact
hitop21_recontact
hitop236_recontact
hitop280_recontact
hitop84_recontact
hitop120_recontact
hitop77_recontact
hitop92_recontact
hitop258_recontact
hitop39_recontact
hitop254_recontact
hitop215_recontact
hitop95_recontact
hitop106_recontact
hitop283_recontact
hitop16_recontact
hitop20_recontact
hitop189_recontact
hitop1_recontact
hitop136_recontact
hitop246_recontact
hitop248_recontact
hitop257_recontact
hitop114_recontact
hitop117_recontact
hitop250_recontact
hitop200_recontact
hitop160_recontact
hitop23_recontact
hitop165_recontact
hitop244_recontact
hitop9_recontact
hitop142_recontact
hitop230_recontact
hitop149_recontact
hitop247_recontact
hitop99_recontact
hitop66_recontact
hitop240_recontact
hitop222_recontact
hitop90_recontact
hitop113_recontact
hitop278_recontact
hitop203_recontact
hitop159_recontact
hitop123_recontact
hitop275_recontact
hitop268_recontact
hitop225_recontact
hitop143_recontact
hitop151_recontact
hitop181_recontact
hitop211_recontact
hitop17_recontact
hitop126_recontact
hitop5_recontact
hitop261_recontact
hitop220_recontact
check_notatall_recontact
hitop15_recontact
hitop72_recontact
hitop140_recontact
hitop109_recontact
hitop197_recontact
hitop104_recontact
todayinattention_1_recontact
todayinattention_2_recontact
todayinattention_3_recontact
todayinattention_4_recontact
todayinattention_5_recontact
todayinattention_6_recontact
todayinattention_7_recontact
todayinattention_8_recontact
todayinattention_9_recontact
todayhyperactivity_1_recontact
todayhyperactivity_2_recontact
todayhyperactivity_3_recontact
todayhyperactivity_4_recontact
todayhyperactivity_5_recontact
todayimpulsivity_1_recontact
todayimpulsivity_2_recontact
todayimpulsivity_3_recontact
todayimpulsivity_4_recontact
todaysct_1_recontact
todaysct_2_recontact
todaysct_3_recontact
todaysct_4_recontact
todaysct_5_recontact
todaysct_6_recontact
todaysct_7_recontact
todaysct_8_recontact
todaysct_9_recontact
today_na1_recontact
todaygad_1_recontact
todaygad_2_recontact
todaygad_3_recontact
todaygad_4_recontact
todaygad_5_recontact
todaygad_6_recontact
todaygad_7_recontact
todayphq_1_recontact
todayphq_2_recontact
todayphq_3_recontact
todayphq_4_recontact
todayphq_5_recontact
todayphq_6_recontact
todayphq_7_recontact
todayphq_8_recontact
today_na2_recontact
todayhitop157_recontact
todayhitop81_recontact
todayhitop34_recontact
todayhitop54_recontact
todayhitop243_recontact
todayhitop182_recontact
todayhitop69_recontact
todayhitop89_recontact
todayhitop50_recontact
todaycheck_1_recontact
todayhitop129_recontact
todayhitop265_recontact
todayhitop124_recontact
todayhitop231_recontact
todayhitop93_recontact
todayhitop67_recontact
todayhitop245_recontact
todayhitop281_recontact
today_na3_recontact
todayhitop141_recontact
todayhitop40_recontact
todayhitop204_recontact
todayhitop21_recontact
todayhitop236_recontact
todayhitop280_recontact
todayhitop84_recontact
todayhitop120_recontact
todayhitop77_recontact
todayhitop92_recontact
todayhitop258_recontact
todayhitop39_recontact
todayhitop254_recontact
todayhitop215_recontact
todayhitop95_recontact
todayhitop106_recontact
todayhitop283_recontact
todayhitop16_recontact
todayhitop20_recontact
todayhitop189_recontact
todayhitop1_recontact
todayhitop136_recontact
todayhitop246_recontact
todayhitop248_recontact
todayhitop257_recontact
todayhitop114_recontact
todayhitop117_recontact
todayhitop250_recontact
todayhitop200_recontact
todayhitop160_recontact
todayhitop23_recontact
todayhitop165_recontact
todayhitop244_recontact
today_na4_recontact
todayhitop9_recontact
todayhitop142_recontact
todayhitop230_recontact
todayhitop149_recontact
todayhitop247_recontact
todayhitop99_recontact
todayhitop66_recontact
todayhitop240_recontact
todayhitop222_recontact
todayhitop90_recontact
todayhitop113_recontact
todayhitop278_recontact
todayhitop203_recontact
todayhitop159_recontact
todayhitop123_recontact
todayhitop275_recontact
todayhitop268_recontact
todayhitop225_recontact
todayhitop143_recontact
todayhitop151_recontact
todayhitop181_recontact
todayhitop211_recontact
todayhitop17_recontact
todayhitop126_recontact
todayhitop5_recontact
todayhitop261_recontact
todayhitop220_recontact
todaycheck_2_recontact
todayhitop15_recontact
todayhitop72_recontact
todayhitop140_recontact
todayhitop109_recontact
todayhitop197_recontact
todayhitop104_recontact
today_na5_recontact
family_wealth_recontact
WHODAS_H2_recontact
WHODAS_H3_recontact
starttime_recontact
endtime_recontact
passed_checks
passed_grid
passed_grid_initialonly
passed_list
passed_checks_recontact
passed_grid_recontact
passed_list_recontact
whichdata

In [51]:
other_scales = {'hitop_SUM': 'hitop_SUM =~hitop_anhedonic_depression + hitop_anxious_worry + hitop_appetite_gain + hitop_appetite_loss + hitop_cognitive_problems + hitop_hyposomnia + hitop_indecisiveness + hitop_insomnia + hitop_panic + hitop_separation_insecurity + hitop_shame_guilt + hitop_situational_phobia + hitop_social_anxiety', 
    'phq_SUM': 'phq_SUM =~phq_1 + phq_2 + phq_3 + phq_4 + phq_5 + phq_6 + phq_7 + phq_8',
    'gad_SUM': 'gad_SUM =~gad_1 + gad_2 + gad_3 + gad_4 + gad_5 + gad_6 + gad_7',
    'baars_inattention_SUM': 'baars_inattention_SUM =~inattention_1 + inattention_2 + inattention_3 + inattention_4 + inattention_5 + inattention_6 + inattention_7 + inattention_8 + inattention_9',
    'baars_hyperactivity_SUM': 'baars_hyperactivity_SUM =~hyperactivity_1 + hyperactivity_2 + hyperactivity_3 + hyperactivity_4 + hyperactivity_5',
    'baars_impulsivity_SUM': 'baars_impulsivity_SUM =~impulsivity_1 + impulsivity_2 + impulsivity_3 + impulsivity_4',
    'baars_sct_SUM': 'baars_sct_SUM =~sct_1 + sct_2 + sct_3 + sct_4 + sct_5 + sct_6 + sct_7 + sct_8 + sct_9'} 

with open("logs/mylog_3wayCFA_baarsgadphq_seed12345.txt", "w") as f:
    with redirect_stdout(f):
        for scale, items in other_scales.items():
            print(f'\n\n\n======================================\nTESTING SCALE {scale.upper()}\n======================================\n')
            print(f"Items: {items}")
        
            items_only = items.split("=~",1)[1]
            items_list = items_only.split(" + ")
        
            # +++ GENPOP VS ENRICHED +++ 
            print('\n -----> GENPOP VS ENRICHED <----- ')
            flag_metric_gp_en, pconfig_gp_en, pmetric_gp_en, pscalar_gp_en, pstrict_gp_en = cfa_helper_func(\
                            scalename = scale,\
                            list_of_items = items_list,\
                            do_metric = True, \
                            do_scalar = True, \
                            do_strict = True, \
                            mydata_python = data_genpop_enriched_full, \
                            mydata_temp_path = path_to_helpfile)

R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.


R[write to console]: No AFIs were selected, so only chi-squared will be permuted.